### ISSUE TITLE
IOPs implementation details

### ISSUE THREAD

**Issue by cjellick** [rancher/longhorn#101]
Assumptions:
Since the replicas are the ones that actually write to disk, our goals it to apply IOPs scheduling and limiting to the replicas (as opposed to the controller or the VM).

**EDIT 6/2:** We are not exposing this functionality to non-longhorn volumes at this point. Moreover, in the UI, only VM disks will have it.

Constraints:
Docker implements iops limiting on a per-device basis, so you need to know where the data be written on the file system and then figure out what device that maps to.

Implementation:

1. When creating a VM, the user specifies read and write IOPs (two separate fields) for each disk on the vm, just like they do for disk size. This gets translated to driver-opts for the volume that is passed to the docker longhorn driver.
1. When the longhorn driver sees these iops options, it adds them to the replica container as scheduling labels AND to the replica container's run command as actual parameters, but with a “logical” name that we will replace when the container is actually started by python-agent. So, the labels and fields on the rancher container will look like this:

    ```
    “labels": {
      “io.rancher.resource.read_iops.vol_name”: 10000,
      “io.rancher.resource.write_iops.vol_name”: 10000,
    },
    "driverReadIops": {
      “rancher-volume”: 10000
    },
    “driverWriteIops": {
      “rancher-volume”: 10000
    }
   ```
1. The scheduler will schedule the replicas based off the new iops scheduling labels, just like it does for disk size. It is getting the available iops from the host stats reporting that we already have (but are currently enhancing to include iops output from fio).
1. When python-agent sees a driverRead/WriteIops entry with a key of “rancher-volume,” it will interpret that to mean “replace rancher-volume with the device where /var/lib/docker is mounted." So at runtime, python-agent will figure out that /var/lib/docker maps back do /dev/sda and the actual command passed to docker will be —read-iops /dev/sda:10000

Limitations/gotchas:
Users can and do configure docker to run somewhere other than /var/lib/docker. When they do, it is usually because they have a special disk mounted just for docker. So, for both calculating available iops and adding the —read-iops command, we should either except that we are hardcoding /var/lib/docker and it could be wrong or we should intelligently determine where docker is actually configured to write to based on the output of `docker info`.

These new iops fields are not implemented yet in docker-py. We’ll need to patch and upstream it in order to use them.

This solution is again constrained to a single disk because replicas are unintelligently writing to wherever  docker is configured to write volumes to. As with disk size, if we want to support multiple disks, we have to implement multi-disk intelligence in general

EDIT 6/2: added vol_name to label

**Comment by jimengliu** [comment]
disksize label has volume name as part of label name, should iops have that too ? Such as io.rancher.resource.write_iops.volume1.  Or since we only support one disk, this does not matter for now ?

**Comment by cjellick** [comment]
@jimengliu I'm thinking we should add volume name to the label for consistency and to prep for the day when we do multi-disk. Do you agree?

**Comment by jimengliu** [comment]
yes, but currently scheduler just needs to get the prefix "io.rancher.resource.write_iops" to schedule iops against the single device that FIO returned via PyAgent.

**Comment by cjellick** [comment]
agreed. so we'll add volume name, but in the scheduler, it wont have meaning/function right now

**Comment by jimengliu** [comment]
agreed.

**Comment by cjellick** [comment]
implemented. closing.
