### ISSUE TITLE
FlexVolume driver deployer doesn't redeploy in certain conditions

### ISSUE THREAD

**Issue by ttpcodes** [rancher/longhorn#102]
Occasionally, when upgrading the `longhorn-flexvolume-driver-deployer` Deployment, the old `longhorn-flexvolume-driver` DaemonSet will be brought down, but a new one won't be brought up in its place. The issue seems to happen whenever the old `deployer` and new `deployer` both still exist after the old DaemonSet has been destroyed. It appears to be a race condition, but I haven't had more time to replicate and test the issue more in depth.

**Comment by yasker** [comment]
Push to v0.4

**Comment by yasker** [comment]
Seems fixed by https://github.com/rancher/longhorn-manager/commit/8dd5e3f709663cd4cc19393ff8e721b37792cf9f
