### ISSUE TITLE
Provisioner doesn't work with v1.10+ even if Flexvolume driver was chosen manually

### ISSUE THREAD

**Issue by niusmallnan** [rancher/longhorn#106]
If it’s v1.8 or v1.9, Flexvolume Plugin would be deployed.
If it’s v1.10+, CSI would be deployed.
When CSI driver has been chosen, the built-in Longhorn provisioner will be disabled.

But if Flexvolume driver was chosen manually on Kubernetes v1.10+, we should make the built-in Longhorn provisioner work, because Flexvolume needs it.

**Comment by yasker** [comment]
We will need to move the Flexvolume provisioner into the driver code, and use external API instead of internal API to operate on the Longhorn volume.

We will run only one copy of the provisioner in the cluster then.

**Comment by yasker** [comment]
Fixed.
