### ISSUE TITLE
UI: Issues with volume detail page and node page.

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#111]
In Volume Detail page:
- [x] Dropdown action `Attach` doesn't work.
- [x] Rename `Create A Backup` to `Create Backup`. Also in the Volume overview page.
- [x] Raname `HOST` to `Attached Node` to keep consistency with the volume list
- [x] Update `Frontend` and `Endpoint` to keep consistency with the volume list

In Node page:
- [x] For some reason, the replicas detail list in the node pages shows replicas are `error` when in detached state.

In Volume List page
- [x] Add frontend choices in the volume creation. It can be `blockdev` or `iscsi`. `blockdev` is the default. Name exposed to the user can be `Block Device` or `iSCSI`.

**Comment by ly5156** [comment]
Rename Create A Backup to Create Backup. Also in the Volume overview page.

**Comment by yasker** [comment]
https://github.com/rancher/longhorn-ui/pull/30

**Comment by yasker** [comment]
@ly5156 For some reason, the replicas in the node list always shows in `unknown` state for me.

**Comment by ly5156** [comment]
@yasker replicat.running is true and replica.mode value is empty string(''),  what state should to be shown?

**Comment by yasker** [comment]
@ly5156 

I saw `replica.running && replica.mode == "RW"` when node page shows the replica is unknown.
And `!replica.running && replica.failedAt =="" ` result in replica mode `Failed`.

It should be like this, and it should be the same with the status we use in the volume detail page:
```
`stopped`: replica is not running && replica.failedAt == ""
`running`: replica.running && replica.mode == ""
`healthy`: replica.running && replica.mode == "RW"
`rebuilding`: replica.running && replica.mode == "WO"
`error`: replica.running && replica.mode == "ERR"
`failed`: replica.failedAt != ""
```

**Comment by yasker** [comment]
Fixed by: https://github.com/rancher/longhorn-ui/pull/35
