### ISSUE TITLE
Issue deploying Flexvolume driver

### ISSUE THREAD

**Issue by webts** [rancher/longhorn#115]
Im getting the following errors when deploying longhorn on rancher (RKE | Rancher v2.0.6 | Custom cluster)

rancher/longhorn-engine:31c42f0
rancher/longhorn-manager:58cbdda
rancher/longhorn-ui:23e53f0

```
INFO[0000] User specified Flexvolume dir at: /var/lib/kubelet/volumeplugins
FATA[0000] Error deploying Flexvolume driver: daemonsets.apps "longhorn-flexvolume-driver" is forbidden: User "system:serviceaccount:longhorn:longhorn-service-account" cannot get daemonsets.apps in the namespace "longhorn"
```
_logs from longhorn-flexvolume-driver-deployer pod_

```
E0717 01:07:38.418811       1 reflector.go:205] github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta2.DaemonSet: daemonsets.apps is forbidden: User "system:serviceaccount:longhorn:longhorn-service-account" cannot list daemonsets.apps at the cluster scope
E0717 01:07:38.418950       1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E0717 01:07:38.449159       1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.EngineImage: engineimages.longhorn.rancher.io is forbidden: User "system:serviceaccount:longhorn:longhorn-service-account" cannot list engineimages.longhorn.rancher.io at the cluster scope
```
_logs from longhorn-manager pod_

**Comment by yasker** [comment]
@webts You're using this commit?

commit b0cc34189848879d01e9c6b34fbf4e3c37cc8c45
Author: Sheng Yang <sheng@yasker.org>
Date:   Mon Jul 2 14:13:07 2018 -0700

    Update images and default Flexvolume location

    Engine to rancher/longhorn-engine:31c42f0
    Manager to rancher/longhorn-manager:58cbdda
    UI to rancher/longhorn-ui:23e53f0

    Also update the default Flexvolume location to the one used by RKE. See the
    inline comments for the other options.

Looks like you're reusing the yaml file from the older version? This is the dev tree, doesn't support the upgrade. You might lose data by doing it. You need to deploy a new cluster for it.

The error is because the change for `deploy/01-prerequisite/` needs to be applied.

**Comment by webts** [comment]
@yasker I see, that would be it. I'm using images from that commit as suggested from this issue https://github.com/rancher/longhorn/issues/99. However im deploying via Rancher > Catalog Apps > Longhorn and changing the default images. 

What deployment config do you suggest using? /rancher/longhorn/master/deploy/longhorn.yaml seems to be outdated as well

**Comment by yasker** [comment]
@webts If you really want to try with upgrade (with the risk of losing data), you can try this commit instead.

Note: we will not provide an upgrade path from this commit. It's purely experimental. it's still possible to lose the data. Use it at your own risk.

```
commit addaf4fbb2f74e8af41572f77322075e05afba20
Author: Sheng Yang <sheng@yasker.org>
Date:   Mon Jul 9 19:35:47 2018 -0700

    deploy: Update image and configuration for CSI

    Manager image: rancher/longhorn-manager:cc732c2
    UI image: rancher/longhorn-ui:bc9271d
```

Use those command to upgrade:
```
kubectl delete -f deploy/02-components/
kubectl apply -f deploy/01-prerequisite/
kubectl create -f deploy/02-components/
```

**Comment by webts** [comment]
@yasker great, thank you will give it a go. (just testing so do not mind loosing data)

**Comment by yasker** [comment]
@webts https://github.com/rancher/longhorn is our v0.2 release (plus a little bit stability update). We're approaching our v0.3 release. We will support the upgrade from v0.2 to v0.3.

**Comment by yasker** [comment]
@webts In fact, if you're using v1.10, this commit is maybe better since it doesn't involve CSI (which we will enable by default in v1.10)

```
commit 98dd3f8fb20ad86e95fbd0429932f015c8c0b7c6
Author: Sheng Yang <sheng@yasker.org>
Date:   Fri Jul 6 19:27:42 2018 -0700

    Update images

    Manager: rancher/longhorn-manager:d5227ec
    UI: rancher/longhorn-ui:436d961

    Flexvolume driver has been updated. Need to redeploy for the testing.
```

**Comment by webts** [comment]
@yasker noted, will give it a go, thank you

**Comment by yasker** [comment]
Close the issue for now. Please reopen if the solution doesn't work.
