### ISSUE TITLE
Deleting the volume doesn't refresh the page automatically

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#117]
The volume will be stuck in `deleting` state until refresh.

**Comment by yasker** [comment]
Let me know if it's the backend issue.

**Comment by ly5156** [comment]
@yasker 
the data which the websocket pushed miss data property

**Comment by yasker** [comment]
@ly5156 Rancher API library defines `data` field as `omitempty`, so it won't show in the json if it's empty.

I am afraid frontend needs to deal with it, and treat the non-exist as the empty.
