### ISSUE TITLE
VM is not able to start after ROOT volume is restore from a backup.

### ISSUE THREAD

**Issue by sangeethah** [rancher/longhorn#122]
Rancher-server version - from snapshot-and-backup branch in https://github.com/cjellick/cattle.git
Longhorn template version - yasker/longhorn:dd1fe7f from https://github.com/yasker/longhorn-catalog

Steps to reproduce the problem:
Deploy a VM with "ROOT" and "DATA" disk on longhorn.
Take a snapshot of "ROOT" volume.
Create a back up from snapshot.
Stop VM.
Restore ROOT volume of the VM from backup.

Start VM.
Vm is not able to boot.

<img width="880" alt="screen shot 2016-06-03 at 12 57 07 pm" src="https://cloud.githubusercontent.com/assets/4266958/15791535/cde2cfaa-298c-11e6-9a4f-c6bf8a0a3231.png">

**Comment by yasker** [comment]
Reproduced with https://github.com/rancher/longhorn/pull/134

**Comment by yasker** [comment]
#134 should fix this.

**Comment by sangeethah** [comment]
Tested with longhorn version - cjellick/longhorn:dev-f04b6af
Rancher-server version - latest build master

Steps to reproduce the problem:
Deploy a VM with "ROOT" and "DATA" disk on longhorn.
Take few snapshots of "ROOT" volume.
Create a back up from one of the snapshot.

backup is stuck in "creating" state forever.

Following error seen in 

```
6/9/2016 11:55:27 AMtime="2016-06-09T18:55:27Z" level=error msg="stat /base_image/ubuntu-14.04-amd64.img: no such file or directory"
6/9/2016 11:55:27 AMtime="2016-06-09T18:55:27Z" level=info msg="Error running sbackup [sbackup create volume-snap-ac524290-b4e3-446a-83ff-83c04a7206b9.img --dest vfs:///var/lib/rancher/longhorn/backups/target1/aae9cb4b-3fed-4f33-8977-2cedfa7cacfa --volume test110932_root-snap5-backup4test344728_1-968e4a6-root]: exit status 1"
6/9/2016 11:55:27 AMtime="2016-06-09T18:55:27Z" level=info msg="Error running sbackup [sbackup create volume-snap-ac524290-b4e3-446a-83ff-83c04a7206b9.img --dest vfs:///var/lib/rancher/longhorn/backups/target1/aae9cb4b-3fed-4f33-8977-2cedfa7cacfa --volume test110932_root-snap5-backup4test344728_1-968e4a6-root]: 1"
6/9/2016 11:55:27 AMtime="2016-06-09T18:55:27Z" level=error msg="Failed to launch agent.Process{Resource:client.Resource{Id:\"23\", Type:\"process\", Links:map[string]string(nil), Actions:map[string]string(nil)}, ProcessType:\"backup\", SrcFile:\"volume-snap-ac524290-b4e3-446a-83ff-83c04a7206b9.img\", DestFile:\"vfs:///var/lib/rancher/longhorn/backups/target1/aae9cb4b-3fed-4f33-8977-2cedfa7cacfa\", Host:\"test110932_root-snap5-backup4test344728_1-968e4a6-root\", Port:0, ExitCode:1, Output:\"\", Created:time.Time{sec:0, nsec:0, loc:(*time.Location)(0x11ca440)}}: exit status 1"
```

**Comment by sangeethah** [comment]
Tested with longhorn version - cjellick/longhorn:dev-8698fe1 and latest cattle build form jimeng's branch.
VMs are able to start  successfully after ROOT volume is restore from a backup.
