### ISSUE TITLE
`storage-longhorn` code access

### ISSUE THREAD

**Issue by richardprice** [rancher/longhorn#13]
Hey,

While trying to understand the fundamentals of getting Longhorn to work across multiple nodes (not in a HA multi-host environment, but accessing volumes on other nodes while keeping storage on one host), I realised that the code repo for the `storage-longhorn` component isn't available publicly.

Is this something that will be released in due course, or will it remain closed?

For reference, the following components have public repositories:

`longhorn-ui` - https://github.com/rancher/longhorn-ui
`longhorn-engine` - https://github.com/rancher/longhorn-engine
`longhorn-manager` - https://github.com/rancher/longhorn-manager

Just missing a crucial part of the equation - `storage-longhorn`

**Comment by yasker** [comment]
It's current in a PR for Rancher storage. https://github.com/rancher/storage/pull/49

We're planning to clean it up and get it merged soon.
