### ISSUE TITLE
Rancher OS host needs to be packaged with nfs client libraries.

### ISSUE THREAD

**Issue by sangeethah** [rancher/longhorn#130]
Rancher-server version - from snapshot-and-backup branch in https://github.com/cjellick/cattle.git
Longhorn template version - yasker/longhorn:dd1fe7f from https://github.com/yasker/longhorn-catalog

For taking backup of snapshots and being able to recover the volumes from backups , Rancher OS hosts needs to be able to do nfs mounts to the NFS shared backup store.

Currently , we are not able to do nfs mounts to the NFS shared backup store. 
Following steps had to be done manually for nfs mount to succeed:

Enable ubuntu-console.
sudo apt-get update
sudo apt-get install nfs-common

**Comment by cjellick** [comment]
Fixed.

**Comment by sangeethah** [comment]
Tested with longhorn version - cjellick/longhorn:dev-8698fe1 and latest cattle build form jimeng's branch.
There is no need  for doing any manual steps after the addition of ROS host for snapshots  to be backedup to a NFS store which is added as backup target in rancher server.
