### ISSUE TITLE
Test: failure due to sometime cannot get the updated result immediately

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#133]
Need to confirm it's expected or not. Can be due to Etcd eventually consistency, or K8S API server layer cache.

Error example:
```
        # try again, this time let's try detach
        volume.engineUpgrade(image=wrong_engine_upgrade_image)
        volume = client.by_id_volume(volume["name"])
>       assert volume["engineImage"] == wrong_engine_upgrade_image
E       assert 'rancher/long...ngine:31c42f0' == 'rancher/longh...t.1-1.1-1.1-1'
E         - rancher/longhorn-engine:31c42f0
E         + rancher/longhorn-test:version-test.1-1.1-1.1-1

test_engine_upgrade.py:409: AssertionError
```

**Comment by yasker** [comment]
@JacieChao Can you investigate this issue? Some ideas to test:

1. If it's the issue from k8s cache layer, then direct API call to the API server should result in a consistent response. It can be verified by not using lister/informer, but direct API call to operate on the CRD. You can write a simple program to do e.g. create then immediately check the object, update then immediately check the object, delete then immediate get list, for e.g. 10000 times. If it failed, then the issue is from the k8s API server (probably etcd).
2. If case 1 failed, then try use etcd api to talk to the etcd directly. See if it's etcd or not.
3. If case 1 success without error, the it's maybe the issue with the cache layer, operated by the lister/informer. You should able to verify that by using lister in the above example as well.


We should able to narrow down the case to one of those, then deal with it from there.

**Comment by JacieChao** [comment]
@yasker 
According to my investigation, Here's my test result.
1. When I running case 1 in my cluster, I got some errors which is not occurred very frequently.
```
{"log":"update settings error : Operation cannot be fulfilled on settings.longhorn.rancher.io \"storage-minimal-available-percentage\": StorageError: invalid object, Code: 4, Key: /registry/longhorn.rancher.io/settings/longhorn-system/storage-minimal-available-percentage, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 159735d3-93aa-11e8-87cb-029b17797472, UID in object meta: 15d33d0e-93aa-11e8-87cb-029b17797472 \r\n","stream":"stdout","time":"2018-07-30T03:38:55.476770115Z"}
{"log":"update settings complete, result is \u0026{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:\u003cnil\u003e DeletionGracePeriodSeconds:\u003cnil\u003e Labels:map[] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Setting:{Value:}} \r\n","stream":"stdout","time":"2018-07-30T03:38:55.477005857Z"}
```
This is one of the errors which will cause update fail. But I didn't get this error after recreate a cluster so I'm not sure the occasion of causing this error. Update conflict error is happened more often.

2. Case 2 works well in my test.

Finally, In my opinion, maybe we need to add a retry logic in API to deal with both `update conflict error` and `storage error`.

**Comment by yasker** [comment]
Push to v0.4.

**Comment by yasker** [comment]
Sounds like this: https://github.com/etcd-io/etcd/issues/741

**Comment by yasker** [comment]
The workaround is in place.

We will still track this for a proper fix.
