### ISSUE TITLE
Creating volume backup time takes too long and no feedback on the front end

### ISSUE THREAD

**Issue by ly5156** [rancher/longhorn#143]
1.  After clicking the backup button, jump to the backup page, and you can't see the backup information immediately.  Users need to refresh the page multiple times to see the results

2. After clicking the backup button, there is no feedback on the front end, the user will mistakenly think that the backup function is not good, and will click the backup button multiple times in succession.

**Comment by yasker** [comment]
Push to v0.4. We will have backup progress then.

**Comment by yasker** [comment]
We did a simple solution as in #174 for this release.
