### ISSUE TITLE
Hide Longhorn and network containers in Host Page

### ISSUE THREAD

**Issue by will-chan** [rancher/longhorn#145]
Either permanently hide or default to hiding the ability to see network and longhorn containers on the host infra page.

**Comment by cjellick** [comment]
This visualization of which volume containers are on which hosts and what state they are in is an extremely important debugging tool for me. If we do this, please make it a setting that I can unset.

**Comment by sangeethah** [comment]
Tested with UI - v1.1.5 shipped using rancher-server version -  v1.1.0-storage-1.

Longhorn related containers and network agent are not shown in hosts view by default.
