### ISSUE TITLE
backup/restore base image

### ISSUE THREAD

**Issue by LLParse** [rancher/longhorn#146]
Backup should record the volume's base image.
Restore should use the backup's base image as the restored volume's base image.

**Comment by LLParse** [comment]
https://github.com/rancher/longhorn-engine/pull/313
https://github.com/rancher/longhorn-manager/pull/146

Test passed with https://github.com/rancher/longhorn-tests/pull/94

**Comment by LLParse** [comment]
https://github.com/rancher/longhorn-ui/pull/56

**Comment by yasker** [comment]
Done.
