### ISSUE TITLE
Attempt to use volume failed - timeout waiting for API

### ISSUE THREAD

**Issue by VAdamec** [rancher/longhorn#15]
I have four servers (RHEL 7.3 (Maipo)) in Docker Swarm cluster, then followed https://github.com/rancher/longhorn/wiki/Multi-Host-Setup-Guide.

```
ID                            HOSTNAME                  STATUS              AVAILABILITY        MANAGER STATUS
39usnnx3hel30rc8mu2ifut4j *   rancher-longhorn-lab004   Ready               Active              Leader
k9tnmupa05bnn3ezbfkmmtysk     rancher-longhorn-lab002   Ready               Active
sk83z70y863oyzfseium4oeb5     rancher-longhorn-lab001   Ready               Active
u79op8ofsihs61sc1ghl2x0g8     rancher-longhorn-lab003   Ready               Active
```

Cluster seems to be ok, in UI I see all four servers, also created volumes and replicase. But I'm unable to do basic thing - mount volumes from different hosts than was used for the first time. My steps:

1. Create volume on server1
docker volume create -d longhorn vol1
2. Use volume on server2
docker run -it --volume-driver longhorn -v vol1:/vol1 ubuntu bash
so far no problem, stop ubuntu test container and then
3. Try to use volume on server3
docker run -it --volume-driver longhorn -v vol1:/vol1 ubuntu bash
```
docker: Error response from daemon: error while mounting volume \
'/var/lib/rancher/volumes/longhorn/vol1': VolumeDriver.Mount: unable to attach volume: \
failed to start the controller for volume 'vol1': \
Fail to create controller for vol1: fail to process schedule request: failed to process schedule: \
fail to wait for api endpoint at \
http://10.0.0.14:9501/v1: timeout waiting for http://10.0.0.14:9501/v1.
```

### longhorn-manager log

```
ERRO[0739] Attempting to Write an unknown type:
ERRO[0770] fail to start controller vol2-controller of vol2, cleaning up: fail to wait for api endpoint at http://10.0.0.17:9501/v1: timeout waiting for http://10.0.0.17:9501/v1
WARN[0770] HTTP handling error unable to attach volume: failed to start the controller for volume 'vol2': Fail to create controller for vol2: fail to process schedule request: failed to process schedule: fail to wait for api endpoint at http://10.0.0.17:9501/v1: timeout waiting for http://10.0.0.17:9501/v1
ERRO[0770] Error in request: unable to attach volume: failed to start the controller for volume 'vol2': Fail to create controller for vol2: fail to process schedule request: failed to process schedule: fail to wait for api endpoint at http://10.0.0.17:9501/v1: timeout waiting for http://10.0.0.17:9501/v1
```

**Comment by yasker** [comment]
Can you check the log for longhorn-engine instances? It sounds like Longhorn controller failed to start. When longhorn-manager is waiting for the controller to be up, you should able to see one longhorn-engine instance running `controller`, then you can follow the log of them.

**Comment by mhemrg** [comment]
same problem.

**Comment by SacDin** [comment]
Same problem. If anyone is willing to help on this, I can provide extensive information including logs.

**Comment by yasker** [comment]
Close this issue due to obsolete. We've moved to Kubernetes now.

Feel free to reopen if it happens again.
