### ISSUE TITLE
doc: RancherOS support

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#154]
We need to document how to enable Longhorn RancherOS support in v0.3.

PR should be made to https://github.com/rancher/longhorn/tree/v0.3-rc

**Comment by yasker** [comment]
Delay it to v0.4 due to CSI is not working.

**Comment by yasker** [comment]
Fixed by https://github.com/rancher/longhorn/commit/14b194d8265b5b4e8414a1274a6b6f014ebf5011

**Comment by Remigius2011** [comment]
hi,

how aboout running longhorn on a rancher provisioned cluster on prem (in my case on vSphere)? it would be nice to have a section describing how to prepare the nodes for longhorn as part of provisioning, preferrable using a `cloud-init.yaml`. How about using the available open-iscsi system service of rancher OS (in the dscription open-iscsi is installed manually using the ubuntu shell which has several drawbacks)?
