### ISSUE TITLE
test: add build `base image` test image in the longhorn-tests

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#155]
https://github.com/rancher/longhorn-tests/tree/master/manager/test_containers

Also, Reduce the base image size to e.g. 32M instead of 4G. We will run full disk checksum.

**Comment by yasker** [comment]
Btw, make sure the size is different from the default test image size, so we can catch the error if something unexpected happened.

**Comment by LLParse** [comment]
https://github.com/rancher/longhorn-tests/pull/89

**Comment by yasker** [comment]
Done.
