### ISSUE TITLE
Hide the "Virtual Machine" stack  from hosts view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/longhorn#167]
Hide the "Virtual Machine" stack  from hosts view.

**Comment by cjellick** [comment]
Holding onto this one until I update the rancher/longhorn-catalog entry.

**Comment by sangeethah** [comment]
Tested with:
Server version - v1.1.0-storage-2
UI - v1.1.6

"Virtual Machine" stack is not shown from hosts view.
