### ISSUE TITLE
[Question] Is the longhorn catalog app usable ?

### ISSUE THREAD

**Issue by Angelinsky7** [rancher/longhorn#172]
Hi i would like to know if the catalog app (version 0.1.0) is really usable now.
I've seen that it's not updated... is it desired ?
May i not use it ?

Thanks for your answer

**Comment by yasker** [comment]
Don't use it for now. v0.3 is coming.

We're at v0.3-rc2 currently. See here for the latest RC. https://github.com/rancher/longhorn/tree/v0.3-rc

We will release the v0.3 next week. The first available format for deployment would be through yaml files at https://github.com/rancher/longhorn . We're going to update the catalog app after we released v0.3. We'd like to support upgrade, both through yaml file and using the catalog app. So if it's possible, it may take more time before we can release longhorn app v0.3 as a Rancher App.

**Comment by Angelinsky7** [comment]
@yasker thanks a lot for your answer... i'll wait for the v0.3 catalog release then (like that i could test the upgrade from 0.1 to 0.3 :-) on my test machine )
