### ISSUE TITLE
UI: Add a pop-up for `Create Backup` button in the `Volume Details` page

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#174]
Due to we cannot resolve https://github.com/rancher/longhorn/issues/143 in v0.3 release. We need a way to tell the user that the backup has started.

We can add a pop up for the users if they click on the `Create Backup` button, remind them `Creating Backup in progress. It would take a while, depends on the actual size of the volume and the network bandwidth. Please check <insert volume backup page URL> for the finished Backups`.

**Comment by yasker** [comment]
Also, add an instruction somewhere near `Take Snapshot` (below?), saying `you can create a backup from snapshot`.

**Comment by LLParse** [comment]
https://github.com/rancher/longhorn-ui/pull/64

**Comment by yasker** [comment]
Fixed.
