### ISSUE TITLE
doc: Document for base image feature

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#175]
https://github.com/rancher/longhorn/issues/135

Need to cover how to create a RancherVM Base Image (maybe we should just update RancherVM's document and link it here, or write a short version for Longhorn). And how to use them with Longhorn.

**Comment by LLParse** [comment]
https://github.com/rancher/longhorn/pull/194
https://github.com/rancher/longhorn-manager/pull/162
https://github.com/rancher/longhorn/pull/207

**Comment by yasker** [comment]
Done.
