### ISSUE TITLE
Update conflict happened much more frequently in volume/node controller

### ISSUE THREAD

**Issue by JacieChao** [rancher/longhorn#183]
When doing nothing, there's tons of conflicts happening in volume/node controller.

**Comment by JacieChao** [comment]
In `ResourceEventHandler`, `OnUpdate` is also called when a re-list happens, and it will get called even if nothing changed. When this happened, volume/node controller will update objects even there's nothing changed, which will due to an update conflict frequently.

**Comment by yasker** [comment]
Close this for now. It's better after the refactor.
