### ISSUE TITLE
Add event log to the dashboard

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#186]
We need event log in the dashboard.

We will need to add an API in the manager, retrieve related event log. Then the UI can get it and display in the dashboard.

Also, we need to add event log for the notable event of nodes/disks etc.

**Comment by yasker** [comment]
@ly5156 What's the default sorting order? I think it makes sense to sort descended by `last seen, so the latest happened should on the top.

Also, don't need to sort by `Message`.

**Comment by ly5156** [comment]
@yasker By default there is no sorting of the data
 For a while, I will remove the sort of message, and sort by the field of last seen default.

**Comment by yasker** [comment]
Fixed.
