### ISSUE TITLE
Project milestone

### ISSUE THREAD

**Issue by darron1217** [rancher/longhorn#19]
This project seems very interesting XD

It would be nicer if this project has public milestone for alpha/beta release :)
Maybe that can give courage to our dev team to give it a try 

Anyway, thanks for this powerful project

**Comment by yasker** [comment]
Thanks @darron1217 , we're going to announce something very soon. :)

**Comment by yasker** [comment]
Hi @darron1217 

We've just released v0.2. And we have a roadmap now describing the next few releases. You can take a look at https://github.com/rancher/longhorn/wiki/Roadmap
