### ISSUE TITLE
CSI cannot work in RancherOS

### ISSUE THREAD

**Issue by niusmallnan** [rancher/longhorn#198]
Using CSI on RancherOS, kubelet does not call NodePublish. I can get these logs:
```
# Kubernetes version v1.10.x

I0809 08:00:16.854453    3149 volume_host.go:219] using default mounter/exec for kubernetes.io/csi
I0809 08:00:16.854509    3149 csi_client.go:225] kubernetes.io/csi: calling NodeGetCapabilities rpc
I0809 08:00:16.854553    3149 csi_client.go:261] kubernetes.io/csi: creating new gRPC connection for [unix:///var/lib/kubelet/plugins/io.rancher.longhorn/csi.sock]
E0809 08:00:16.854744    3149 csi_attacher.go:282] kubernetes.io/csi: attacher.MountDevice failed to check STAGE_UNSTAGE_VOLUME: rpc error: code = Unavailable desc = grpc: the connection is unavailable
```
Kubelet can't find csi sock file, so can't call NodePublish.

Usually, we use RKE(v0.18) to deploy k8s on RancherOS, RKE will change the bind-mounts of the kubelet container. The `root-dir` will be changed to `/opt/rke/var/lib/kubelet`.
```
# RancherOS 
/opt/rke/var/lib/kubelet:/opt/rke/var/lib/kubelet
```
This means that the /var/lib/kubelet directory in the kubelet container is meaningless.
We need to put the csi sock file to host directory `/opt/rke/var/lib/kubelet`,  then the kubelet can read it. We have a lot of ways to achieve this, this is not worried.

Unfortunately, the csi sock path of kubelet in v1.10 is written dead:
https://github.com/kubernetes/kubernetes/blob/release-1.10/pkg/volume/csi/csi_plugin.go#L37-L44
```
	// TODO (vladimirvivien) implement a more dynamic way to discover
	// the unix domain socket path for each installed csi driver.
	// TODO (vladimirvivien) would be nice to name socket with a .sock extension
	// for consistency.
	csiAddrTemplate = "/var/lib/kubelet/plugins/%v/csi.sock"
	csiTimeout      = 15 * time.Second
	volNameSep      = "^"
	volDataFileName = "vol_data.json"
```
https://github.com/kubernetes/kubernetes/blob/release-1.10/pkg/volume/csi/csi_client.go#L254-L262
```
func newGrpcConn(driverName string) (*grpc.ClientConn, error) {
	if driverName == "" {
		return nil, fmt.Errorf("driver name is empty")
	}

	network := "unix"
	addr := fmt.Sprintf(csiAddrTemplate, driverName)
	glog.V(4).Infof(log("creating new gRPC connection for [%s://%s]", network, addr))
```
So, no matter what, kubelet can only read this fixed csi sock path.

This should be the root cause of the problem.

**Comment by niusmallnan** [comment]
The CSI team seems to be aware of this csi sock issue, so they introduced the `Kubelet Plugin Watcher` in k8s v1.11. It can pass the csi sock path to kubelet.
https://kubernetes-csi.github.io/docs/print.html#kubelet-plugin-watcher
If we use this mechanism, what we need to do is:
1. upgrade csi to v0.3
2. update our csi deployment spec, should add a path prefix `/opt/rke`.
3. consider compatibility with k8s v1.10


For csi v0.2 and k8s v1.10, there is a workaround.
Add the `extra_binds` to kubelet in RKE cluster.yml:
```
  kubelet:
    extra_args:
      feature-gates: MountPropagation=true
      volume-plugin-dir: /opt/rke/var/lib/kubelet/volumeplugins
    extra_binds:
      - "/var/lib/kubelet:/var/lib/kubelet" # here
```
Update the `pods-mount-dir` to `/opt/rke/var/lib/kubelet/pods` in csi deployment spec:
1. https://github.com/rancher/longhorn-manager/blob/master/csi/deployment.go#L207-L211
2. https://github.com/rancher/longhorn-manager/blob/master/csi/deployment.go#L239-L244

**Comment by yasker** [comment]
Do we really need to persist `/var/lib/kubelet/plugins`? I think the Unix domain socket can be recreated upon node reboot.

If that's the case, we can do something similar to https://github.com/rancher/rke/pull/800 (discussion in https://github.com/rancher/rke/pull/709 ), which would bind mounts `/var/lib/kubelet/plugins:/var/lib/kubelet/plugins`.

BTW, RKE after this commit, you don't need to do `volume-plugin-dir: /opt/rke/var/lib/kubelet/volumeplugins` to enable Flexvolume driver. Things should work out of the box, with directory `/var/lib/kubelet/volumeplugins/`.

RancherOS etc has various non-standard location things, e.g. https://github.com/rancher/rke/issues/662 , which causes issues for the application. The general way we want is to make RancherOS and RKE works without extra config if possible.

**Comment by yasker** [comment]
Seems we need `/var/lib/kubelet/pods` to be bind mounted as well.

**Comment by yasker** [comment]
@niusmallnan Shouldn't the sock file to be automatically recreated upon the node reboot since it will be created when the container started? Then why should we persist the directory for rebooting?

**Comment by niusmallnan** [comment]
@yasker The sock file can be automatically recreated. https://github.com/container-storage-interface/spec/blob/v0.2.0/spec.md#connectivity

We need to ensure that the kubelet and csi-attacher and csi-provisioner read the same sock file.

**Comment by yasker** [comment]
@niusmallnan There should be only one active sock file there by this name. If the other connected to a closed sock file they will error out.

And we should try best to clean up the sock file when the container exits, e.g. by catching the signal.

**Comment by yasker** [comment]
Fixed by https://github.com/rancher/longhorn-manager/pull/242
