### ISSUE TITLE
deleting snapshot hangs forever

### ISSUE THREAD

**Issue by cjellick** [rancher/longhorn#211]
Steps to reproduce
1. create volume
2. create snap A
3. create snap B
4. delete snap A

sfold seems to hang or take forever. im deleting this snap on an empty volume.
see this in the sync-agent logs:
```
time="2016-08-01T21:49:12Z" level=info msg="Running /proc/self/exe [sfold volume-snap-63a9c04a-02d7-43dd-a317-aa65fe783e28.img volume-snap-a905e1c6-c817-4668-bf49-f272d8e1a3fd.img]"
```

**Comment by yasker** [comment]
Need longhorn integration test for the case.
