### ISSUE TITLE
Scheduler scheduled replica to the same node

### ISSUE THREAD

**Issue by JacieChao** [rancher/longhorn#217]
This issue is due to disk status update delay. One of the node is not available for scheduling, the other two node status didn't update immediately after scheduling replica, it will cause scheduler schedule 2 big replica on the same node, which is impossible in normal situation.

**Comment by yasker** [comment]
This shouldn't be possible since all replicas scheduling are in an one thread process. And update to the rs inside controller should prevent this.

**Comment by JacieChao** [comment]
@yasker Yeah, but scheduler depend on disk status which is updated by node controller. If we schedule replica before node controller update disk status, this situation will occur.

**Comment by yasker** [comment]
1. Let node controller watch replicas,

2. Add a `ScheduledReplica map[string]int64` to the `Disk.Status`.

3. Change the scheduling logic that each replica should wait for all the other scheduled replicas (`nodeID != "") of the same volume been accounted for before continuing scheduling. Just search for the disk status for the node the previous replica has been scheduled and see if it's name is there.

**Comment by yasker** [comment]
Fixed.
