### ISSUE TITLE
RancherOS longhorn service?

### ISSUE THREAD

**Issue by pwFoo** [rancher/longhorn#219]
Instead of use longhorn with Rancher (Server) it would be nice to have a longhorn RancherOS service.

Is it possible or a howto (manually install @RancherOS) available?

**Comment by pwFoo** [comment]
Alternative RancherOS make instructions / binaries would be great!

**Comment by yasker** [comment]
@pwFoo, 

We haven't ready to push Longhorn yet, it's still in heavy development. We will put more information when we are more ready.
