### ISSUE TITLE
Shared longhorn volume?

### ISSUE THREAD

**Issue by pwFoo** [rancher/longhorn#221]
I tried to run two containers at different hosts with the same longhorn volume, but second container failed to start / create.

```
Error (409 Client Error: Conflict ("Unable to remove volume, volume still in use: remove longhorn1: volume is in use - [ab7e7921fc18f72ea312a60b543b593c75364e9cdcfa8e01e30e5e604c4a6349]"))
```

So longhorn volume couldn't mounted to different containers / host at the same time?

**Comment by pwFoo** [comment]
I'm not sure, could also be a bug with my second host. Volume isn't created here, also if I stop the first instance at the other host...

So my question.
Is it possible to mount the longhorn volume to more than one container running on differend hosts?

**Comment by yasker** [comment]
No... Longhorn is not designed to be shared across different host. You can think it as EBS instead of NFS.

**Comment by pwFoo** [comment]
So longhorn also isn't a multihost / shared mount volume solution. :( 
Any suggestion what to use?

**Comment by yasker** [comment]
Currently, we suggest using NFS/EFS with Convoy. You can also use convoy-glusterfs(we're adding back the support for that), but we won't able to support the setup of GlusterFS ourselves since there are too many variants of setup.

**Comment by pwFoo** [comment]
I'll give https://github.com/contiv/volplugin a and also Convoy NFS a try, but volume size limit like possible with longhorn and ceph could be needed in some needs.

So longhorn is multihost and move the storage / volume from host to host, but can't mounted to multiple containers? Or just not host comprehensive?
Would it be possible in the future to add this feature to longhorn?

**Comment by yasker** [comment]
Still, Longhorn is more like EBS rather than NFS. You have one volume, which can be represented as a block device and attached to a container. It can be moved from host to host, but not shareable, unless you put another layer on top of Longhorn. 

We have no plan to add shareable feature to longhorn, it's a different issue from what longhorn suppose to address.
