### ISSUE TITLE
Support for Docker 18.03.1-ce

### ISSUE THREAD

**Issue by dnoland1** [rancher/longhorn#222]
Get the following error when trying to install Longhorn on Ubuntu with Docker 18.03.1-ce. Can workaround by downgrading, but would prefer to use a new version of Docker.

```
FATA[0000] Unsupported Docker version found [18.03.1-ce], supported versions are [1.11.x 1.12.x 1.13.x 17.03.x]
```

**Comment by JacieChao** [comment]
I don't think it's a longhorn issue, looks like you are using rke to deploy kubernetes cluster. If you want to use Docker 18.03.1-ce, you should disable rke docker version check in `cluster.yml`
```
# If set to true, RKE will not fail when unsupported Docker version are found
ignore_docker_version: false
```

**Comment by dnoland1** [comment]
Sorry, yes, was reporting this on behalf of someone who was deploying both RKE and Longhorn. Message was indeed from RKE.
