### ISSUE TITLE
Deal with Kubernetes node delete

### ISSUE THREAD

**Issue by JacieChao** [rancher/longhorn#223]
Here's some situation we should deal with when user remove physical node from kuberentes cluster.
1. When user remove physical node from cluster, we could let user delete node from UI (just remove `down` node without longhorn-manager running on it)
2. If volumes has attached to the node before remove it, volume couldn't be rebuilt.
3. Replicas running on remove node should be able to schedule to other nodes.

**Comment by yasker** [comment]
Also, need to update manual test plan in https://github.com/rancher/longhorn-tests/wiki/Manual-Test-Plan, since we cannot test it automatically right now.

**Comment by yasker** [comment]
Done.

**Comment by yasker** [comment]
https://github.com/rancher/longhorn-manager/pull/184
