### ISSUE TITLE
Failover scenario

### ISSUE THREAD

**Issue by qdrop17** [rancher/longhorn#224]
Hi everyone.

One of my main reasons for checking out Rancher 2.0 and Longhorn is it's capability of data replication / high availability.

I successfully deployed Rancher 2.0 and Longhorn (on Ubuntu 16.04 machines). On top of that I manage to properly provision services - including Longhorn volumes (with 2 replicas).

My setup consists of 3 servers:

- rancher-server (Rancher 2.0 Server)
- rancher-node01 (Rancher Agent including all roles)
- rancher-node02 (Rancher Agent including all roles)

I expected the system to work as follows: If I kill the node with the running application pod, Rancher would relaunch this pod an the remaining node.

Unfortunately, this is not the case. It just fails and says "Deployment does not have minimum availability.".

I'm not even able to move a pod to another node (while persisting it's data within the longhorn volumes). Same error.

What steps and thoughts do I have to follow to enable the mentioned scenarios?

Thank you very much for helping.

**Comment by yasker** [comment]
@qdrop17 Can you make a more specific description of what you've done on try to move the volume?

For example, "Deployment does not have minimum availability." is reported for Longhorn or the service you want to deploy?

You're using deployment or statefulset or other kinds of workload?

**Comment by qdrop17** [comment]
Hello @yasker. Thanks for replying.

Well from my understanding, it should not be necessary to move to volume as longhorn started a volume container on each host.

I simply deployed a default configured elasticsearch container / pod using the Rancher 2.0 UI. With just one instance. This got deployed on a node automatically. Longhorn also provisioned the volumes properly and mounted them into the container / pod.

I then disconnected one node from the network entirely. I thought that Kubernetes will detect that and spins up the container / pod on another host (where the longhorn volume is also present obviously).

Is this scneario even working from a technical point of view or am I missing some important configuration?

**Comment by yasker** [comment]
@qdrop17 Can you give a look at our upcoming v0.4 document? It describes the behavior of Kubernetes and Longhorn while dealing with node failure.

https://github.com/rancher/longhorn/blob/v0.4/docs/node-failure.md

**Comment by yasker** [comment]
The upcoming Longhorn v0.4.0 release is able to handle node failure better, but the user would need to read https://github.com/rancher/longhorn/blob/v0.4/docs/node-failure.md to know what's to expect and what to do during node failure.

Close this issue for now. Feel free to reopen if you have more questions.
