### ISSUE TITLE
Volume created date showing as "Invalid date" in UI

### ISSUE THREAD

**Issue by dnoland1** [rancher/longhorn#227]
Create a three node cluster using RKE and deployed Longhorn. Create the sample nginx pod with PVC using https://raw.githubusercontent.com/rancher/longhorn/v0.3-rc/examples/pvc.yaml. When browsing UI, seeing "Invalid date" for the volume Created field:
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/468462/44253175-86590900-a1b3-11e8-864e-8b21a2dc8865.png">
Using Longhorn v0.3-rc4.

**Comment by yasker** [comment]
It's happened for non-chrome browsers. 

Should be fixed in https://github.com/rancher/longhorn-ui/pull/85 , and would be included in the next RC.
