### ISSUE TITLE
Docker Swarm support

### ISSUE THREAD

**Issue by mhemrg** [rancher/longhorn#23]
Hi,
Does Longhorn support Docker Swarm?

**Comment by yasker** [comment]
Not currently, we support Kubernetes only ATM

**Comment by riosolar** [comment]
Does Longhorn support Docker Swarm? in 2021?

**Comment by mhemrg** [comment]
Swarm Cluster Volume Support with CSI Plugins
https://github.com/moby/moby/issues/39624

**Comment by olljanat** [comment]
> Swarm Cluster Volume Support with CSI Plugins [moby/moby#39624](https://github.com/moby/moby/issues/39624)

That support was now released as part of Docker 23.0.0 **but** Longhorn is one of those CSI plugins which **cannot** be easily made working with that. More info on my repo https://github.com/olljanat/csi-plugins-for-docker-swarm
