### ISSUE TITLE
The replices can't be rescheduled when restart the cluster with CSI driver.

### ISSUE THREAD

**Issue by rootwuj** [rancher/longhorn#231]
**Environment:**

Using rke to deploy kubernetes v1.11.1
Longhorn version: v0.3-rc4

**Steps to Reproduce:**

1. Deploy longhorn with CSI driver
2. Create volume and attach to host
3. Power off and restart the cluster

**Results:**

1. The volume status is:Detached, the pod status is:Completed.
（The replices status is running when restart the cluster with Flexvolume driver. ）
2. The pod state is still Completed, when the volume is reattached

**Comment by yasker** [comment]
Related to https://github.com/rancher/longhorn/issues/66 .

Push to v0.3.1

**Comment by yasker** [comment]
Fixed with https://github.com/rancher/longhorn/issues/275
