### ISSUE TITLE
doc: Need to document on how to use block storage and the filesystem level cache

### ISSUE THREAD

**Issue by rootwuj** [rancher/longhorn#233]
**Environment:**
Using rke to deploy kubernetes v1.11.1
Longhorn version: v0.3-rc4

**Steps to Reproduce:**
1. Deploy longhorn with CSI driver
2. Backup volume (mount path has been written)
```
root@ip-172-31-17-105:~# kubectl exec -it volume-test sh
/ # cd data/
/data # ls
aa.yaml     lost+found  test
/data #
/data # cat aa.yaml
this is aa
/data # md5sum aa.yaml
2c808b4d0985eed9b4e34a17c1c26e91  aa.yaml
/data #
/data # cd test/
/data/test # md5sum bb.yaml
98d375a76b3dca56b240a849a451e832  bb.yaml
/data/test #
```

3. Restore backup to create volume
4. Create a pod using the volume created in the previous step

**Results:**

The file under the mount path has no content, MD5 value has been modified.
```
root@ip-172-31-17-105:~# kubectl exec -it volume-testrestore sh
/ # cd data/
/data # ls
aa.yaml     lost+found  test
/data # cat aa.yaml
/data #
/data # md5sum aa.yaml
68b329da9893e34099c7d8ad5cb9c940  aa.yaml
/data #
/data # cd test/
/data/test # md5sum bb.yaml
98d375a76b3dca56b240a849a451e832  bb.yaml
/data/test #

```
（I tried to use the flexvolume driver, the file MD5 value is consistent.）

**Comment by yasker** [comment]
@rootwuj Can you try to run `sync` before the backup? Otherwise, the content may not be written to the disk.

**Comment by yasker** [comment]
OK, we need to document the expected behavior on block storage for the user.

**Comment by yasker** [comment]
Done.
