### ISSUE TITLE
UI:salvage page style needs to be adjusted

### ISSUE THREAD

**Issue by rootwuj** [rancher/longhorn#234]
**Environment:**
Longhorn version: v0.3-rc4

 **Steps to Reproduce:**
When the volume health status is Faulted, click salvage to enter the salvage page.

**Results:**
1. Page style needs to be adjusted
2. Don't remember the number of replicas you last selected

**Comment by yasker** [comment]
@rootwuj Let me know if https://github.com/rancher/longhorn-ui/pull/86 fixed it.

**Comment by rootwuj** [comment]
@yasker  https://github.com/rancher/longhorn-ui/pull/86   fixed
