### ISSUE TITLE
UI: The volume detail box resized when click actions

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#235]
To reproduce:
1. Choose one volume
2. In the volume detail page, click attach/detach

Notice the left box is higher than the right one.

<img width="1846" alt="screen shot 2018-08-20 at 2 14 26 pm" src="https://user-images.githubusercontent.com/3344618/44367044-695a5980-a483-11e8-821f-82f1e24c8fd7.png">

**Comment by ly5156** [comment]
@yasker

**Comment by yasker** [comment]
Fixed.
