### ISSUE TITLE
tgt: Failure in reverting snapshot: Socket server connection closed

### ISSUE THREAD

**Issue by sheng-liang** [rancher/longhorn#235]
a054a12d6d37f91b3de2a7ec4e02f024ba1c1e727b49955738b7512b08b87730
b354ad670945ad3504897f8d63873c5ca0c44b2c504a970baf1469ff53039f0c
5559fcd416b6e51767b8970f32d4a51d6c11811dfba65734ebd14739ac67f651
a054a12d6d37f91b3de2a7ec4e02f024ba1c1e727b49955738b7512b08b87730
2016-11-04 13:13:30.986543: iteration = 5 thread = 4 replica1 = 66b956e6e5f81733cc55fdbc810c5c6b3562fac33a187e044fb1700f62ad2c10
2016-11-04 13:13:31.608913: iteration = 5 thread = 4 replica2 = e8a0ed1cb70b15263ebae35bde9dca57059954482350317fc0c2ed5d771a7166
2016-11-04 13:13:50.727669: iteration = 4 thread = 15 : FAIL TO WAIT FOR DEVICE READY, docker logs:
time="2016-11-04T20:11:08Z" level=info msg="Starting with replicas [\"tcp://172.18.1.15:9502\" \"tcp://172.18.2.15:9502\"]" 
time="2016-11-04T20:11:08Z" level=info msg="Connecting to remote: 172.18.1.15:9502" 
time="2016-11-04T20:11:08Z" level=info msg="Opening: 172.18.1.15:9502" 
time="2016-11-04T20:11:08Z" level=info msg="Adding backend: tcp://172.18.1.15:9502" 
time="2016-11-04T20:11:08Z" level=info msg="Connecting to remote: 172.18.2.15:9502" 
time="2016-11-04T20:11:08Z" level=info msg="Opening: 172.18.2.15:9502" 
time="2016-11-04T20:11:08Z" level=info msg="Adding backend: tcp://172.18.2.15:9502" 
time="2016-11-04T20:11:09Z" level=info msg="SCSI device /dev/sdd created" 
time="2016-11-04T20:11:09Z" level=info msg="Creating device /dev/longhorn/vol15 8:48" 
time="2016-11-04T20:11:09Z" level=info msg="Device /dev/longhorn/vol15 is ready" 
time="2016-11-04T20:11:09Z" level=info msg="Listening on localhost:9501" 
time="2016-11-04T20:12:13Z" level=info msg="Snapshot: 172.18.1.15:9502 03b50720-dabf-4548-bb16-5437f7fae7e0" 
time="2016-11-04T20:12:13Z" level=info msg="Snapshot: 172.18.2.15:9502 03b50720-dabf-4548-bb16-5437f7fae7e0" 
127.0.0.1 - - [04/Nov/2016:20:12:13 +0000] "POST /v1/volumes/dm9sMTU=?action=snapshot HTTP/1.1" 200 180
time="2016-11-04T20:13:29Z" level=info msg="Shutdown SCSI device for 172.18.0.6:iqn.2014-09.com.rancher:vol15" 
time="2016-11-04T20:13:30Z" level=info msg="Shutdown SCSI target iqn.2014-09.com.rancher:vol15" 
time="2016-11-04T20:13:30Z" level=info msg="Reverting to snapshot volume-snap-03b50720-dabf-4548-bb16-5437f7fae7e0.img on tcp://172.18.1.15:9502" 
time="2016-11-04T20:13:30Z" level=info msg="Reverting to snapshot volume-snap-03b50720-dabf-4548-bb16-5437f7fae7e0.img on tcp://172.18.2.15:9502" 
time="2016-11-04T20:13:30Z" level=warning msg="Socket server connection closed" 
panic: exit status 242

goroutine 25 [running]:
panic(0xa0bde0, 0xc420226740)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi.startDaemon(0xc42022a078, 0x0)
	/go/src/github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi/target.go:193 +0xfd
created by github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi.StartDaemon
	/go/src/github.com/rancher/longhorn/vendor/github.com/yasker/go-iscsi-helper/iscsi/target.go:163 +0x87
Process Process-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "teardown-test.py", line 162, in run_test
    check_data(thread, pattern1)
  File "teardown-test.py", line 76, in check_data
    data = readat_direct("/dev/longhorn/vol" + str(i), page * PAGE_SIZE, PAGE_SIZE)
  File "teardown-test.py", line 41, in readat_direct
    f = os.open(dev, os.O_DIRECT | os.O_RDONLY)
OSError: [Errno 2] No such file or directory: '/dev/longhorn/vol15'
2016-11-04 13:13:53.128692: iteration = 4 thread = 13 : Device ready after 1.859 seconds
2016-11-04 13:13:53.128761: iteration = 4 thread = 13 controller = d9729cbb9931694d4646d6242474b604e273d870beae564af53046dbf948f84d
2016-11-04 13:13:54.882861: iteration = 5 thread = 2 : Device ready after 1.031 seconds
2016-11-04 13:13:54.882959: iteration = 5 thread = 2 controller = ffdaa11d744b2d47c9aeabccbbde3f4dd626c4f920ca02457804ca1918bb697f
2e731833395cdb67b4666ecd2932f8426d4c44694ad8d8259e23b47170a8ed05

**Comment by sheng-liang** [comment]
sheng@ubuntu:~$ cat var/log/tgtd.log
tgtd: iser_ib_init(3431) Failed to initialize RDMA; load kernel modules?
tgtd: work_timer_start(146) use timer_fd based scheduler
tgtd: bs_init(387) use signalfd notification
tgtd: device_mgmt(246) sz:72 params:path=/var/run/longhorn-vol15.sock,bstype=longhorn,bsopts=size=134217728
tgtd: bs_thread_open(409) 16
tgtd: bs_longhorn_request(101) cmd->scb[0]: 35
tgtd: device_mgmt(246) sz:72 params:path=/var/run/longhorn-vol15.sock,bstype=longhorn,bsopts=size=134217728
tgtd: bs_thread_open(409) 16
connect error: No such file or directory

**Comment by yasker** [comment]
Fixed in https://github.com/yasker/longhorn/commit/72089c370f90fbc9ff6822a2ce3190aabf4ca63d
