### ISSUE TITLE
UI: Volume detail page salvage button cannot be clicked

### ISSUE THREAD

**Issue by rootwuj** [rancher/longhorn#238]
**To reproduce:**
1. The volume health status is faulted.
2. Go to the volume details page and click the salvage button.

**Results:**
The salvage button no click event.

**Comment by rootwuj** [comment]
@ly5156  I can click the salvage button to go to the details page. But the details page content and the list page are inconsistent.

The list page:
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/42061003/44384523-11892480-a54f-11e8-900b-ab212943dd48.png">


The details page :
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/42061003/44384484-ebfc1b00-a54e-11e8-899a-09020da84bf0.png">

**Comment by rootwuj** [comment]
Fixed.

**Comment by yasker** [comment]
@rootwuj Just a reminder that don't mark the issue as fixed until the PR has been merged.
