### ISSUE TITLE
Snapshot and revert should handle a replica go bad during the operation

### ISSUE THREAD

**Issue by sheng-liang** [rancher/longhorn#243]
Snapshot and revert operations both assume all replicas are good. It should handle the situation a replica goes bad during the operation. As long as there's one good replica, the operation should succeed. Otherwise it is very difficult for the user to check for errors and recover.

If we are making snapshot and revert resilient to replica errors during the operation, we might as well make them work if there are bad replicas before the operation starts. This makes the whole operation a lot easier to use.

**Comment by yasker** [comment]
Snapshot has it all fixed at: https://github.com/rancher/longhorn/commit/e85cfa5cbdceb01260b544a44c6bb6bde5b9658b

Revert should be fixed at: https://github.com/rancher/longhorn/commit/1557011b05730942260550fee9afa0b7590ae61e but we need test case for it.
