### ISSUE TITLE
Manual test upgrading from v0.1/v0.2 to v0.3 following the instruction

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#244]
@rootwuj

Instructions updated at:

https://github.com/rancher/longhorn/blob/v0.3-rc/docs/upgrade.md#upgrade

Some upgrade test cases at:

https://github.com/rancher/longhorn-tests/wiki/Manual-Test-Plan#upgrade-test

For charts, use https://github.com/LLParse/charts-rancher/tree/longhorn-v0.3

**Comment by rootwuj** [comment]
I manually tested to upgrade from v0.1/v0.2 to v0.3.

**Testing process:**

1. Installed with Longhorn App v0.1 in Rancher 2.0.7, then upgrade to Longhorn App 0.3-rc4.
2. Deploy Longhorn 0.2 according to the official Longhorn deployment instructions, then upgrade to Longhorn 0.3-rc4

**Result:**
Manual test case execution is passed:

1. The attached volume is correct.
2. Manager cannot do anything about the attached volumes except detaching it.
3. Manager cannot live-upgrade the attached volumes if the version is incompatible.
4. Manager cannot reattach an existing volume, until the user has upgraded the engine image to a manager supported version.
5. After offline or online (live) engine upgrde, the contents of the volumes are valid.
6. For the volume never been attached in the old version, it's attachable after upgrade.

**Comment by yasker** [comment]
@rootwuj What workloads you've included in your test?

**Comment by rootwuj** [comment]
The workloads I tested include: deployment/stateful set/pod

**Comment by yasker** [comment]
Sounds good to me.
