### ISSUE TITLE
UI: Node status is down, editing should not be allowed

### ISSUE THREAD

**Issue by rootwuj** [rancher/longhorn#249]
**Environment:**
Using rke to deploy kubernetes v1.11.1
Longhorn version: v0.3-rc5

**Steps to Reproduce:**
Edit the node with the status down.

**Results:**
Report 502 error.

**Comment by yasker** [comment]
Related to https://github.com/rancher/longhorn/issues/223

**Comment by rootwuj** [comment]
This issue has been fixed.
