### ISSUE TITLE
Read base image from QCOW in replica

### ISSUE THREAD

**Issue by cjellick** [rancher/longhorn#25]
High level goal: 
To read the base image qcow for a VM directly from longhorn (by including it in the replica) instead of relying on it to already be in the image. This will let us pass the block device for the root disk directly to KVM.
Users will still creates an image based off of rancher-vm, ie rancher/ubuntu-vm and put the QCOW in that image, but we will then use that image to launch the replicas (in addition to using it to launch the vm itself).

- In cattle, in our pre-vm-create logic (where we already add vm-specific configuration) do the following:
  - add a driver-opt for the root volume for the image, ie: `—driver-opt image=rancher/ubuntu-vm`
  - add a driver-opt for the root volume that tells the driver not to format or mount the volume, ie `—driver-opt dont-format=true`
  - add a device to the container that will the actual longhorn block device on the host, ie `docker run … --device /dev/longhorn/volume-foo-uuid:/dev/vmroot`

- In the docker longhorn driver, adjust logic to account for the new parameters provided by cattle
  - If dont-format driver options is present, don’t format or  mount the device
  - If the image driver option is present, we will use a different rancher-compose file to create the longhorn volume stack. The new stack will basically use two containers: one based off of the user specified image and one that just contains the longhorn binary. The binary container’s volumes will be mounted into the qcow container and the container will be start with an entrypoint/command to start the replica, ie `docker run —entrypoint longhorn rancher/vm-ubuntu replica /dir/to/qcow. Here’s a rough approximation of the new compose file:
```
replica:
  image: rancher/vm-ubuntu
  volumes_from: binary
  entrypoint: /cmd/longhorn
  command: replica $LONGHORN_DIRECTORY
binary:
  image: longhorn
  volumes:
    - /cmd
  labels:
    io.rancher.start_once: true
```
 
- In rancher-vm, if `/dev/vmroot` is present, pass it directly to kvm as the root device, If it isn’t present, use the currently logic of using the qcow in the image and creating a snapshot (this will let rancher-vm work without rancher+longhorn running)

Plan of attack is for me to get all the plumbing working without waiting for the actual read-from-qcow logic in longhorn. Should be able to get this all plumbed without that bit.

**Comment by sangeethah** [comment]
Rancher Server version - v1.1.0-dev2-rc1
Longhorn controller image - cjellick/longhorn:dev6

Deployed VM with ROOT and DATA volumes in longhorn.
Replica containers for ROOT volumes are started with VM image.
Replica containers for DATA volumes are started with longhorn image.

Able to read and write successfully into ROOT and DATA volumes.

Migrate VM to a different host ( deactivate the host on which VM is running and delete the VM).

After VM is migrated, we are able to read all the current contents of ROOT and DATA disks and also able to write to ROOT and DATA volumes.
