### ISSUE TITLE
Longhorn running, hosts activated, volume attached but pods timing out waiting for volume

### ISSUE THREAD

**Issue by SacDin** [rancher/longhorn#25]
Volume shows as "Healthy" in longhorn-ui but pod is timing out waiting for volume. The longhorn is deployed in separate namespace than requesting pod. I hope that is not the issue here.

Logs from longhorn-manager : 
```
DEBU[1477] volume myservice-db state is healthy
DEBU[1477] volume myservice-db desire state is healthy
DEBU[1477] volume myservice-db state is healthy
DEBU[1482] volume myservice-db state is healthy
DEBU[1482] volume myservice-db desire state is healthy
DEBU[1482] volume myservice-db state is healthy
```

Thanks in anticipation.

**Comment by yasker** [comment]
What's the output of `kubectl describe <pod>`? Has the volume been attached manually or attached by the flex volume driver?

Also, make sure the driver installed in the correct directory. https://github.com/rancher/longhorn/blob/master/deploy/example.yaml#L207

If it's bare metal, I bet it's should be at `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/`

**Comment by SacDin** [comment]
Hi, changing the driver path fixed the problem while running longhorn in shared namespace with pod. It worked great and pod was up !

 However, when I tried to move longhorn in separate namespace, getting following error in longhorn-manager : 
```
adacts@druid2:~/temp$  kubectl logs longhorn-manager-qc6hm -f -n storage
INFO[0000] Detected IP is 10.32.0.21
INFO[0000] Kubernetes orchestrator is ready
INFO[0002] Listening on 10.32.0.21:9500
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x110aec9]

goroutine 134 [running]:
github.com/rancher/longhorn-manager/manager.(*VolumeManager).VolumeCreateBySpec(0xc42024b1f0, 0xc420200f20, 0x17, 0x0, 0x0)
	/go/src/github.com/rancher/longhorn-manager/manager/manager.go:406 +0x529
created by github.com/rancher/longhorn-manager/manager.(*VolumeManager).startProcessing
	/go/src/github.com/rancher/longhorn-manager/manager/process.go:38 +0x3c7
```

**Comment by yasker** [comment]
@SacDin Thank for confirming that it's volume driver plugin.

I've just pushed a new update which will deploy Longhorn system in the `longhorn-system` namespace. Can you give it a try?

In the meanwhile, I'd like to close this issue since the original question has been addressed.

If you met more issues when trying the new version, feel free to file a new issue.

**Comment by SacDin** [comment]
Hi @yasker 
Thank you for the prompt update. I will try it out shortly and let you know.
Regards.
