### ISSUE TITLE
Ip address is not assigned to Windows Vm.

### ISSUE THREAD

**Issue by sangeethah** [rancher/longhorn#27]
Server version - Build from master 
Ros version - v0.4.4 
Longhorn catalog template from - https://github.com/cjellick/longhorn-catalog ( image -cjellick/longhorn:dev2)

Steps to reproduce the problem:
Create a widows VM - (image - yasker/vm-windows7) which uses ROOT volumes from longhorn driver.

Once the VM boots up successfully , we are not able to ping 8.8.8.8 . There is no ip from managed network that is assigned to the VM.

<img width="773" alt="screen shot 2016-05-04 at 11 28 42 am" src="https://cloud.githubusercontent.com/assets/4266958/15025211/1120975a-11ed-11e6-8604-eba1220fdc41.png">

**Comment by yasker** [comment]
Fixed by https://github.com/rancher/vm/pull/75

**Comment by yasker** [comment]
Assign to @sangeethah to verify.

**Comment by sangeethah** [comment]
Tested with latest images - rancher/vm-ubuntu:14.04 and yasker/testimage:latest.
VM gets ip address successfully.
