### ISSUE TITLE
longhorn-csi-plugin in error on second node

### ISSUE THREAD

**Issue by marcteyssier** [rancher/longhorn#277]
I using Rancher 2.0.8 and 2 nodes with fresh installation (ubuntu 16.04).

When I enabled Longhorn 0.3 with default configuration. It's ok on the first but the csi_plugin is ko on the second.
I checked the kubernetes log and I have 
```
Error from server (InternalError): an error on the server ("{\"Code\":{\"Code\":\"ServerError\",\"Status\":500},\"Message\":\"NotFound 404: clusters.management.cattle.io \\\"c-fsxg7\\\" not found\",\"Cause\":null,\"FieldName\":\"\"}") has prevented the request from succeeding (get pods longhorn-csi-plugin-stk2q)
```

I tried with other driver (flexVolume), in another node order (before 2 and after 1), the second node is always in error.

**Comment by yasker** [comment]
The error is from Rancher. Can you check using `kubectl` directly to see if the deployment of Longhorn is OK with Kubernetes?

**Comment by marcteyssier** [comment]
Actually, I have a return on node 1 and not on the 2nd:
node 1

`{
    "actions": {},
    "id": "v1",
    "links": {
        "apiVersions": "http://longhorn-backend:9500/v1/apiversions",
        "attachInputs": "http://longhorn-backend:9500/v1/attachinputs",
        "backupInputs": "http://longhorn-backend:9500/v1/backupinputs",
        "backupVolumes": "http://longhorn-backend:9500/v1/backupvolumes",
        "backups": "http://longhorn-backend:9500/v1/backups",
        "controllers": "http://longhorn-backend:9500/v1/controllers",
        "diskConditions": "http://longhorn-backend:9500/v1/diskconditions",
        "diskInfos": "http://longhorn-backend:9500/v1/diskinfos",
        "diskUpdateInputs": "http://longhorn-backend:9500/v1/diskupdateinputs",
        "diskUpdates": "http://longhorn-backend:9500/v1/diskupdates",
        "engineImages": "http://longhorn-backend:9500/v1/engineimages",
        "engineUpgradeInputs": "http://longhorn-backend:9500/v1/engineupgradeinputs",
        "errors": "http://longhorn-backend:9500/v1/errors",
        "events": "http://longhorn-backend:9500/v1/events",
        "nodeConditions": "http://longhorn-backend:9500/v1/nodeconditions",
        "nodeInputs": "http://longhorn-backend:9500/v1/nodeinputs",
        "nodes": "http://longhorn-backend:9500/v1/nodes",
        "recurringInputs": "http://longhorn-backend:9500/v1/recurringinputs",
        "recurringJobs": "http://longhorn-backend:9500/v1/recurringjobs",
        "replicaRemoveInputs": "http://longhorn-backend:9500/v1/replicaremoveinputs",
        "replicas": "http://longhorn-backend:9500/v1/replicas",
        "salvageInputs": "http://longhorn-backend:9500/v1/salvageinputs",
        "schemas": "http://longhorn-backend:9500/v1/schemas",
        "self": "http://longhorn-backend:9500/v1/apiversions/v1",
        "settingDefinitions": "http://longhorn-backend:9500/v1/settingdefinitions",
        "settings": "http://longhorn-backend:9500/v1/settings",
        "snapshotInputs": "http://longhorn-backend:9500/v1/snapshotinputs",
        "snapshots": "http://longhorn-backend:9500/v1/snapshots",
        "volumeConditions": "http://longhorn-backend:9500/v1/volumeconditions",
        "volumes": "http://longhorn-backend:9500/v1/volumes"
    },
    "type": "apiVersion"
}`

And on the 2nd node:
curl: (6) Could not resolve host: longhorn-backend

**Comment by yasker** [comment]
Yeah, that confirmed you have a network issue with your second node.

All the nodes should able to visit `longhorn-backend`, inside the pod of `longhorn-system` namespace. That's why CSI plugin failed to start.

**Comment by marcteyssier** [comment]
It's the same error in another work space.
It's a problem with my rancher, I try to fix it before restart longhorn.

**Comment by marcteyssier** [comment]
I have the problem.
This is because I use 2 OVH servers with ovh kernel for Ubuntu 16.04.
I check if it's compatible with docker (https://docs.docker.com/install/linux/linux-postinstall/#troubleshooting Kernel compatibility), and I have 1 error !

I reinstall my 2 nodes with default Ubuntu 16.04 kernel and all is ok and up :-)

Thank you for your help !
