### ISSUE TITLE
Passing AWS credentials to backup snapshots to S3 

### ISSUE THREAD

**Issue by payes** [rancher/longhorn#277]
Hi,
I was trying to backup a snapshot to s3 using the following command:
sudo docker exec -it Container_ID longhorn backups create snapshotName --dest S3_destination_URL

Above command doesn't work, if the credentials are added after the longhorn controller starts inside the container.

I had to modify the file package/Dockerfile to generate the AWS credentials file. And then built the longhorn image.
Is there any way to pass these credentials with the backup create/restore commands ?

**Comment by yasker** [comment]
You can use AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variable instead. See https://github.com/aws/aws-sdk-go#configuring-credentials
