### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by SacDin** [rancher/longhorn#28]
longhorn-manager is giving following error : 
```
sac@node2:~$ kubectl logs longhorn-manager-j6v7v -n longhorn-system
INFO[0000] Detected IP is 10.32.0.12
INFO[0000] Kubernetes orchestrator is ready
INFO[0002] Listening on 10.32.0.12:9500
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x110aec9]

goroutine 102 [running]:
github.com/rancher/longhorn-manager/manager.(*VolumeManager).VolumeCreateBySpec(0xc4203fad20, 0xc420146da0, 0x17, 0x0, 0x0)
	/go/src/github.com/rancher/longhorn-manager/manager/manager.go:406 +0x529
created by github.com/rancher/longhorn-manager/manager.(*VolumeManager).startProcessing
	/go/src/github.com/rancher/longhorn-manager/manager/process.go:38 +0x3c7
```

For second time setup, do I need to clean any directories on the node ?

**Comment by yasker** [comment]
Can you list the reproduce steps?

**Comment by SacDin** [comment]
On digging further, found following : 
- If I deploy manager in namespace1 (in which one volume was previously attached), it runs perfectly with following logs : 
```
DEBU[0628] volume my-volume-1 desire state is detached
DEBU[0628] volume my-volume-1 state is detached
DEBU[0632] volume my-volume-1 state is detached
DEBU[0632] volume my-volume-1 desire state is detached
DEBU[0632] volume my-volume-1 state is detached
DEBU[0633] volume my-volume-1 state is detached
DEBU[0633] volume my-volume-1 desire state is detached
DEBU[0633] volume my-volume-1 state is detached
```
The logs are continuous.
- If I deploy it in any new namespace, the segmentation fault occurs. 
- No pods are currently requesting PVC / flexvolume named "my-volume-1". All pods are deleted. Still the manager is having logs related to "my-volume-1" which was previously used. 
- Is it possible that manager is saving these volume names somewhere ? I checked all hostPath directories but have found nothing yet.

**Comment by yasker** [comment]
Sounds like CRD wasn't cleaned up.

I will include that in the README.md as well.

For now, can you use `kubectl -n longhorn-system delete crd -l longhorn-manager` to clean up the CRD stored in the Kubernetes and try again?

**Comment by SacDin** [comment]
Wonderful. 
Confirmed, working now in separate namespace.
Closing. Many thanks for the support.
