### ISSUE TITLE
Sometimes no volumes are displayed in longhorn-ui

### ISSUE THREAD

**Issue by SacDin** [rancher/longhorn#29]
- Volume listing keeps loading and loading
- Host count is displayed but volumes are always 0
- But, sometimes volumes are listed and counts are also displayed
- What might be causing this ?

More information:
- longhorn-frontend service always remain in pending state
- No errors in longhorn-ui logs

**Comment by yasker** [comment]
Can you open the developer tools in the web browser to check which requests failed? Also, can you check if anything unusual in the Longhorn manager logs?

UI is asking `longhorn-backend` service for the IP to send requests. `longhorn-backend` service will redirect the requests to one of the running longhorn-manager pod in the daemon set. So it sounds like at least some of longhorn managers got troubles on response UI's API request.

**Comment by yasker** [comment]
Close the issue for now. Please reopen if the solution doesn't work.
