### ISSUE TITLE
Longhorn CSI test cases freeze on K8s 1.11 clusters

### ISSUE THREAD

**Issue by LLParse** [rancher/longhorn#290]
Kubernetes version: v1.11.2 (installed with Rancher)
Longhorn version: v0.3.1-rc1
Longhorn-test versions afflicted: v0.3.0, v0.3.1-rc1

Deploy the Longhorn test pod with following arguments: 
```
args: ["-m", "csi"]
````
When `test_csi_io` runs, it will hang indefinitely after `csi-io-test` Pod is created and running. Manually testing CSI plugin on K8s 1.11 succeeds. This automated test succeeds on previous versions of Kubernetes such as 1.10

**Comment by yasker** [comment]
Freeze is fixed by: https://github.com/rancher/longhorn-tests/commit/ac0673cb2a4721667c3a5cff0f7259e9f020096b

It sounds like a bug in Kubernetes. Either in python library or stream. Deal with it later.

**Comment by yasker** [comment]
Cannot reproduce on Kubernetes v1.12.4
