### ISSUE TITLE
Change number of replicas for a volume

### ISSUE THREAD

**Issue by KuroObi** [rancher/longhorn#293]
Is it possible to change the number of replicas for a longhorn volume after it was created and already used?

**Comment by yasker** [comment]
We don't support change the replica number at the moment. It can be added if necessary. What's your use case?

**Comment by KuroObi** [comment]
In our development stacks we only use a replica factor of 1, but if we were to transfer it to production we would need the redundancy.

**Comment by yasker** [comment]
I see. Just to be clear, we don't recommend to use replica number of 1. You won't have any redundancy in this case.

Yeah, we can look into adding this feature in the future releases.

**Comment by courcelm** [comment]
I'm looking to deploy Elasticsearch with Longhorn. Since Elasticsearch replicates its data to the cluster nodes I think it would be useful to be able to set replica number to 1.

**Comment by yasker** [comment]
@courcelm Currently Longhorn does allow to set the replica number to 1. But for now, you cannot change it after the volume was created.

**Comment by courcelm** [comment]
How can it be done before creating it?

**Comment by yasker** [comment]
You can set it in the storage class. https://github.com/rancher/longhorn/blob/master/examples/storageclass.yaml

**Comment by yasker** [comment]
Filed #299 . Close this one.
