### ISSUE TITLE
Manager: support changing volume's `NumberOfReplicas` setting

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#299]
https://github.com/rancher/longhorn/issues/293

Overview
There are requests to run Longhorn in a single replica setup since the workload itself can replicate by themselves.
Also, enable the ability for users to update volume's `NumberOfReplicas` setting can enable a few interesting use cases, e.g. manually evict one node without losing the resiliency of the volume, increase volume's resiliency without creating another volume.
And we can introduce a global setting for the default replica number.

Pre-requirement:
1. The volume must be healthy.
2. The volume must not during the migrating process.
3. The volume must not during the engine upgrading process.

Design:
1. The number of replicas cannot exceed a predefined value or lower than 1.
2. If the number of replicas was reduced by the user, the manager will not automatically destroy any replicas. The user must do it manually if they wish to preserve space.
3. The volume will report "excessive resiliency" error if the number of healthy replicas is more than expected. But it won't impact volume's normal operations, including attaching after detaching. The volume will still try to use all the healthy replicas it knows.

**Comment by Dremor** [comment]
May I add an idea : make it possible to set the default number of replicas in the general settings.

Use case : 
- Users who want to preserve disk space, and manually set more replicas for specific volumes.
- Users who want to have a more reliable cluster by adding more replicas by default.

**Comment by yasker** [comment]
@Dremor Yeah, that's definitely doable. We can add that for the next release.

**Comment by yasker** [comment]
Backend is done (except for the `excessive resiliency` reporting).

Pending on https://github.com/rancher/longhorn/issues/359
