### ISSUE TITLE
Use with Rancher Cattle

### ISSUE THREAD

**Issue by machship-mm** [rancher/longhorn#3]
You mention in the blog that Longhorn is compatible with Swarm and Kubernetes - what about Cattle?

**Comment by sheng-liang** [comment]
Cattle uses standard Docker volume plugins and will of course be supported.

**Comment by asthomasdk** [comment]
Any eta on when this is be available?

**Comment by gaieges** [comment]
I'm also curious how this works given the wiki's statement of "swarm mode must be enabled" for a multi-host setup.  Will that continue to be, or is it currently, the only way to get a multi-host volume cluster?

**Comment by yasker** [comment]
@gaieges Swarm mode is currently only used to provide an overlay network for Longhorn. You can set up any other overlay networking across the hosts for Longhorn as well. The community is more familiar with swarm mode so we tested and showed case of Swarm mode overlay networking in our instruction.

**Comment by yasker** [comment]
@asthomasdk @machship-mm We're planning to support Rancher and Kubernetes at early second half of year.

**Comment by asthomasdk** [comment]
Thanks for the info. I understand from the Meetup yesterday that you are re-writing the rancher support to something better - which makes sense. 

I would have thought that supporting Rancher natively to start with would make the most sense though - as this puts Rancher in a very strong position. The work you guys are doing with Longhorn is an increasingly important part of the container management stack - and there is already so much you can do out of the box in Rancher. Easily, effectively and safely managing containers and data across hosts is very high on my list. 

So you definitely have my vote for Rancher support :;-)

**Comment by failedguidedog** [comment]
Any developments for Longhorn integration in Rancher?

If not, I'll be making my own Rancher catalog entry to create an infrastructure stack for Longhorn, but if an integration is coming soon I will not bother.

**Comment by yasker** [comment]
Hi @failedguidedog,

Feel free to try it in Docker way and make a catalog.

We're working on Rancher and Kubernetes integration but haven't had a date set yet. In our plan, it will be more complex than just a catalog because we're planning to use Rancher/Kubernetes to orchestrate the longhorn-engine instances around.

**Comment by wcgcoder** [comment]
Checking in again here. I realize that you've probably re-focused to only support Rancher 2.0. 
It's worth mentioning that everyone else is being left behind who's not comfortable with the Kubernetes transition. Of course I find it also odd that it wasn't initially integrated into Rancher right when it was being developed, but I understand there are many technical hurdles you're overcoming. 

To-date, the alpha has not released any information on an automated upgrade path from cattle to Kubernetes, forcing people to rebuild their environments. I of course hope this changes.

Despite all this, I am very grateful to the Rancher Labs team. ❤️

**Comment by yasker** [comment]
We've moved to using Kubernetes for orchestration. Rancher 2.0 will be native since it's based on K8S as well.

We will have more integration with Rancher 2.0 later.
