### ISSUE TITLE
Volumes unmounting and containers going down

### ISSUE THREAD

**Issue by Aeolun** [rancher/longhorn#301]
I have been using Rancher for a few weeks now, and by far the most annoying issue is my Longhorn volumes suddenly detaching and becoming unreachable, bringing a random set of pods down each time.

I get some fairly unhelpful messages like:

(Apologies, apparently cannot insert the right characters for code formatting on iPhone)

Unable to mount volumes for pod "bitbucket-87f479b99-psnbs_default(cb48ec25-bcd8-11e8-93e2-d43d7edaffee)": timeout expired waiting for volumes to attach or mount for pod "default"/"bitbucket-87f479b99-psnbs". list of unmounted volumes=[bitbucket-volume]. list of unattached volumes=[bitbucket-volume default-token-zh2sk]
 14 minutes ago
 Warning
 FailedMount
 MountVolume.SetUp failed for volume "pvc-caff2517-bcd8-11e8-93e2-d43d7edaffee" : rpc error: code = Internal desc = exit status 1

I mean, I already know it isn’t mounted. Right now I manually remount the volume to one of the nodes, and it’ll eventually fix itself after I reboot the connecting pods.

I really have no idea how to deal with this except use anything other than Longhorn. If you have any ideas on how I could locate and fix the problem, I would very much appreciate it.

**Comment by yasker** [comment]
Can you get the Longhorn manager and related driver log? See https://github.com/rancher/longhorn/blob/master/docs/troubleshooting.md#troubleshooting-guide on how to get the logs.

**Comment by Aeolun** [comment]
The logs for longhorn manager (2 instances) are attached. Unfortunately I didn't get much useful information out of tailing the volume (I stopped and started the service and it was reattached), but got only this, which seems more like an access log:

```
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-3208b412] 213.239.209.220 - - [29/Sep/2018:02:06:22 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-07acdf72] 144.76.111.179 - - [29/Sep/2018:02:06:22 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-f17df4bb] 213.239.209.220 - - [29/Sep/2018:02:06:22 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-3208b412] 213.239.209.220 - - [29/Sep/2018:02:06:23 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-07acdf72] 144.76.111.179 - - [29/Sep/2018:02:06:23 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-f17df4bb] 213.239.209.220 - - [29/Sep/2018:02:06:23 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-3208b412] 213.239.209.220 - - [29/Sep/2018:02:06:24 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-07acdf72] 144.76.111.179 - - [29/Sep/2018:02:06:24 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-f17df4bb] 213.239.209.220 - - [29/Sep/2018:02:06:24 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-3208b412] 213.239.209.220 - - [29/Sep/2018:02:06:25 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-07acdf72] 144.76.111.179 - - [29/Sep/2018:02:06:25 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-f17df4bb] 213.239.209.220 - - [29/Sep/2018:02:06:25 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-3208b412] 213.239.209.220 - - [29/Sep/2018:02:06:26 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-07acdf72] 144.76.111.179 - - [29/Sep/2018:02:06:26 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-f17df4bb] 213.239.209.220 - - [29/Sep/2018:02:06:26 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-3208b412] 213.239.209.220 - - [29/Sep/2018:02:06:27 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-07acdf72] 144.76.111.179 - - [29/Sep/2018:02:06:27 +0000] "GET /v1 HTTP/1.1" 200 978
[pvc-fd1f8511-be60-11e8-93e2-d43d7edaffee-r-f17df4bb] 213.239.209.220 - - [29/Sep/2018:02:06:27 +0000] "GET /v1 HTTP/1.1" 200 978
```

[longhorn-manager-1.log](https://github.com/rancher/longhorn/files/2430174/longhorn-manager-1.log)
[longhorn-manager-2.log](https://github.com/rancher/longhorn/files/2430175/longhorn-manager-2.log)

**Comment by yasker** [comment]
I think you have network issues.

>E0927 04:04:14.494367 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Setting: Get https://10.43.0.1:443/apis/longhorn.rancher.io/v1alpha1/settings?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: getsockopt: connection refused
E0927 04:04:14.548562 1 reflector.go:205] github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Job: Get https://10.43.0.1:443/apis/batch/v1/jobs?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: getsockopt: connection refused
E0927 04:04:14.549306 1 reflector.go:205] github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: Get https://10.43.0.1:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: getsockopt: connection refused
E0927 04:04:14.553741 1 reflector.go:205] github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.CronJob: Get https://10.43.0.1:443/apis/batch/v1beta1/cronjobs?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: getsockopt: connection refused
E0927 04:04:14.555032 1 reflector.go:205] github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta2.DaemonSet: Get https://10.43.0.1:443/apis/apps/v1beta2/daemonsets?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: getsockopt: connection refused
E0927 04:04:14.694335 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Replica: Get https://10.43.0.1:443/apis/longhorn.rancher.io/v1alpha1/replicas?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: getsockopt: connection refused

and:
```
time="2018-09-27T04:05:01Z" level=warning msg="Failed to start monitoring pvc-fd1db948-be60-11e8-93e2-d43d7edaffee-e-6b68ff54, cannot connect"
```

and your Longhorn engine crashes without any warning from manager's perspective.

What's the bandwidth of your network? Can you check if your Kubernetes overlay network is stable?

**Comment by Aeolun** [comment]
The bandwidth is technically 1Gbit, and I have no doubt that it's realistically at least somewhere within an order of magnitude of that. 

Unfortunately, I'm not quite advanced enough to have any idea of how to establish whether the kubernetes overlay network is stable. Do you have any idea how I could do this? Or how to deliberately trigger instability to confirm that this is indeed what causes the failure?

**Comment by Aeolun** [comment]
This was resolved by not having my servers in different datacenters separated by two countries. 

I still don't think that should technically result in this issue, but for now it works for me.

**Comment by yasker** [comment]
@Aeolun Oh, that explains it. You may have enough bandwidth but the network latency is too big across the datacenter. In general, no primary storage can be spread across different datacenter since it have to provide a response in a constrained timeframe. In your case, seems even the overlay network cannot work well across the datacenter.

In fact, we're looking into a way to replica data into another datacenter in an asynchronous way. The asynchronous replica can be switched to synchronized if the workload fail over happens across the availability zone/ in another datacenter. It's still very early to tell when the feature will be available though.
