### ISSUE TITLE
Support of Backup { GCE Bucket / Minio }

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/longhorn#303]
Hi

Can you add the features of Backup of GCE Bucket / Minio.

Thanks,
Keerthi

**Comment by vincent99** [comment]
Both of those have S3-compatible APIs and should be usable today.

**Comment by yasker** [comment]
And our example for backup uses Minio.

https://github.com/rancher/longhorn/blob/master/docs/backup.md#setup-a-local-testing-backupstore
