### ISSUE TITLE
Volumes deleted by Longhorn not deleted in Rancher

### ISSUE THREAD

**Issue by shinebayar-g** [rancher/longhorn#305]
I've created Longhorn volumes when creating MongoDB replica set from catalog. Then I deleted my MongoDB replica set and deleted its created volumes on longhorn. But that volumes is still exist in rancher volumes menu.

**Comment by yasker** [comment]
You need to delete the volume from Kubernetes side (PVC and PV). Kubernetes don't know about the volume deleted by Longhorn. There is no way for a storage vendor to tell Kubernetes the underlying volume has been deleted.

**Comment by shinebayar-g** [comment]
Thanks for the explanation, so I go to my cluster/volumes and delete the existing volume that are deleted in Longhorn? Is it the right step?

**Comment by yasker** [comment]
Yeah, if PVC for the namespace is there, delete the PVC first. After that, if any volume remains, delete the persistent volume under the cluster.

**Comment by shinebayar-g** [comment]
Hmm I tested it with another deployment redis cluster from catalog app, since my MongoDB install stuck on installing step after I try to re-install MongoDB.

Here is the result of redis cluster.
First I deployed redis from Catalog Apps with longhorn PV option. Everything installed just fine. Then I deleted redis from Catalog Apps. It removed related volumes from both Longhorn volumes and Rancher volumes section, nothing related about redis left. This time it was different result.

Then I re-tested again with redis. Installed redis cluster using same options, redis is installed fine. Then I removed redis from Catalog Apps. This time related volumes weren't removed from Rancher volumes and Longhorn volumes.

Can you tell me what should happen when I remove something from Catalog Apps?
Which is the right behaviour you expected?

I think if someone remove application from catalog apps with persistent volume, there should be option to decide remove existing volume or not ?

**Comment by yasker** [comment]
@shinebayar-g The default [reclaim policy](https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/) of longhorn storage class is `Delete`. So the PV should be deleted once the PVC was deleted.

The deletion of Catalog Apps should trigger the deletion of PVCs associated with it, thus resulting in the deletion of PV and Longhorn volumes. You can check the PVCs in the namespace after you removed the app. They should have been deleted.

If the volume was created before the app, it won't be deleted. But the most apps in our catalog doesn't have this option. We're working on fix it. https://github.com/rancher/charts/issues/47

Also, see my demo using Wordpress on how to retain the data in apps: https://www.youtube.com/watch?v=vRqvz-Ii49A&feature=youtu.be&t=55m24s.

**Comment by shinebayar-g** [comment]
@yasker Thanks for the great explanation. I understand you very well. However I didn't catch this part:

> You can check the PVCs in the namespace after you removed the app. They should have been deleted.

When I installing Redis from Catalog Apps there was name and namespace option, it was default to **redis**
You mean this?

If yes this is not deleted after I removing redis from Catalog Apps. It's still there.
![image](https://user-images.githubusercontent.com/3091558/46242103-cc31ff80-c3f6-11e8-9442-e7882b9c0c1d.png)

If I remove this namespace that redis installation created, it's deleting successfully both Rancher and Longhorn volumes.

**Comment by shinebayar-g** [comment]
**Another test** Alright, since you said that removing catalog apps triggers deletion of related namespace, what if I use default namespace? Or same namespace as other apps like MongoDB?
It'll delete related namespace and remove all volumes created by another app in same namespace right?
This is getting quite interesting.

**Comment by yasker** [comment]
I meant the PVCs should be deleted if it's created along with the app, not the namespace.

If the PVCs remains, then the PV would remain, as well as the Longhorn volume. That would sounds like a Rancher bug, which failed to clean up the resources after the app was deleted.

**Comment by yasker** [comment]
Close the issue due to the age. Feel free to reopen if needed.

**Comment by tiger0425** [comment]
I have the same problem? How to deal with it, please?

**Comment by yasker** [comment]
@tiger0425 You need to follow https://github.com/rancher/longhorn/issues/305#issuecomment-425619372 and delete the volume from Kubernetes side.
