### ISSUE TITLE
Kubernetes v1.12: driver name io.rancher.longhorn not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by Maxwell1987** [rancher/longhorn#310]
When I upgrade rancher to 2.1.0 / k8s 1.12.0，all workloads using longhorn will not start, the error message is like this
MountVolume.MountDevice failed for volume "pvc-9cb54cca-a9aa-11e8-b476-fa163e532171" : driver name io.rancher.longhorn not found in the list of registered CSI drivers
I tried to create a new workload and tried to redeploy longhorn, the error still exists.

**Comment by yasker** [comment]
Sounds like 1.12 break the CSI backward compatibility. We're working on it.

**Comment by hunsche** [comment]
The same thing happens to me when starting the deployment, how should I proceed temporarily?

**Comment by yasker** [comment]
Fixed.

**Comment by glawson6** [comment]
What is the fix? Is there a link or instructions somewhere?

**Comment by yasker** [comment]
@glawson6 We haven't released the fix yet. We will release v0.3.2 next week and provide the upgrade instructions.

**Comment by AmreeshTyagi** [comment]
I am also getting this issue while deploying statefulset on Kubernetes v1.12 & longhorn v0.3.2.
Any idea?

**Comment by yasker** [comment]
@AmreeshTyagi The Kubernetes v1.12 changed the CSI interface. We automatically detect that for v1.12 when deploying. But your setup has already been deployed in v1.11 way. You can manually delete the `longhorn-driver-deployer` and it should automatically redeploy correctly again.

**Comment by AmreeshTyagi** [comment]
@yasker Thanks. Tried after deleting from catalog & it worked. Thanks again.
