### ISSUE TITLE
Add Longhorn to CNCF Landscape

### ISSUE THREAD

**Issue by phal0r** [rancher/longhorn#313]
Hi guys,

I think this is a really cool piece of technology and deserves more attention. What about adding it to the `cloud-native storage` section of the CNCF Landscape -> https://landscape.cncf.io/format=landscape&zoom=150

**Comment by yasker** [comment]
Good idea! I will make a PR for it after v0.3.2 released.

**Comment by phal0r** [comment]
Yeah, your pull request was accepted. Nice!
