### ISSUE TITLE
Documented procedures for removing a node with longhorn provisioned

### ISSUE THREAD

**Issue by jgallucci32** [rancher/longhorn#315]
I am unable to find instructions for removing a node from the cluster with storage provisioned on the node with longhorn. There are settings to disable scheduling, however, what are the procedures for removing a node and rebalancing the data to other nodes in the cluster.

An example use case would be wanting to re-size an existing cluster with newer instances. Our first deployment uses 3 instances with m2.large nodes, but we wanted to expand the cluster to add 3 m2.xlarge nodes and once things balanced out (application-wise), remove the 3 original nodes.

The goal here would be to have the storage follow the same process of decommissioning a node as Kubernetes does, but considerations for data re-balancing need to be made.

**Comment by yasker** [comment]
Hi @jgallucci32 

The issue you mentioned is one of the issues we're currently working on: https://github.com/rancher/longhorn/issues/306

We will address this in the next release.

Btw, rebalancing (by rebuilding a new replica) should happen automatically when you attached the volume, even the node original replica resides is down. If that's not the case, please let me know.

**Comment by yasker** [comment]
https://github.com/rancher/longhorn/issues/306 has been fixed.
