### ISSUE TITLE
Delete volumes entirely with Kubernetes

### ISSUE THREAD

**Issue by tboerger** [rancher/longhorn#32]
Hi,

I have launched Longhorn with my Kubernetes Setup, attaching volumes and detaching volumes works fine, but how can I enforce that a volume gets really deleted and not only detached? Adding `persistentVolumeReclaimPolicy: Delete` to the PersistentVolume seems to be the wrong option...

**Comment by yasker** [comment]
We haven't added the support for `persistentVolumeReclaimPolicy: Delete`, and currently the volume can only be deleted from Longhorn API/UI, not from K8S. It's in the roadmap.

**Comment by tboerger** [comment]
Sad that it's not possible in an automated, integrated way. Is the roadmap somewhere public visible?

**Comment by yasker** [comment]
Regarding this feature, it should be implemented with our Dynamic Provisioner support, which should be there in about a month.

**Comment by yasker** [comment]
Hi @tboerger 

We just completed the support for `persistentVolumeReclaimPolicy`, since we've added support Kubernetes Dynamic Provisioner now. You can give it a try now.

Notice the API changes, so you would need to clean up and redeploy.
