### ISSUE TITLE
Upgrade error: Replica delete jobs orphaned

### ISSUE THREAD

**Issue by LLParse** [rancher/longhorn#322]
The old replica delete logic that is being replaced in v0.3.2 creates jobs to cleanup replica data. These jobs are not used in the new delete logic.

While upgrading across the v0.3.2 boundary, any manager in the process of deleting a replica will potentially orphan a replica delete job. The new deletion logic is replayed for these replicas in the new version; the result of the orphaned job is unimportant.

Post-upgrade crossing the v0.3.2 boundary, we need to delete these orphaned jobs, if any exist.

**Comment by yasker** [comment]
Done.
