### ISSUE TITLE
engine: 2 TB size limit

### ISSUE THREAD

**Issue by magnusmaki** [rancher/longhorn#324]
I cant make volumes larger than 2 TB, is it "by design" or is it configurable somewhere?
(When creating over 2TB the filesystem cant be created)
Really like longhorn! :)

**Comment by yasker** [comment]
We don't aware of this limitation. What's the error message? Longhorn should be able to support block device as big as filesystem allowed for a single file, e.g. 16TB for ext4.

**Comment by yasker** [comment]
@magnusmaki We've reproduced the issue in our lab. Looking into it.

**Comment by magnusmaki** [comment]
Ok! thanks!

**Comment by yasker** [comment]
Fixed. We will release the fix with the next release.
