### ISSUE TITLE
Moving pod to a different node - volume does not reattach

### ISSUE THREAD

**Issue by graememross** [rancher/longhorn#328]
I installed longhorn to our in-house development cluster yesterday.

My first test was to attach a volume to a pod and load some data - all worked as expected.
I then tried to spin up another copy of the pod and expected the volume to attach to the new pod as well, my access mode is 
```
spec:
  accessModes:
  - ReadWriteMany 
```
What happened is that the Volume failed to mount with the following messages in the Rancher console
`

Normal | SuccessfulAttachVolume | AttachVolume.Attach succeeded for volume "pvc-e8518f89-e34f-11e8-9e98-005056be109a" | 14 minutes ago
-- | -- | -- | --
Warning | FailedMount | MountVolume.SetUp failed for volume "pvc-e8518f89-e34f-11e8-9e98-005056be109a" : rpc error: code = Internal desc = exit status 1

`
In the appropriate longhorn-csi-plugin log I found

`
E1108 11:17:14.087947       1 mount_linux.go:523] format of disk "/dev/longhorn/pvc-73386ad7-e346-11e8-9e98-005056be109a" failed: type:("ext4") target:("/var/lib/kubelet/pods/d4b8d3c3-e347-11e8-bc5e-005056be4270/volumes/kubernetes.io~csi/pvc-73386ad7-e346-11e8-9e98-005056be109a/mount") options:(["defaults"])error:(exit status 1)

E1108 11:17:14.087982       1 utils.go:100] GRPC error: rpc error: code = Internal desc = exit status 1
time="2018-11-08T11:17:15Z" level=info msg="NodeServer NodePublishVolume req: volume_id:\"pvc-73386ad7-e346-11e8-9e98-005056be109a\" target_path:\"/var/lib/kubelet/pods/d4b8d3c3-e347-11e8-bc5e-005056be4270/volumes/kubernetes.io~csi/pvc-73386ad7-e346-11e8-9e98-005056be109a/mount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > > volume_attributes:<key:\"fromBackup\" value:\"\" > volume_attributes:<key:\"numberOfReplicas\" value:\"3\" > volume_attributes:<key:\"staleReplicaTimeout\" value:\"30\" > volume_attributes:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1541607102428-8081-rancher.io/longhorn\" > "

E1108 11:17:15.193838       1 mount_linux.go:148] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-73386ad7-e346-11e8-9e98-005056be109a /var/lib/kubelet/pods/d4b8d3c3-e347-11e8-bc5e-005056be4270/volumes/kubernetes.io~csi/pvc-73386ad7-e346-11e8-9e98-005056be109a/mount
Output: mount: special device /dev/longhorn/pvc-73386ad7-e346-11e8-9e98-005056be109a does not exist
`

I then tried to simplify the test by trying to just move the existing pod from the one node to another.

The same thing happened.

However I then went into the longhorn GUI and told it attach the volume onto the appropriate node. Once the volume had attached the pod then started up properly and was able to read the data.

Any ideas what might be wrong?

**Comment by graememross** [comment]
Just checked and there doesn't seem to be any way to load a volume into a second pod when it is already mounted in the first pod - am I missing something here?

**Comment by yasker** [comment]
Hi @graememross 

It's expected. Longhorn is a distributed block storage solution, so like AWS EBS or Google Persistent Disk, it's `ReadWriteOnce` in Kubernetes's word. One volume cannot be used by more than one node at the same time. You can see https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes for more details.

**Comment by graememross** [comment]
Ok thanks for the quick response. I can work with that in my use case. 

Just tested with ReadWriteOnce and it works as expected.

Any plans to implement ReadWriteMany (or ReadOnlyMany) I can imagine use cases where that would be useful and desirable - tho for my present uses cases I don't really need it - just asking :)

**Comment by yasker** [comment]
@graememross It's not possible for a block storage solution to implement ReadWriteMany.

But ReadOnlyMany is possible. We're tracking it with https://github.com/rancher/longhorn/issues/4.
