### ISSUE TITLE
Longhorn default engine 0.3.0 hangs "deploying", can't change default engineimage

### ISSUE THREAD

**Issue by florianb** [rancher/longhorn#330]
I recently deployed longhorn v0.3.1 by hand using the installation description in the readme. The installation went well except from the state of the longhorn engine.

The UI displayed the engineimage `rancher/longhorn-engine:v0.3.0`, which hangs in the "deploying" state. I then added the engineimage `rancher/longhorn-engine:v0.3.1` by hand which deployed successful.

But i am still not able to add volumes since the default engineimage is still `rancher/longhorn-engine:v0.3.0`. I read somewhere that it should be possible to change the default-engineimage in the shell of the longhorn-manager. I opened an interactive terminal session but i found no way to set the default engineimage.

So my question is, how to change the default engineimage? 🌷

**Comment by florianb** [comment]
I got an update to my situation - the recently installed engine v0.3.1 disappeared. So i guess i have to try to fix the installation of the engine 0.3.0 first.

**Comment by florianb** [comment]
I was able to fix the deployment of the 0.3.0 engine. Is it necessary or recommended to try upgrading to 0.3.1?

**Comment by yasker** [comment]
@florianb In fact, Longhorn v0.3.1 should use Longhorn Engine v0.3.0 as the default engine. The versions of Longhorn and Longhorn Engine are not always consistent. I've added more information to the homepage to clarify that.

**Comment by florianb** [comment]
Thank you very much @yasker!
