### ISSUE TITLE
Dynamic volume

### ISSUE THREAD

**Issue by aborderon** [rancher/longhorn#335]
Hello,

I come here to ask a quick question, I could see on previous problems that it was not possible to resize the size of a persistent volume Longhorn.

However, I would like to know if it is possible to create a dynamic volume, that is to say with a default size of 6 GB for example and to see the size of the volume automatically expand according to the need of the application that uses it ?

Typically, for the example of a Mysql database that uses longhorn as persistent storage and increases over time what would you recommend?

Thank you

**Comment by yasker** [comment]
@aborderon Longhorn volume themselves are stored in the sparse format, that means the position which wasn't written any data won't be stored on the disk anyway. So you can specify a bigger size than you expect to use and it will automatically use all the spaces till that specified size.

However, there is a catch. For some filesystem e.g. ext4, the size of the metadata of filesystem related to the total size of the disk. The bigger size of the disk, the larger space the metadata would take. But it won't be too big e.g. 20G ext4 should take only about 200M of the extra space, make it still a reasonable choice.

**Comment by aborderon** [comment]
Okay, fine, I understand better. thank you for this clarification.

I will try to anticipate the growth of our base.
