### ISSUE TITLE
chart: Need image modification support

### ISSUE THREAD

**Issue by BalaBalaYi** [rancher/longhorn#339]
Like the implement in openebs which you can modify the image and tag:
![image](https://user-images.githubusercontent.com/23303886/49053965-5cd96000-f22d-11e8-97ea-1a84e20a5246.png)

**Comment by BalaBalaYi** [comment]
@yasker 
For now, i can use yml to define the private-registry for longhorn images.
```
driver: csi
persistence.flexvolumePath: ""
persistence.defaultClass: 'true'
ingress.enabled: 'false'
ingress.host: xip.io
service.ui.type: Rancher-Proxy
service.ui.nodePort: ""
image.longhorn.engine: harbor.io/library/rancher/longhorn-engine
image.longhorn.manager: harbor.io/library/rancher/longhorn-manager
image.longhorn.ui: harbor.io/library/rancher/longhorn-ui
```

But i don't know how to define the private-registry for the following images:
![image](https://user-images.githubusercontent.com/23303886/49212322-b9d74080-f3fc-11e8-9269-3774c5768339.png)

Could you give me some advise? thx

**Comment by yasker** [comment]
@BalaBalaYi Those are in the command line argument of `longhorn-driver-deployer`. See https://github.com/rancher/longhorn-manager/blob/master/app/driver.go#L73

You can update the cmdline parameter of `longhorn-driver-deployer` to use different images for csi.  Parameters (as you seen in the code) are: `csi-attacher-image`, `csi-provisioner-image`, and `csi-driver-registrar-image`

**Comment by BalaBalaYi** [comment]
@yasker Get it. Thx!

**Comment by yasker** [comment]
Will be addressed in https://github.com/rancher/charts/pull/132
