### ISSUE TITLE
will longhorn have a s3 compatible object storage?

### ISSUE THREAD

**Issue by thbeh** [rancher/longhorn#353]
Is there a plan to create a S3 compatible object storage for longhorn?

**Comment by yasker** [comment]
@thbeh Longhorn supports S3 compatible object storage. See https://github.com/rancher/longhorn/blob/master/docs/backup.md#setup-a-local-testing-backupstore for example.

**Comment by thbeh** [comment]
Sorry, I meant will longhorn have a direct S3 API for object storage instead of dependancy on minio, etc. Something similar to Zenko's s3server?

**Comment by yasker** [comment]
No, Longhorn doesn't act as S3 server. User can use any S3 compatible server with Longhorn.

And for Zenko, I think it's a controller provides S3 API but not storing the data by itself. It replicates data to other cloud storages e.g. AWS S3.

What would be the use case for Longhorn to provide S3 API? If you meant it's more like Ceph Object storage, Longhorn doesn't support it. Longhorn only designed to provide the block device at the moment.

**Comment by thbeh** [comment]
Thanks.

**Comment by milovanderlinden** [comment]
> @thbeh Longhorn supports S3 compatible object storage. See https://github.com/rancher/longhorn/blob/master/docs/backup.md#setup-a-local-testing-backupstore for example.

The link is dead.

**Comment by yasker** [comment]
@milovanderlinden please see https://github.com/longhorn/longhorn/blob/master/docs/snapshot-backup.md#setup-a-local-testing-backupstore instead.

**Comment by milovanderlinden** [comment]
Yes, I found it, but I justed wanted to make sure others would not stumble on a dead link. By the way, in github comments you can use relative URL's.

**Comment by xvilo** [comment]
> @milovanderlinden please see https://github.com/longhorn/longhorn/blob/master/docs/snapshot-backup.md#setup-a-local-testing-backupstore instead.

Link is dead, again

**Comment by mantissahz** [comment]
Hi @xvilo 
here are Refs: 
https://github.com/longhorn/longhorn/blob/v0.8.0/docs/snapshot-backup.md#setup-a-local-testing-backupstore
https://longhorn.io/docs/1.3.1/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-a-local-testing-backupstore

**Comment by Mrs-Feathers** [comment]
> Sorry, I meant will longhorn have a direct S3 API for object storage instead of dependancy on minio, etc. Something similar to Zenko's s3server?

yes, s3gw by aquarius labs is an s3 gateway specifically designed for longhorn. while longhorn does not have any capabilities for s3 clients for storage (except backups), s3gw provides a gateway that allows all longhorn storages to be accessed as if they were s3 buckets..
