### ISSUE TITLE
Backup volume not appear

### ISSUE THREAD

**Issue by kc004** [rancher/longhorn#361]
I have created S3 backup path for Longhorn and provided secret keys along with it.
It seems backup created on S3 successfully but on the backup tab it doesn't show up. Is there any other way I can restore those volumes? 

![image](https://user-images.githubusercontent.com/8349649/50965152-2adb3f00-14f7-11e9-8454-e4d860c25d36.png)

![image](https://user-images.githubusercontent.com/8349649/50965272-8c031280-14f7-11e9-9d72-e0e243b8e82e.png)

---
Version: `v0.3.2`

**Comment by yasker** [comment]
@kc004 Can you click the left-top dropdown and see if the volume is there?

**Comment by kc004** [comment]
Yes, i saw it not a single volume is there.

**Comment by yasker** [comment]
If you go to the volume detail page, then select `Backups` from the top-right drop down menu, are you able to see the backup?

Also, can you check what's in `backups` folder of s3? If a backup was completed, it should show a related file there.

**Comment by kc004** [comment]
When i clicked on create backup one snapshot is generated and i can see files are being transmitted in S3. There are 2 folders and 1 file
2 Folders:
1. backup - which contains backup.cfg
2. blocks - It contains many folders and when i go through them they contains .blk file.

1 file - volume.cfg

**Comment by yasker** [comment]
@kc004 Hi, have you figured out anything? Recently I also encounter it once but cannot reproduce it since.

**Comment by yasker** [comment]
@kc004 the snapshot issue has been fixed in https://github.com/rancher/longhorn/issues/321 , which has been shipped with v0.3.3 release.

Can you send me the manager logs, and engine/replica logs after you click "backup"?

**Comment by kc004** [comment]
@yasker I can see the backup volumes now. Actually, I was accessing longhorn using Rancher Proxy but rancher proxy doesn't redirect to the actual backup page. Now, I am accessing it using ingress and it seems working perfectly. Thanks for your support.
