### ISSUE TITLE
Defining an NFS Backup Target

### ISSUE THREAD

**Issue by paulmorabito** [rancher/longhorn#377]
What is the format for entering an NFS share as a backup target for Longhorn?

**Comment by dnauck** [comment]
In my last test i used:

```
nfs://123.123.123.123:/path/to/backup
```

Its also NFSv4 only

**Comment by yasker** [comment]
@paulmorabito 

@dnauck is right. Also, I've updated the doc for NFS backupstore at: https://github.com/rancher/longhorn/blob/master/docs/backup.md#nfs-backupstore
