### ISSUE TITLE
Scheduling and managing backups

### ISSUE THREAD

**Issue by paulmorabito** [rancher/longhorn#378]
How can I schedule a regular NFS backup and is it possible to maintain a rolling backup of last x backups according to the backup schedule defined?

**Comment by yasker** [comment]
@paulmorabito It's exactly `Recurring Backup` designed for. Check for the Volume Detail page, scroll down and you will see it.

**Comment by ainiml** [comment]
> @paulmorabito It's exactly `Recurring Backup` designed for. Check for the Volume Detail page, scroll down and you will see it.

wow this has eluded me for days.

Clicking the scheduled backups icon should bring you to this hidden section of the details

![Screenshot from 2019-12-07 04-17-32](https://user-images.githubusercontent.com/28725423/70372101-d11afa80-18a8-11ea-92cf-831265dd4208.png)

**Comment by yasker** [comment]
@ainiml yeah, that's a good idea. Can you file another issue for it?
