### ISSUE TITLE
[Feature Request] Show replica location in volume view (or mark volumes with 2+ replicas on the same host)

### ISSUE THREAD

**Issue by dnauck** [rancher/longhorn#382]
It would be helpful to see the replica locations and state in the UI list of the volumes, currently you need to click one by one to find replicas on the same host or failed replicas.

Maybe with a hover information or search/reporting, etc.

**Comment by yasker** [comment]
This one can be expressed similarly to #383 

We can put a small icon with tooltip next to **Health**, and it will show if:
1. Yellow: Compromised HA. if more than one RW replicas are scheduled on one node.
2. Red: No HA. if all the RW replicas are scheduled on one node.
3. If neither was satisfied, nothing is shown.

Also, we can add a related filter to the upper-right dropdown for this embedded field.

**Comment by yasker** [comment]
Feature merged.
