### ISSUE TITLE
[Feature Request] show engine image version in UI volume list

### ISSUE THREAD

**Issue by dnauck** [rancher/longhorn#383]
After a longhorn upgrade you need to find our which volume needs an upgrade ans has wich engine image version. Please provide some reporting for this.

**Comment by yasker** [comment]
I think it's not necessary to show the full engine image version there, but user needs to know the engine version is different from the default version (so it should be upgraded).

Put an icon similar to the upgrade icon for Longhorn manager next to the **volume name** would be helpful. 
![screen shot 2018-11-08 at 22 08 13](https://user-images.githubusercontent.com/3344618/52607345-caf3f300-2e2a-11e9-917b-180d76b4b248.png)

**Comment by yasker** [comment]
Feature merged.
