### ISSUE TITLE
longhorn-csi-plugin error on particular node

### ISSUE THREAD

**Issue by kc004** [rancher/longhorn#394]
I have two control planes and two workers in the cluster. All the deployments of longhorn-CSI-plugins are working fine except one-second master node CSI plugin.
In the longhorn-csi-plugin deployment, there are two pods one is driver-registrar and csi-plugin.
Driver registrar is giving me these logs:
<pre>
Still trying, connection is TRANSIENT_FAILURE
Still trying, connection is CONNECTING
Still trying, connection is TRANSIENT_FAILURE
Still trying, connection is TRANSIENT_FAILURE
Still trying, connection is TRANSIENT_FAILURE
Still trying, connection is TRANSIENT_FAILURE
Still trying, connection is TRANSIENT_FAILURE
Still trying, connection is TRANSIENT_FAILURE
Still trying, connection is TRANSIENT_FAILURE
Connection timed out
Calling CSI driver to discover driver name.
GRPC call: /csi.v0.Identity/GetPluginInfo
GRPC request: {}
GRPC response: {}
GRPC error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
E0219 15:50:47.039029 1 main.go:158] rpc error: code = Unavailable desc = all SubConns are in TransientFailure
</pre>

Second pod longhorn-csi-plugin which is constantly restarting and having logs like these:
<pre>
level=info msg="CSI Driver: io.rancher.longhorn csiVersion: 0.2.0"
level=fatal msg="Error starting CSI manager: Failed to initialize Longhorn API client: Get http://longhorn-backend:9500/v1: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
</pre>
If i delete the pod then for some time it working fine then throw me errors like above.

**Comment by yasker** [comment]
This log indicates that longhorn-csi-plugin cannot connect to the Longhorn manager, which should be exposed as a service at `longhorn-backend:9500`.

That failing master is a worker as well? Seems something wrong with the network setup. If you use `kubectl exec` to get into the longhorn-csi-plugin pod, can you ping `longhorn-backend`? I guess you can do that in the pod on the success nodes but would fail on this pod.

**Comment by kc004** [comment]
Yes master is worker also. Longhorn-backend is getting dns internal ip address but not able to ping by any of the available pods. 

Longhorn-manager logs for that particular node:
<pre>
time="2019-02-20T10:05:29Z" level=debug msg="Engine image rancher/longhorn-engine:v0.3.3 is ready"
time="2019-02-20T10:05:29Z" level=info msg="Listening on 10.42.1.30:9500"
time="2019-02-20T10:05:29Z" level=info msg="Start Longhorn Engine Image controller"
time="2019-02-20T10:05:29Z" level=info msg="Start Longhorn node controller"
time="2019-02-20T10:05:29Z" level=info msg="Start Longhorn websocket controller"
time="2019-02-20T10:05:29Z" level=info msg="Start Longhorn Setting controller"
time="2019-02-20T10:05:29Z" level=info msg="Start Longhorn replica controller"
time="2019-02-20T10:05:29Z" level=info msg="Start Longhorn engine controller"
time="2019-02-20T10:05:29Z" level=info msg="Start Longhorn volume controller"
time="2019-02-20T10:05:59Z" level=debug msg="Failed to check for the latest upgrade: Post https://longhorn-upgrade-responder.rancher.io/v1/checkupgrade: dial tcp: i/o timeout"
time="2019-02-20T10:08:29Z" level=debug msg="Requeue longhorn-system/ip-172-31-7-97.ap-southeast-1.compute.internal due to conflict"
</pre>

Other nodes logs:
<pre>
time="2019-02-19T15:29:59Z" level=info msg="Listening on 10.42.2.15:9500"
time="2019-02-19T15:30:35Z" level=debug msg="Requeue longhorn-system/ip-172-31-11-176.ap-southeast-1.compute.internal due to conflict"
time="2019-02-19T15:40:59Z" level=debug msg="websocket: open" id=5720062091805486083 type=settings
time="2019-02-19T15:41:00Z" level=debug msg="websocket: open" id=3982356775922476595 type=events
time="2019-02-19T15:41:02Z" level=debug msg="websocket: open" id=4069183594094656459 type=nodes
time="2019-02-19T15:41:05Z" level=debug msg="websocket: close 1006 (abnormal closure): unexpected EOF" id=4069183594094656459 type=nodes
time="2019-02-19T15:41:07Z" level=debug msg="websocket: open" id=783805898215549464 type=nodes
time="2019-02-19T15:41:08Z" level=debug msg="websocket: open" id=715945828572183189 type=volumes
time="2019-02-19T15:41:09Z" level=debug msg="websocket: close 1006 (abnormal closure): unexpected EOF" id=783805898215549464 type=nodes
time="2019-02-19T15:41:11Z" level=warning msg="HTTP handling error write tcp 10.42.2.15:9500->10.42.3.19:48100: write: broken pipe"
time="2019-02-19T15:41:11Z" level=error msg="Error in request: write tcp 10.42.2.15:9500->10.42.3.19:48100: write: broken pipe"
2019/02/19 15:41:11 http: response.WriteHeader on hijacked connection
2019/02/19 15:41:11 http: response.Write on hijacked connection
time="2019-02-19T15:41:11Z" level=error msg="Failed to write err: write tcp 10.42.2.15:9500->10.42.3.19:48100: write: broken pipe"
time="2019-02-19T15:41:19Z" level=debug msg="websocket: open" id=2312333231131831162 type=nodes
time="2019-02-19T15:41:24Z" level=debug msg="websocket: close 1006 (abnormal closure): unexpected EOF" id=715945828572183189 type=volumes
time="2019-02-19T15:41:40Z" level=debug msg="websocket: open" id=793111327246758909 type=volumes
time="2019-02-19T15:57:40Z" level=debug msg="websocket: close 1001 (going away)" id=793111327246758909 type=volumes
time="2019-02-19T15:57:40Z" level=debug msg="websocket: close 1001 (going away)" id=3982356775922476595 type=events
time="2019-02-19T15:57:40Z" level=debug msg="websocket: close 1001 (going away)" id=2312333231131831162 type=nodes
time="2019-02-19T15:57:40Z" level=debug msg="websocket: close 1001 (going away)" id=5720062091805486083 type=settings
time="2019-02-19T20:24:05Z" level=debug msg="Requeue longhorn-system/ip-172-31-11-176.ap-southeast-1.compute.internal due to conflict"
time="2019-02-20T00:15:05Z" level=debug msg="Requeue longhorn-system/ip-172-31-11-176.ap-southeast-1.compute.internal due to conflict"
</pre>

<pre>
time="2019-02-19T15:29:58Z" level=info msg="Listening on 10.42.3.18:9500"
time="2019-02-19T15:29:58Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"ip-172-31-8-84.ap-southeast-1.compute.internal\", UID:\"37371dd9-345b-11e9-b1a2-0295347eca30\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"64315\", FieldPath:\"\"}): type: 'Normal' reason: 'Ready' Node ip-172-31-8-84.ap-southeast-1.compute.internal is ready"
time="2019-02-19T15:29:58Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"ip-172-31-8-84.ap-southeast-1.compute.internal\", UID:\"37371dd9-345b-11e9-b1a2-0295347eca30\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"64315\", FieldPath:\"\"}): type: 'Normal' reason: 'Ready' Disk /var/lib/rancher/longhorn/ on node ip-172-31-8-84.ap-southeast-1.compute.internal is ready"
time="2019-02-19T15:29:58Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"ip-172-31-8-84.ap-southeast-1.compute.internal\", UID:\"37371dd9-345b-11e9-b1a2-0295347eca30\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"64315\", FieldPath:\"\"}): type: 'Normal' reason: 'Schedulable' Disk /var/lib/rancher/longhorn/ on node ip-172-31-8-84.ap-southeast-1.compute.internal is schedulable"
time="2019-02-19T15:34:58Z" level=debug msg="Requeue longhorn-system/ip-172-31-8-84.ap-southeast-1.compute.internal due to conflict"
time="2019-02-19T15:42:28Z" level=debug msg="Requeue longhorn-system/ip-172-31-8-84.ap-southeast-1.compute.internal due to conflict"
time="2019-02-19T16:56:29Z" level=debug msg="Requeue longhorn-system/ip-172-31-8-84.ap-southeast-1.compute.internal due to conflict"
</pre>

**Comment by yasker** [comment]
@kc004 Can you try `curl longhorn-backend:9500`? If it's a network issue, this should fail on the failure pod but should success on the other nodes.

E.g.
```
kubectl -n longhorn-system exec -it longhorn-csi-plugin-q4r22 -c longhorn-csi-plugin curl longhorn-backend:9500
```

**Comment by kc004** [comment]
@yasker Thanks. It was a certificate error between two masters and now it solved.

**Comment by BabyWords** [comment]
> @yasker Thanks. It was a certificate error between two masters and now it solved.

Hello，I met the same issue,could you  please specify the details how to solve this issue?

**Comment by yasker** [comment]
@BabyWords Can you describe your issue? The root cause can be different. You can also file another issue since this one is closed already. We can mark them as duplicated later if needed.
