### ISSUE TITLE
Volume restored in Longhorn doesn't show up in Kubernetes as PV

### ISSUE THREAD

**Issue by kc004** [rancher/longhorn#395]
I did restore PV from S3 backup and on Longhorn UI it created but when I see it in Rancher UI or kubectl get PV I cannot see any PV created with that name. Same as If I created PV from Rancher UI along with S3 backup URL it created PV but I cannot find it in Rancher. 

Both are working differently and my application not able to start. Using Rancher UI created PV, PV bounded with PVC but I cannot see it on nodes and longhorn UI. The same case with Longhorn, I created PV using Longhorn and it doesn't appear in kubectl get pv or Rancher PV section so my PVC not able to bound it.

**Comment by yasker** [comment]
The restored volume is a Longhorn volume. It's not a Persistent Volume in Kubernetes yet.

https://github.com/rancher/longhorn/blob/master/docs/restore_statefulset.md can help you to create a PV with an existing Longhorn volume. You can also take a look at https://www.youtube.com/watch?v=vRqvz-Ii49A&t=3328s which contains the demo on how to restore the volume to a workload.

**Comment by kc004** [comment]
@yasker Thanks I can access my restored volume data. Actually at the time of restore PV it was in attaching state for a long time so I thought it was an error in attaching a volume but actually, it was downloading data from S3 and it took 20 min to download it from S3.

**Comment by yasker** [comment]
@kc004 Thanks for the update. We will introduce the progress check for restore (#49) in the future release.
