### ISSUE TITLE
Support for DNS resolution in windows VM.

### ISSUE THREAD

**Issue by sangeethah** [rancher/longhorn#40]

**Comment by yasker** [comment]
Should be fixed by: https://github.com/rancher/vm/pull/75

**Comment by yasker** [comment]
Assign to @sangeethah for verify.

**Comment by sangeethah** [comment]
Tested with latest images - rancher/vm-ubuntu:14.04 and yasker/testimage:latest.
VM gets ip address successfully and DNS resolution works expected.
