### ISSUE TITLE
If add replica process dies, replica stays in WO mode and sync never resumes

### ISSUE THREAD

**Issue by cjellick** [rancher/longhorn#41]
Steps to reproduce (theoretical):

1. Get a healthy volume going
1. Write a decent amount of data so that adding a replica will take a little while (while it copies data from good replica to new replica.
1. While the new replica is being added, stop the sync-agent.

At this point, the replica has been added to the controller but is in WO (write only) mode but the rebuild failed and will never be completed.

The fix that I've added cleans up after a failed rebuild. It removes the replica from the controller so that on the next sync, it can be re-added properly.

**Comment by cjellick** [comment]
The fix I'm adding allows for retry of replicas that failed to build. But, I should probably also add a check that waits for the the sync agent to be online before attempting to add. I think the root cause when I saw this in the wild was the fact that the sync agent hadnt yet come online.

**Comment by sangeethah** [comment]
@cjellick , I tried the following steps multiple times and I am not able to reproduce the issue where replica is stuck in "WO" mode when testing with image - 

1. Have a ROOT volume with ~500M data.
2. Delete the replica container.
3.Wait for the new replica container to start.
4.Delete/stop the sync agent sidekick container of this replica.

I see the controller reporting the newly created replica in "WO" mode for sometime (like ~20 - 25 secs), after which it becomes "RW" mode.

<img width="670" alt="screen shot 2016-05-06 at 3 03 26 pm" src="https://cloud.githubusercontent.com/assets/4266958/15087255/1f9d3ff8-139c-11e6-8c98-e3f1fbaa48e7.png">

Are the steps I am following the right way to reproduce the issue?
