### ISSUE TITLE
Download support bundle may cause 504 gateway timeout if it took too long

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#414]
Need a better experience.

**Comment by dnauck** [comment]
Maybe a two phase method:

1.) user clicks the download bundle button
2.) longhorn notifiy the user that it now starts to collect a required information and when it finishes it will notifiy the user again that the bundle is read for download

**Comment by yasker** [comment]
As a workaround before the fix, the user should able to find a zip named like "longhorn-support-bundle_xxxx.zip` inside one of manager pods' `/tmp/` directory. The user can use `kubectl cp` to copy that file out.

**Comment by yasker** [comment]
This can be done by introducing three new APIs.

1. POST `/supportbundle/, and it should be called with `nodeId` set so we can route the request to one of the longhorn manager. Other options would include description and issue URL etc. API server will return a bundleID which client can use to check if the supportbundle is ready or not.
2. GET `/supportbundle/<bundleId>`, providing bundleId and nodeId as parameter, API server should route the request to the manager specified by the nodeId then answer with if the bundle is ready for download or not
3. GET `/supportbundle/<bundleId>?action=download` should allow user to download the support bundle.

**Comment by yasker** [comment]
Backend merged.

**Comment by yasker** [comment]
@shreesha21 Can you provide an API example here?

**Comment by shreesha21** [comment]
API examples for 3 requests and the responses:

**Support Bundle Initiate Request:** 
```curl -X POST http://165.22.149.199:32318/v1/supportbundles```

**Response:** 
```{"actions":{},"errorMessage":"","id":"srao3","links":{"self":"http://165.22.149.199:32318/v1/supportbundles/srao3"},"name":"longhorn-support-bundle_40981e85-7203-11e9-b075-a2aeebaaea88_2019-05-09T02-38-29Z.zip","nodeID":"srao3","state":"InProgress","type":"supportbundle"}```

**Support Bundle Query Request:** 
```curl -X GET -H "Content-type: application/json" -H "Accept: application/json" -d '{"name":"longhorn-support-bundle_40981e85-7203-11e9-b075-a2aeebaaea88_2019-05-09T02-38-29Z.zip"}' "http://165.22.149.199:32318/v1/supportbundles/srao3"```

**Response:**
```{"actions":{},"errorMessage":"","id":"srao3","links":{"self":"http://165.22.149.199:32318/v1/supportbundles/srao3"},"name":"longhorn-support-bundle_40981e85-7203-11e9-b075-a2aeebaaea88_2019-05-09T02-38-29Z.zip","nodeID":"srao3","state":"ReadyForDownload","type":"supportbundle"}```

**Support Bundle Download Request:**
```curl -X POST http://165.22.149.199:32318/v1/supportbundles/srao3?action=download --data '{"name":"longhorn-support-bundle_40981e85-7203-11e9-b075-a2aeebaaea88_2019-05-09T02-38-29Z.zip"}'```

**Response:**
```**_Zip file_**```
