### ISSUE TITLE
Adding a replica fails if the replica previously failed a rebuild

### ISSUE THREAD

**Issue by cjellick** [rancher/longhorn#42]
This is tricky to reproduce without having breakpoints in cattle. The symptoms are actually difficult to catch as well. The replica looks healthy, but if you exec into the controller and do a `longhorn ls`, you'll see that the good replica's snapshot grows and grows.

The cause of this is that once the initial rebuild fails, the replica ends up in a state of closed=true and rebuilding=true. When it is added the next time, that combination of states is considered invalid for performing a snapshot and the `longhorn add` fails.

My steps to reproudce:
1. Prevent the sync agent container from starting right away. I can do this by putting a break point in InstancePreStart that only triggers if the name of the instance contains sync
2. delete a replica and its sidekicks
3. exec into controller. do longhorn ls. you'll see a replica in WO mode. delete that replica from the controller with `longhorn rm <replica address>`

Controller agent will continually try to add the replca but the `longhorn add <replica>` command will always fail.

**Comment by cjellick** [comment]
The fix I'm adding allows for retry of replicas that failed to build. But, I should probably also add a check that waits for the the sync agent to be online before attempting to add. I _think_ the root cause when I saw this in the wild was the fact that the sync agent hadnt yet come online.

**Comment by cjellick** [comment]
@sangeethah To repro, in leui of having a break point in cattle, you try write a decent amount of data to the volume before removing a replica so that the add replica takes awhile and then stop/kill the sync agent container

**Comment by sangeethah** [comment]
@cjellick: tested with image - cjellick/longhorn:dev4 , to see if this issue reproduces.

1. Have a ROOT volume with ~500M data.
2. Delete the replica container. 
3. I see the controller reporting the newly created replica in "WO" mode.
4. From controller  container , do longhorn rm <replica address>

Controller is never sees the replica getting recreated again .
I see the following exception in controller log constantly:

```
16 3:17:14 PM::1 - - [06/May/2016:22:17:14 +0000] "GET /v1/replicas HTTP/1.1" 200 377
5/6/2016 3:17:14 PM::1 - - [06/May/2016:22:17:14 +0000] "GET /v1/volumes HTTP/1.1" 200 540
5/6/2016 3:17:14 PMtime="2016-05-06T22:17:14Z" level=info msg="Connecting to remote: 10.42.39.163:9502"
5/6/2016 3:17:14 PMtime="2016-05-06T22:17:14Z" level=info msg="Opening: 10.42.39.163:9502"
5/6/2016 3:17:14 PMtime="2016-05-06T22:17:14Z" level=info msg="Snapshot: 10.42.134.46:9502 b5a603bf-4d31-4969-a407-a5e54ca0df1c"
5/6/2016 3:17:14 PMtime="2016-05-06T22:17:14Z" level=info msg="Snapshot: 10.42.39.163:9502 b5a603bf-4d31-4969-a407-a5e54ca0df1c"
5/6/2016 3:17:14 PMtime="2016-05-06T22:17:14Z" level=info msg="Closing: 10.42.39.163:9502"
5/6/2016 3:17:14 PMtime="2016-05-06T22:17:14Z" level=error msg="Error in request: Bad status: 404 404 Not Found"
5/6/2016 3:17:14 PM::1 - - [06/May/2016:22:17:14 +0000] "POST /v1/replicas HTTP/1.1" 500 172
```

<img width="748" alt="screen shot 2016-05-06 at 3 19 43 pm" src="https://cloud.githubusercontent.com/assets/4266958/15087501/090c6226-139e-11e6-95f2-3797cfd17b1a.png">

**Comment by sangeethah** [comment]
@cjellick: tested with image - cjellick/longhorn:dev5 ,  when replica process  in "WO" mode is killed from within the controller , new replica gets added successfully and gets from "WO"  to "RW" mode eventually.
 
Following are the steps that were done to verify the fix:

Have a ROOT volume with ~500M data.
Delete the replica container ( this ends up deleting the side kick containers as well).
New replica containers get created.
I see the controller reporting the newly created replica in "WO" mode.
From controller container , do longhorn rm < address> when replica is still in "WO" mode.
After few seconds , a new replica is seen  when execution longhorn ls. This replica gets from "WO"  to "RW" mode eventually.
