### ISSUE TITLE
driver: k3s data-dir detection would fail if the command line has prefix e.g. `/usr/local/bin/k3s`

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#449]
PR in progress:
https://github.com/rancher/longhorn-manager/pull/246

Thanks to @aaliddell for spotting this issue!
https://github.com/rancher/longhorn-manager/pull/242#issuecomment-476852524

**Comment by yasker** [comment]
rancher/longhorn-manager#246 merged.

**Comment by meldafrawi** [comment]
**Test steps**

- create k3s server using `/usr/local/bin/k3s --debug  server --bind-address K3S_SERVER_ADDRESS`
- create 2 k3s agents using `/usr/local/bin/k3s --debug  agent --server https://K3S_SERVER_ADDRESS:6443  --token  K3S_SERVER_TOKEN` 
- install Longhorn (latest)   https://github.com/rancher/longhorn-manager/commit/43b34366ada0ee04fe87dcc9e5e7e46c5b176e1b
 - create a storage class
 - create a pod using Longhorn volume

**Result:** 
I was able to create 3 node k3s cluster, deploy Longhorn, and create a pod using Longhorn volume, access Longhorn UI,  without any issues.
