### ISSUE TITLE
chart: kubelet root-dir is not configurable in the chart

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#451]
Like `flexvolume-dir`, `kubelet root-dir` should be a configurable parameter, in case the auto detection failed.

**Comment by meldafrawi** [comment]
Test Steps: 
- change `kubeletRootDir` value in helm chart `values.yml` 
- install longhorn using helm CLI
- check `longhorn-csi-plugin` for `spec.volumes.hostPath` , it's value reflected the change.
