### ISSUE TITLE
Log Level adjustment

### ISSUE THREAD

**Issue by KuroObi** [rancher/longhorn#454]
We've been running longhorn for a while now and recently added the node-problem-detector to our clusters and now the longhorn-manager log gets and abundance of the following log-messages:
`level=debug msg="Unknown condition of kubernetes node xxxx: condition type is KernelDeadlock, reason is KernelHasNoDeadlock, message is kernel has no deadlock"

level=debug msg="Unknown condition of kubernetes node xxxx: condition type is ReadonlyFilesystem, reason is FilesystemIsNotReadOnly, message is Filesystem is not read-only"`

Is there a way to set the loglevel to warn or even to use the node-problem-detector node annotations to react to states like read-only fs.

**Comment by yasker** [comment]
@KuroObi 

You can disable debug mode by removing `-d` from the manager command line, though it would likely require a restart of the pods.

But it's hard to know what you don't know. And we don't want to flood debug log with useless information. I've skimmed the design doc for node-problem-detector, it seems all the conditions will become an issue only if `condition.Status==true`. I think we can use this to filter the node conditions worth logging. We will fix the log for the next release.

**Comment by yasker** [comment]
Fix merged.
