### ISSUE TITLE
UI: Upgrade dependency to newer versions

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#457]
There are many warnings about deprecated package during Longhorn UI build:

```
---> Running in 178bd9f58e10
npm WARN deprecated rc-radio@2.0.1: rc-radio is deprecated, please use rc-checkbox instead.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated core-js@2.5.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
```

Also, need to check UI against vulnerability scanner.

**Comment by meldafrawi** [comment]
**[WIP] Features to be tested:** 
- Dashboard
- Node
  - [ ] As UI user, i was able to list/sort all nodes details.
  -  [ ] As UI user, i was able to disable scheduling on a node.
  -  [ ] As UI user, i was able to filter nodes, using Name or Status (Schedulable, Unschedulable, Disabled, Down).
  - [ ] As UI user, i was able to add disk to node.
  - [ ] As UI user, i was able to enable/Disable Scheduling on a disk in a node.
  - [ ] As UI user, i was able to enable/disable scheduling on a node.
  - [ ] As UI user, i was able to Expand/Collapse nodes with all their disks.

- Volume
  - [ ] As UI user, i was able to create a volume
  - [ ] As UI user, i was able to create a PV
  - [ ] As UI user, i was able to create a PVC to an existing volume in default/user created namespace.
  - [ ] As UI user, i was able to create a backup from volume.
  - [ ] As UI user, i was able to attach/detach  a volume.

- Backup
     - [ ] As UI user, i was able to list/sort all volumes backup list.
- Settings
  - General:
    - [ ] As UI user, i was able to configure backup target with backup target credentials
    - [ ] As UI user, i was able to configure Recurring Snapshot and Backup Schedule
    - [ ] As UI user, i was able to configure Storage Over Provisioning Percentage

  - Engine Image:

**Comment by yasker** [comment]
Reopen to track for merging the code.

**Comment by yasker** [comment]
Merged. Please file new bugs in the new issues.
