### ISSUE TITLE
manager: Add last backup field to volume

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#459]
It would be very informative if users can know when is the last time this volume backed up.

Brief design:
Volume's last backup field will be updated when a backup was done, along with the timestamp. It should update as the last backup indicates in the backup store for the volume, instead of setting the field to be the backup that just completed. The source of truth should be the backup store.

**Comment by yasker** [comment]
Related to https://github.com/rancher/longhorn/issues/83

**Comment by yasker** [comment]
The backend change is not ready yet.

**Comment by yasker** [comment]
Backend change merged.

**Comment by yasker** [comment]
Done.

**Comment by meldafrawi** [comment]
It would be more clear to add **Last Backup At** field along with **Created At** field so users can know when is the last time this volume backed up.

![Screenshot from 2019-04-26 21-01-57](https://user-images.githubusercontent.com/18232258/56831351-1b46f280-6869-11e9-8828-45a906d2e2cf.png)

**Comment by yasker** [comment]
@smallteeths Can you look into this? ^^

**Comment by meldafrawi** [comment]
- [ ] Add `Last Backup At` field
