### ISSUE TITLE
manager: better kubernetes integration

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#461]
Currently, users don't know the relationship between Longhorn volume and Kubernetes workload, so it's hard for the user to operates on a volume while knowing what's the potential impact would be. It's important for the user to know which workload is using the volume, so when a volume needs to be performed maintenance or need to be backup/restored, the user can know exactly what data they're working with.

The feature contains:
1. The ability to identify the Workload and Namespace is using Longhorn volume.
2. Ability to create PV and PVC directly from Longhorn volume, which also makes it easier for the user to use restored volume for Kubernetes.
3. Speed up the recovery from node failure. The current Kubernetes failover cases will take an extra six minutes after pod deleted to get VolumeAttachment deleted. Longhorn should detect the deletion of the Pod and delete the correlated VolumeAttachment sooner than six minutes.

Original issue:
https://github.com/rancher/longhorn/issues/82

**Comment by yasker** [comment]
UI details:
Feature 1: workload display
1. Remove Frontend and Endpoint from volume list.
2. Add Workload name, pod name, namespace to the list. Workload and pod name show as `workload/pod`.
3. Add PV and PVC in the list. Show the name and status as a tooltip for the icon.
4. In volume details, add all the information from volume.status.kubernetesStatus.

Feature 2: create pv/pvc by volume
Add new actions to volume. `Create PV` and `Create PVC`. Create PVC provides an option to choose the namespace.

**Comment by yasker** [comment]
First feature backend part has been merged in. See volume.status.kubernetesStatus

**Comment by yasker** [comment]
Done.

**Comment by meldafrawi** [comment]
**Testing list:**

_Feature 1: workload display_

- [ ] Remove Frontend and Endpoint from volume list. 
- [ ] Add Workload name, pod name, namespace to the list. Workload and pod name show as workload/pod.
- [ ] Add PV and PVC in the list. Show the name and status as a tooltip for the icon.

- [ ] In volume details, add all the information from volume.status.kubernetesStatus.

_Feature 2: create pv/pvc by volume_

- [ ] Add new actions to volume. Create PV and Create PVC.

**Comment by meldafrawi** [comment]
It would be much easier for the user if workload/pod **namespace** exist in the volume list level, with sort and filtering.

**Comment by yasker** [comment]
@meldafrawi Agreed.

@smallteeths Can we add `Namespace` between `PV/PVC` and `Pod`? And add sorting for it too.

**Comment by meldafrawi** [comment]
- [ ] Add Namespace between PV/PVC and Pod.

**Comment by meldafrawi** [comment]
`Last Backup At` trimmed, need to be adjusted.

![Screenshot from 2019-04-30 21-31-17](https://user-images.githubusercontent.com/18232258/56988094-7fcac000-6b8f-11e9-9643-15600e06c990.png)


I can't find `namespace` the filter list.
![Screenshot from 2019-04-30 21-37-25](https://user-images.githubusercontent.com/18232258/56988408-3f1f7680-6b90-11e9-9e12-54fceec975c9.png)

**Comment by meldafrawi** [comment]
@smallteeths, Can you please check this ^ ?
