### ISSUE TITLE
uninstaller: add ability to cleanup leftover resources with finalizers when longhorn uninstall stuck

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#462]
Wrongly uninstall Longhorn shouldn't require user to remove finalizers manually.

**Comment by yasker** [comment]
The stuck situation be simulated by `kubectl delete ns longhorn-system` or `kubectl delete -f deploy/longhorn.yaml`

See also https://forums.rancher.com/t/longhorn-system-stuck-terminating/13690

**Comment by yasker** [comment]
Remember to update the doc for v0.5.0

**Comment by yasker** [comment]
@shuo-wu Have you updated the doc yet?

**Comment by shuo-wu** [comment]
You mean Longhorn doc? Not yet

**Comment by meldafrawi** [comment]
**Test steps**

_Install steps:_
- install Longhorn (latest)   https://github.com/rancher/longhorn-manager/commit/43b34366ada0ee04fe87dcc9e5e7e46c5b176e1b
 - create a storage class
 - create a pod using Longhorn volume

 _Uninstall steps:_
- delete the pod
- delete the storage class
- delete Longhorn, and get stuck, pressing Ctrl + c
-  create Longhorn uninstall jobs
- create Longhorn uninstall jobs
 
_Check step:_
- Ensure longhorn components are removed along with longhorn-system namespace.

**Result:** 
Longhorn components are removed along with uninstall jobs and longhorn-system namespace
