### ISSUE TITLE
engine: block device permission is not consistent with native block devices

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#463]
e.g. 

directories:
drwxr-xr-x  2 root root         580 Apr  5 11:01 block/
drwx------  2 root root          60 Apr  4 23:53 longhorn/

block devs:
brw-rw----  1 root disk      8,   0 Mar 25 18:58 sda
brw------- 1 root root 8, 16 Apr  4 00:30 /dev/longhorn/test

We should make the permissions consistent with native ones.

Raised by https://forums.rancher.com/t/systemd-complaining-still-working-fine/13860 , systemd complains, though volume still works fine.

**Comment by yasker** [comment]
https://github.com/rancher/longhorn-engine/pull/350 merged

**Comment by meldafrawi** [comment]
**Longhorn Engine Version:**  cb070da
- [x] Block Devices created with 0660 permissions
