### ISSUE TITLE
Error: Failed to mkdir /lib-modules: mkdir /lib-modules: read-only file system

### ISSUE THREAD

**Issue by xXTim97Xx** [rancher/longhorn#474]
I'm getting a "CrashLoopBackOff" on the Longhorn-csi-plugin pod with kubic-os and an on premise Kubernetes Cluster.

The error shows me: "Error: Failed to mkdir /lib-modules: mkdir /lib-modules: read-only file system"

Maybe this is because kubic uses a read-only file system. 
How to solve that problem?

**Comment by yasker** [comment]
It looks like the directory specified by CSI plugin pod here is wrong. It shouldn't need to create a new directory. Looks like should be `/lib/modules` instead of `/lib-modules`.

We will fix this in the next release.

**Comment by yasker** [comment]
Closed by mistake. That commit should refer to #464

**Comment by yasker** [comment]
https://github.com/rancher/longhorn-manager/pull/267 merged.
