### ISSUE TITLE
Automatic Provisioning of Persistent Volumes (CSI)

### ISSUE THREAD

**Issue by benosman** [rancher/longhorn#475]
Hello,

I'm testing out Longhorn for my cluster, and one minor niggle I have with it is that in the UI it shows only the guid of the volume, not the label of the claim. 

I read in #82 that it may not be possible to retrieve that information from the storage driver.

So, I was looking at ways of getting the volume names to be manually set rather than the auto generated guid.

Since I'm using Kubernetes 1.13, I'm using the CSI driver, I followed the example in the manifests here:
https://github.com/rancher/longhorn/blob/master/examples/csi/example_pv.yaml

However, they only seem to work when the volume has already been created in the UI. The CSI driver does not provision the volume. Since I'm automating the creation of these volumes, I'd like a way to auto provision without using the UI.

I understand the flexvolume driver may do this, but since that is going to be deprecated, it doesn't seem a good idea to switch. 

Is there any other way I'm missing for me to manually specify the persistent volume name and still retain automatic provisioning?

**Comment by yasker** [comment]
Though it's impossible to control what the PV name is when Kubernetes decide to provision it, we're going to address #82 by implementing #461 in the next release, so users would be able to see the workload using Longhorn volume in the Longhorn UI. Hope this will address your issue as well.

**Comment by benosman** [comment]
Great, those changes would certainly go a long way to easing this issue for me!

Closing this issue then, and I will keep an eye on 461.

**Comment by jiridanek** [comment]
https://longhorn.io/docs/1.5.1/concepts/#dynamic-storage-provisioning

> Longhorn introduces a Longhorn StorageClass so that your Kubernetes workloads can carve out pieces of your persistent storage as necessary.

```
$ kubectl get storageclass --all-namespaces
NAME                 PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
longhorn (default)   driver.longhorn.io   Delete          Immediate              true                   13h
```

Notice it defines three replicas, so if you don't have three nodes (yet), find a node or two so this works ;P

```
$ kubectl describe storageclass/longhorn
Name:            longhorn
IsDefaultClass:  Yes
Annotations:     longhorn.io/last-applied-configmap=kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Delete"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
```
