### ISSUE TITLE
manager: support bundle improvements

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#480]
- [x] Allow user to add comment in the support bundle.It will help to understand and keep track of the problem
- [x] Add `snapshot info` in the support bundle if the engine is up and running.

**Comment by dnauck** [comment]
Year, maybe also a Github Issue id ;)

**Comment by yasker** [comment]
@shreesha21  Two fields can be added to the metadata.yaml, `issueURL` and `description`.

**Comment by yasker** [comment]
Let's create a new directory in the support bundle, called `volumes`.

So the snapshot information can be stored at:

`volumes/<volumename>/snapshots.json`

**Comment by yasker** [comment]
Backend merged

**Comment by meldafrawi** [comment]
**Longhorn Version:** 0.5.0-rc1

- was able to add `issue URL` and `Description` to support bundle, data is exist in `metadata.yaml`
- was able to verify snapshot information in support bundle
  - yamls/volumes/<volumename>/snapshots.yaml
  - yamls/volumes/<volumename>/generationError.log
