### ISSUE TITLE
Make StorageClass and ReplicaCount configurable in Helm Charts

### ISSUE THREAD

**Issue by gabrielcalderon** [rancher/longhorn#486]
When installing Longhorn from Rancher's UI there's no way to configure how many replicas are created. This results in single node systems having 3 replicas for each volume, and 3 pods for the drivers/provisioner. 

Would it make sense to have this value be configurable ?

**Comment by yasker** [comment]
@gabrielcalderon Yeah, we will add the option to configure `numberOfReplicas` for the default storage class `longhorn` in the next release.

**Comment by gabrielcalderon** [comment]
Great to hear! 👍
