### ISSUE TITLE
manager: engine image ownership didn't transfer when the owner node is down

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#489]
If an engine image's owner node is down, the controller should assign a new owner. Otherwise, the engine image status won't be updated.

It won't be a problem for new engines, but the status of old engines can be stuck in `deploying`.

**Comment by meldafrawi** [comment]
**Longhorn Version:** 0.5.0-rc2

Steps to reproduce:
- check engine image owner ID.
- power off the owner ID node
- check engine image owner ID, and ensure that is is in running state.
