### ISSUE TITLE
UI: Volume overview page improvement

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#490]
- [x] Change `Schedule` to `Backup Schedule`, seems better to be two lines.
- [x] Remove the wording `Click for details` for `Workload/Pod` and `Schedule` tooltips. I noticed the mouse pointer will turn into a hand sign, which should be enough to tell the user it's clickable. Keep the `Last time used:` tooltip for `Workload/Pod`.
- [x] In `Workload/Pod`, don't show `Pod Status` if `Last Pod Ref at` was set, since it doesn't make sense to show the pod status in the past.
- [x] In `Backup Schedule` column, add tooltip according to the icon color: `No recurring backup scheduled` for grey; `Only recurring snapshot scheduled` for yellow, `Recurring backup scheduled` for blue. 
- [x] For `Create PV/PVC` in the volume dropdown, don't allow edit for PV name if there is existing PV associated with the volume (grey out the PV name textbox). Don't allow edit PVC related options if there is already a PVC associated with the volume (automatic fill and grey out the create PVC checkbox, PVC name, and namespace).
- [x] Volume list page doesn't refresh `Backup Schedule` if the recurring schedule was added then removed. A manual refresh also doesn't work.

**Comment by yasker** [comment]
Done

**Comment by ainiml** [comment]
Where is the `Backup Schedule` option?
