### ISSUE TITLE
K3S - Can't access Longhorn UI through Rancher due to timeouts

### ISSUE THREAD

**Issue by vitobotta** [rancher/longhorn#493]
I have set up a K3S cluster, imported it into Rancher, and installed Longhorn. Install went OK but I can't access the UI through Rancher by clicking on the relevant link in the Apps page, due to timeouts:

```
Error: 'dial tcp 10.42.2.4:8000: i/o timeout'
Trying to reach: 'http://10.42.2.4:8000/'
```

I can access the UI with an ingress, but that's unauthenticated so I would prefer access it through Rancher. Any idea on why it is timing out? Thanks!

**Comment by yasker** [comment]
@guangbochen Is there anything we can check for Rancher proxy?

**Comment by vitobotta** [comment]
Thanks @yasker , I hope I can get it to work with K3S :)

**Comment by vitobotta** [comment]
Just to add that I had the same problem with Nodeport access with another cluster but I had forgotten to install an ingress (Since I installed K3S with Traefik disabled). In another cluster with Nginx ingress I can access the UI with a Nodeport, not sure if it's related. I still can't access the UI with the Rancher proxy on this new cluster though.

**Comment by guangbochen** [comment]
The generated URL `http://10.42.2.4:8000/` is not a proper proxy URL, can you please run `kubectl cluster-info` to check if the proxy URL is generated correctly of the Longhorn UI, for example, the default the CoreDNS proxy URL would be something like: `https://YOUR_ID_ADDRESS/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy`

**Comment by vitobotta** [comment]
Hi @guangbochen , that is not the URL I use to access the UI. I access the UI from a URL on the Rancher app, but when it times out I see that error message in the page.

**Comment by guangbochen** [comment]
yes, but even from the rancher UI the correct url address should be a system-proxy address, so we need double check if the proxy url has been generated in the k8s cluster or it is a UI display and linking bug, thanks.

**Comment by vitobotta** [comment]
Update: it's not just the Rancher proxy that is timing out; I guess this is based on the same way the `kubectl proxy` command works because if I try to open something else with that command I also get the timeout. See https://github.com/rancher/k3s/issues/418

**Comment by vitobotta** [comment]
Closing, since it's not related to Longhorn. When K3S server is started with `--disable-agent`, the server can't communicate with the services on the workers and therefore the proxy can't either. See https://github.com/rancher/k3s/issues/418
