### ISSUE TITLE
feature: incremental restoration for disaster recovery

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#495]
## Goal

To ensure DR on another datacenter works well, we're planning to have a standby volume in the recovery region, receiving incremental backup from the backup store, and ready to be deployed.

It's easier than putting an async replication across the data center.

Also, it will require a mode for the engine to not enable frontend, but allow the command to restore the backups in an incremental way.

## User experience
1. Select BackupVolume page
2. In the BackupVolume page, select `Create Disaster Recovery Volume`, and specify how many replicas and frontend as usual.
3. The volume would be created. The user needs to attach it. After it was attached, the frontend won't be enabled. The volume is now in standby mode.
4. Longhorn manager will poll backup store for certain backup volume every a few minutes. If the latest backup hasn't been restored into the volume, the manager will initiate the restoration process.
   4.1. There would be only one restoration process per volume at any given time.
5. At any given time, the user can decide to "activate" the volume. Then the volume will finish any on-going restoration, detach automatically, then change its state to a normal volume. Then the user can use it for any workload in this cluster.
    5.1. Check for the latest backup for one last time before activation would be done automatically.
    ~~5.2. Users can also ask stand-by volume to check the latest backup manually~~

**Comment by yasker** [comment]
Backend merged.

**Comment by yasker** [comment]
UI part:
1. Add a dropdown in the BackupVolume page (not backup page), which enables the user to create a standby volume using the latest backup from this backup volume. User will need to input the volume name, replica size etc like restoring from a backup.
2. We need to show one more icon next to the volume state, indicates it's a standby volume instead of a normal volume. User needs to manually attach the volume to a node for it to start monitoring the backup store and automatically restore the latest backup for the volume. After the standby volume was attached, there will be no frontend and the user cannot access it.
3. One more action will be enabled for standby volume once it's attached. It's called `activate`. It transforms the standby volume into a normal volume and automatically detaches it. Then the user can use it like a normal volume.

**Comment by yasker** [comment]
@shuo-wu can you provide a few API examples for the above actions/status?

**Comment by shuo-wu** [comment]
Standby volume creation is similar to normal volume creation but with some specific input fields requirements:
  1. Boolean field `standby` should be true.
  2. String field `fromBackup` should be set with a valid backup url.
  3. String field `frontend` should be empty.

Standby volume starts to do restoration only after it is attached to one node.

If a volume is standby volume, the following actions are disallowed:
  1. Create/Revert/Delete snapshot
  2. Create backup
  3. Create PVC/PV

Using volume `activate` action to change standby volume to a normal volume:
  1. Input:
    1. String field `frontend` should be set. `"blockdev"` or `"iscsi"`
  2. Status
    1. Make sure `standby` field is true.
    2. Make sure volume["controllers"][0]["lastRestoredBackup"] == volume["lastBackup"]

After activating volume, volume should be `detaching` or `detached` state.
