### ISSUE TITLE
K3S - Volumes stuck at "Creating" but not always

### ISSUE THREAD

**Issue by vitobotta** [rancher/longhorn#499]
This is a follow up to the conversation on Slack. 

I am having an issue with Longhorn in a K3S cluster, where volumes provisioned with PVCs sometimes are created and attached without problems, while sometimes they get stuck at the "Creating" phase. I have the same happening regardless of whether I configure Longhorn to use the CSI driver or the Flexvolume one. 

Thanks in advance for looking into it!

**Comment by yasker** [comment]
Does the thing happen if you're using UI to create a volume directly? Maybe a race condition so you may want to try multiple times.

**Comment by vitobotta** [comment]
When I create volumes directly from the UI instead of with a PVC, the volumes are created instantly and I can then attach them to nodes without problems.

**Comment by yasker** [comment]
Found this line in the log
```
time="2019-04-25T13:27:44Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-e76e3db1-675d-11e9-88ee-96000024bffe out of the queue: fail to sync longhorn-system/pvc-e76e3db1-675d-11e9-88ee-96000024bffe: BUG: multiple engines when volume is detached"
```

I suspect it's similar to https://github.com/rancher/longhorn/issues/133. There is a rare race condition between creating an engine and get the engine information due to how Kubernetes indexer works. So we've created the engine object twice, result in later we found an unexpected engine exists with this error.

We haven't seen this in Kubernetes setup yet. But since K3s is using sqlite instead of etcd in the backend, probably that changed some conditions so you would see this issue show up.

Sadly there is no easy workaround for this now. We will workaround or fix this in the next release.

**Comment by yasker** [comment]
@vitobotta Can you share your environment setup so we can try to reproduce it?

**Comment by vitobotta** [comment]
@yasker It's a test K3S cluster with a master (1 core, 2 GB of ram) and three workers (2 cores, 8 GB of ram). Any other info I can provide? Thanks!

**Comment by yasker** [comment]
@vitobotta which version of k3s?

**Comment by vitobotta** [comment]
v1.14.1-k3s.4

**Comment by yasker** [comment]
So K3s v0.4.0, got it.

**Comment by vitobotta** [comment]
As a followup to our conversation on Slack, and for reference, I wanted to update the issue just in case somebody else plays with Longhorn on K3S as well :) 

So it is confirmed that the problem with volumes sometimes stuck at "Creating" is indeed due to two engines being created for those volumes for the reason explained above by @yasker.

As suggested on Slack, when the problem occurs I find with `kubectl -n longhorn-system get lhe` the pvcs which have two engines, and delete one engine with `kubectl -n longhorn-system delete lhe <engine_name>`. If I do this, volumes pass from the Creating phase to Detached and then Attached and things work as expected. This way I managed to deploy a few test apps including Percona XtraDB Cluster which I couldn't before because of this problem.

While waiting for the 0.5.0 release which will include the fix, and for fun, I came up with a one liner that finds and removes the duplicate engines when they occur, so I put this one liner in my zshrc and I just run `longhorn-fix` to fix the volumes stuck at Creating in one shot :D I'm bad with bash so I guess it can be simplified but like I said it was also for fun 📦 

```
alias longhorn-fix="grep -Ff <(kubectl -n longhorn-system get lhe | tail -n +2 | cut -d '-' -f -6 | uniq -d | sort) <(kubectl -n longhorn-system get lhe | sort) | sed -n 'p;n' | cut -d ' ' -f 1 | xargs -L1 kubectl -n longhorn-system delete lhe"
```
I'm going to close this as the fix will be included in the 0.5.0 as confirmed by yasker.

@yasker  Thanks a lot!

**Comment by yasker** [comment]
Thanks @vitobotta !

Btw, I've reopened the bug to track the effort to fix it in v0.5.0.

**Comment by vitobotta** [comment]
Wonderful, thanks!

**Comment by vitobotta** [comment]
@yasker I have noticed that when I apply the workaround it takes a while for the pod to attempt attaching the volume again after it failed the first time. How long does it take for the attaching to be attempted again?

**Comment by yasker** [comment]
It sounds like the exponential backoff in Kubernetes, which is described here: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy
