### ISSUE TITLE
Container Storage Interface (CSI) support

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#50]
CSI became beta in v1.10, we should start working on supporting it.

**Comment by errorsandwarnings** [comment]
@yasker 

In CSI only file volumes are supported. I think longhorn is a block volume interface. Correct ?

[Read Here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/container-storage-interface.md#third-party-csi-volume-drivers)
> 
> What are the limitations of alpha?
> The alpha implementation of CSI has the following limitations:
> The credential fields in CreateVolume, NodePublishVolume, and ControllerPublishVolume calls are not supported.
> Block volumes are not supported; only file.
> Specifying filesystems is not supported, and defaults to ext4.
> CSI drivers must be deployed with the provided “external-attacher,” even if they don’t implement “ControllerPublishVolume”.
> Kubernetes scheduler topology awareness is not supported for CSI volumes: in short, sharing information about where a volume is provisioned (zone, regions, etc.) to allow k8s scheduler to make smarter scheduling decisions.
>

**Comment by yasker** [comment]
A block storage can be easily presented as a file system by formatting it. But a file system cannot be present as a block storage.

**Comment by yasker** [comment]
Majority of the support is in with https://github.com/rancher/longhorn-manager/pull/68

Pending on https://github.com/rancher/longhorn/issues/106

**Comment by yasker** [comment]
Done.
