### ISSUE TITLE
Snapshot issue after restoring from backup

### ISSUE THREAD

**Issue by courcelm** [rancher/longhorn#503]
I restored a few volumes from backup and it's not able to take any snapshot. I get the following error from UI pop up:

fail to list snapshot: cannot get client for volume matomo-backup-1: cannot get engine client with image rancher/longhorn-engine:v0.4.1: engine image ei-6e2b0e32 (rancher/longhorn-engine:v0.4.1) is not ready, it's deploying

UI engine pods status is green.

**Comment by courcelm** [comment]
Not sure if backup restoration is the problem. New volume also have this issue.

**Comment by yasker** [comment]
Is there anything recently changed with the cluster nodes? Image may become unready when something for the node changed. We've found a bug #489 recently.

**Comment by courcelm** [comment]
I was restoring backup and loading apps. Not sure about the above issue. I flushed the manager and it fixed my problem.
