### ISSUE TITLE
i have two questions about longhorn?

### ISSUE THREAD

**Issue by stoneLee81** [rancher/longhorn#506]
1 I use longhorn class to create a volume, and add volume, then start the service, in this service  I can find the volume. IF I create some files in the volume, and last delete this volume, the data i created before exists?

2 Is it possible to increase/decrease the existing volume of longhorn size?

**Comment by yasker** [comment]
Hi @stoneLee81 

1. There are a few different cases here:
    1.1. If by volume you meant the Longhorn volume, then no. The data stored in the volume would be gone if the Longhorn volume has been deleted. However, you can backup the volume using Longhorn built-in backup mechanism, so later you can restore to the volume back to the cluster from the backup store.
    1.2 If you meant Kubernetes PV, it depends what's the Reclaim policy of PV. If it's `Retain`, the PV (and Longhorn volume) won't be deleted, so it can be reused with another PVC; if it's `Delete`, the PV will be deleted along with Longhorn volume, which is the same as in 1.1. You can see details here: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming
2. Volume resizing hasn't been supported by Longhorn. We're tracking it at https://github.com/rancher/longhorn/issues/17
