### ISSUE TITLE
Try best to gracefully shutdown longhorn controller when IO in fly

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#51]
Currently the controller shutdown(by SIGTERM/Ctrl-C/docker stop) is problematic. When disk cache is dirty, the controller shutdown will flush current cache into the disk, which can pause the shutdown process for minutes.

Reproduce step for longhorn binary:
1. Start controller and connect to replica.
2. Start a IO process(e.g. dd), wait for e.g. 45 seconds(to make sure cache is dirty).
3. Stop the controller process(by SIGTERM or Ctrl-C), it may stuck at:
```
INFO[0075] Starting TCMU teardown.
INFO[0075] Removing: /sys/kernel/config/target/loopback/naa.6001405r0098f6bcd/tpgt_1/lun/lun_0/test
```
The process will likely take more than 30 seconds, then you will see tons information like this in the kernel log(dmesg): 
```
ABORT_TASK: Sending TMR_TASK_DOES_NOT_EXIST for ref_tag: 117
```
Finally shutdown process either finished or error out.

**Comment by sangeethah** [comment]
Able to reproduce the issue when following these steps:

1. Create a VM with ROOT volume using "longhorn"
2. Start writing data in ROOT volume ( using dd if=/dev/zero of=test bs=512)
3. While data is still being written , try to stop the controller container.
4. Controller container get stuck in "stopping" state forever.

**Comment by sangeethah** [comment]
This issue reproduces more consistently when testing with container having a DATA disk that is 10 GB.
Start writing data in DATA volume ( using dd if=/dev/zero of=test bs=512). After about 45 seconds, stop the controller. Controller container gets stuck in "stopping" state forever.

**Comment by sangeethah** [comment]
Reopening this issue for verification.

**Comment by sangeethah** [comment]
Tested with Rancher server - latest Build from master 
Ros version - v0.4.5-rc2 
Longhorn catalog template from - https://github.com/cjellick/longhorn-catalog (image - cjellick/longhorn:dev6)

Create a container with DATA volume using "longhorn"
Start writing data to DATA volume ( using dd if=/dev/zero of=test bs=512)
Wait for about 45 secs,
While data is still being written , try to stop the controller container.
Controller container gets stopped and restarted successfully.
