### ISSUE TITLE
pvc error No such file or directory

### ISSUE THREAD

**Issue by tiger0425** [rancher/longhorn#511]
Readiness probe failed: ls: cannot access '/dev/longhorn/pvc-3dd3c3fa-6fef-11e9-8bec-005056b4546b': No such file or directory
--

**Comment by tiger0425** [comment]
tgtd: iser_ib_init(3431) Failed to initialize RDMA; load kernel modules?
tgtd: work_timer_start(146) use timer_fd based scheduler
tgtd: bs_init(387) use signalfd notification
tgtd: device_mgmt(246) sz:108 params:path=/var/run/longhorn-pvc-3dd3c3fa-6fef-11e9-8bec-005056b4546b.sock,bstype=longhorn,bsopts=size=1073741824
tgtd: bs_thread_open(409) 16
time="2019-05-06T11:34:42Z" level=info msg="New data socket connnection established"
time="2019-05-06T11:34:43Z" level=warning msg="FAIL to discover due to Failed to execute: nsenter [--mount=/host/proc/130084/ns/mnt --net=/host/proc/130084/ns/net iscsiadm -m discovery -t sendtargets -p 10.42.10.131], output iscsiadm: Could not open /run/lock/iscsi: No such file or directory\n\niscsiadm: Could not open /run/lock/iscsi: No such file or directory\n\niscsiadm: Could not add new discovery record.\n, error exit status 6"
time="2019-05-06T11:34:43Z" level=warning msg="Nodes cleaned up for iqn.2014-09.com.rancher:pvc-3dd3c3fa-6fef-11e9-8bec-005056b4546b"
time="2019-05-06T11:34:47Z" level=warning msg="FAIL to discover due to Failed to execute: nsenter [--mount=/host/proc/130084/ns/mnt --net=/host/proc/130084/ns/net iscsiadm -m discovery -t sendtargets -p 10.42.10.131], output iscsiadm: Could not open /run/lock/iscsi: No such file or directory\n\niscsiadm: Could not open /run/lock/iscsi: No such file or directory\n\niscsiadm: Could not add new discovery record.\n, error exit status 6"
time="2019-05-06T11:34:47Z" level=warning msg="Nodes cleaned up for iqn.2014-09.com.rancher:pvc-3dd3c3fa-6fef-11e9-8bec-005056b4546b"
time="2019-05-06T11:34:50Z" level=warning msg="FAIL to discover due to Failed to execute: nsenter [--mount=/host/proc/130084/ns/mnt --net=/host/proc/130084/ns/net iscsiadm -m discovery -t sendtargets -p 10.42.10.131], output iscsiadm: Could not open /run/lock/iscsi: No such file or directory\n\niscsiadm: Could not open /run/lock/iscsi: No such file or directory\n\niscsiadm: Could not add new discovery record.\n, error exit status 6"
time="2019-05-06T11:34:50Z" level=warning msg="Nodes cleaned up for iqn.2014-09.com.rancher:pvc-3dd3c3fa-6fef-11e9-8bec-005056b4546b"
time="2019-05-06T11:34:53Z" level=warning msg="FAIL to discover due to Failed to execute: nsenter [--mount=/host/proc/130084/ns/mnt --net=/host/proc/130084/ns/net iscsiadm -m discovery -t sendtargets -p 10.42.10.131], output iscsiadm: Could not open /run/lock/iscsi: No such file or directory\n\niscsiadm: Could not open /run/lock/iscsi: No such file or directory\n\niscsiadm: Could not add new discovery record.\n, error exit status 6"
time="2019-05-06T11:34:53Z" level=warning msg="Nodes cleaned up for iqn.2014-09.com.rancher:pvc-3dd3c3fa-6fef-11e9-8bec-005056b4546b"
time="2019-05-06T11:34:56Z" level=warning msg="FAIL to discover due to Failed to execute: nsenter [--mount=/host/proc/130084/ns/mnt --net=/host/proc/130084/ns/net iscsiadm -m discovery -t sendtargets -p 10.42.10.131], output iscsiadm: Could not open /run/lock/iscsi: No such file or directory\n\niscsiadm: Could not open /run/lock/iscsi: No such file or directory\n\niscsiadm: Could not add new discovery record.\n, error exit status 6"
time="2019-05-06T11:34:56Z" level=warning msg="Nodes cleaned up for iqn.2014-09.com.rancher:pvc-3dd3c3fa-6fef-11e9-8bec-005056b4546b"
time="2019-05-06T11:34:59Z" level=error msg="Shutting down frontend due to failed to start up launcher: failed to start frontend: Failed to execute: longhorn-engine-launcher [--url 0.0.0.0:9510 frontend-start --id c737e971-3a2a-473f-9fc6-12fc2830d034], output , stderr, time=\"2019-05-06T11:34:59Z\" level=fatal msg=\"Error running frontend-start command: failed to start frontend: rpc error: code = Unknown desc = Failed to execute: nsenter [--mount=/host/proc/130084/ns/mnt --net=/host/proc/130084/ns/net iscsiadm -m node -T iqn.2014-09.com.rancher:pvc-3dd3c3fa-6fef-11e9-8bec-005056b4546b -p 10.42.10.131 --login], output iscsiadm: No records found\\n, error exit status 21.\"\n, error exit status 1"
2019/05/06 11:34:59 failed to start up launcher: failed to start frontend: Failed to execute: longhorn-engine-launcher [--url 0.0.0.0:9510 frontend-start --id c737e971-3a2a-473f-9fc6-12fc2830d034], output , stderr, time="2019-05-06T11:34:59Z" level=fatal msg="Error running frontend-start command: failed to start frontend: rpc error: code = Unknown desc = Failed to execute: nsenter [--mount=/host/proc/130084/ns/mnt --net=/host/proc/130084/ns/net iscsiadm -m node -T iqn.2014-09.com.rancher:pvc-3dd3c3fa-6fef-11e9-8bec-005056b4546b -p 10.42.10.131 --login], output iscsiadm: No records found\n, error exit status 21."
, error exit status 1

**Comment by yasker** [comment]
It sounds like the iscsid(open-iscsi) exists but wasn't configured correctly on the host. This is what iscsiadm reported.

`Could not open /run/lock/iscsi: No such file or directory`

**Comment by tiger0425** [comment]
Thank you. I found the reason. There is no automatic folder / run / lock generated by installing open-iscsi.
i create mkdir /run/lock,is ok

**Comment by yasker** [comment]
Thanks for the update. Issue closed.
