### ISSUE TITLE
PVC cannot bound to PV if default storage class is set when create PV/PVC from Longhorn UI

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#512]
Reproduce steps:
1. Create a volume in Longhorn UI
2. Set a storage class to be default in Kubernetes. (either using Rancher or https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/ )
3. Create PV of the volume
4. Create PVC of the volume.

The PVC won't show up.

`kubectl` shows that PVC has the default storage class set, which PV doesn't have.

**Comment by yasker** [comment]
Fix merged.

**Comment by meldafrawi** [comment]
**Longhorn Version:** 0.5.0-rc1

- PVC is now bound to PV
- in `kubectl` PV & PVC have the default storage class set.
