### ISSUE TITLE
Create PV/PVC together may end up in error

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#514]
It due to UI didn't wait for PV to complete creation (and in Available state) before continue to create PVC, so PVC creation call errors out.

<img width="880" alt="Screen Shot 2019-05-07 at 6 36 14 PM" src="https://user-images.githubusercontent.com/3344618/57343156-0a16a500-70f7-11e9-8487-2f49acf4282e.png">

<img width="800" alt="Screen Shot 2019-05-08 at 11 20 42 PM" src="https://user-images.githubusercontent.com/3344618/57432669-52af8a80-71eb-11e9-8047-6d1756d36680.png">

**Comment by yasker** [comment]
Talked with @smallteeths , it seems hard and slow for the frontend to poll the volume state between creating PV and create PVC.

We can add a flag to CreatePVInput and CreatePVCInput: `WaitForCompletion bool`. For CreatePV, we will wait (with a timeout) until PV shows up with status `Available` in the volume.KubernetesStatus; for CreatePVC, we will wait for the PV change state to `Bound`. This can also reports error for #512 instead of failed silently.

**Comment by yasker** [comment]
Backend change has been merged. No frontend change needed.

**Comment by meldafrawi** [comment]
**Longhorn Version:** 0.5.0-rc-1

I was able to Create PV/PVC together using,
  - UI: drop down menu in volume list page
  - UI: drop down menu in  volume details page 
  - UI: using bulk `Create PV/PVC` button in volume list page.
and are ended up being in bound state
