### ISSUE TITLE
Support object storage for backups (S3/Minio/etc)

### ISSUE THREAD

**Issue by pulberg** [rancher/longhorn#52]
Would be great to see support for object based storage for the backup location, ideally support for S3 api v2/v4.

**Comment by yasker** [comment]
@blaggacao Longhorn Engine already has the ability to backup to S3. We're integrating it with Longhorn Manager. You can take a look at https://rancher.com/microservices-block-storage/ `Backup of Snapshots`

**Comment by yasker** [comment]
Longhorn Engine change https://github.com/rancher/longhorn-engine/pull/302 merged.

**Comment by yasker** [comment]
Longhorn Manager change https://github.com/rancher/longhorn-manager/pull/67 merged.

**Comment by yasker** [comment]
Longhorn test https://github.com/rancher/longhorn-tests/pull/32 merged.

Done.
