### ISSUE TITLE
UI - Grayed out "Create PV/PVC" in drop down menu when trying to create a PVC for a PV in Released state.

### ISSUE THREAD

**Issue by meldafrawi** [rancher/longhorn#524]
**Steps to reproduce:**
- Create a pod with longhorn volume, using  `kubectl create -f https://raw.githubusercontent.com/rancher/longhorn/master/examples/pvc.yaml`

- Delete the pod using `kubectl delete pod volume-test`

- Change PV `persistentVolumeReclaimPolicy` to **Retain** using:
`kubectl patch  pv PV_NAME  -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'`

- Delete pvc  using `kubectl delete pvc longhorn-volv-pvc`

Using UI, try to use Create PV/PVC in drop down menu, you will notice that option is grayed out.

**Comment by yasker** [comment]
An easier way to reproduce:
1. Create a volume
2. Create PV and PVC for it.
3. Delete the PVC using `kubectl delete pvc xxx`
4. Notice the UI shows the PV state to `Released`, but `Create PV/PVC` in dropdown wasn't allowed.

**Comment by smallteeths** [comment]
After deleted the PVC successful， the PVstatus from the data will be failed, SO if created the PVC again, it's also will be failed.
![Jietu20190513-144606](https://user-images.githubusercontent.com/27733391/57607267-42a5fb00-759d-11e9-9c42-3bc93f505fff.jpg)

**Comment by yasker** [comment]
@smallteeths This may be related to #525

**Comment by meldafrawi** [comment]
Longhorn Version: 0.5.0-rc2

Fixed
