### ISSUE TITLE
Kuberenetes storage controller not adding size option to created PVs

### ISSUE THREAD

**Issue by techninja1008** [rancher/longhorn#53]
When the storage controller creates a PV in response to an unsatisfied PVC, the size option is not added, meaning the pod fails to be created as the flex volume script fails.

**Comment by yasker** [comment]
@techninja1008 Which version of k8s you're using?

**Comment by yasker** [comment]
I've found out that the Flexvolume plugin wasn't waiting for the volume to be `detached`, so it may fail intermediately. Since we're doing provisioning through dynamic provisioner, the Flexvolume plugin's creation will fail. The retry process by k8s controller will keep calling the Flexvolume plugin. it will ultimately pick up the change that volume is in `detached` state, then the driver will attach it.

So in my setup, the Flexvolume plugin works after automatic retry and does provide the correct volume to the pod.

@techninja1008 I will fix the intermediate failure. Just want to confirm that in your setup the pod starts with the volume in the end as well.

**Comment by yasker** [comment]
@techninja1008 Can you check if the latest of https://github.com/yasker/longhorn-manager fixes your problem?

You can use the following upgrade the Flexvolume drivers to my latest build. It will only upgrade the driver and won't touch anything else:
```
kubectl delete -f https://raw.githubusercontent.com/yasker/longhorn-manager/work/deploy/02-components/04-driver.yaml
kubectl create -f https://raw.githubusercontent.com/yasker/longhorn-manager/work/deploy/02-components/04-driver.yaml
```

**Comment by techninja1008** [comment]
I am on Kubernetes 1.9.5-rancher1, deployed with RKE.

I do believe that will fix my intermittent timeout errors, however, it then proceeds to fail as the driver is not passed a size option. It's definitely not the only problem as the same pod's still failing 12 hours later...

Here is the relevant section of the created PV:
```
"capacity": {
      "storage": "976564Ki"
    },
    "flexVolume": {
      "driver": "rancher.io/longhorn",
      "fsType": "ext4",
      "options": {
        "fromBackup": "",
        "numberOfReplicas": "3",
        "staleReplicaTimeout": "30"
      }
    }
```

From reading a bit of the code, ~it appears that the problem is~ after reading the update you gave me, I spotted that you've changed the code for the options so that it checks for null output from `jq`.
However, as the PV doesn't have a size option in the first place, it fails to create the volume.

**Comment by techninja1008** [comment]
Ok, after trying that update, it's simply not getting past the mount device timeout at all:

```
Normal   Scheduled              9m                default-scheduler        Successfully assigned kube-cert-manager-b98c7fdf4-bl4c7 to 212.47.241.212
  Normal   SuccessfulMountVolume  9m                kubelet, 212.47.241.212  MountVolume.SetUp succeeded for volume "default-token-gn6pc"
  Warning  FailedMount            1m (x3 over 7m)   kubelet, 212.47.241.212  MountVolume.SetUp failed for volume "pvc-c2e63336-357f-11e8-aa6c-0007cb0b44a7" : mount command failed, status: Failure, reason: Wait block device /dev/longhorn/pvc-c2e63336-357f-11e8-aa6c-0007cb0b44a7 timeout
  Warning  FailedMount            59s (x4 over 7m)  kubelet, 212.47.241.212  Unable to mount volumes for pod "kube-cert-manager-b98c7fdf4-bl4c7_certmanager(c30bceac-357f-11e8-aa6c-0007cb0b44a7)": timeout expired waiting for volumes to attach/mount for pod "certmanager"/"kube-cert-manager-b98c7fdf4-bl4c7". list of unattached/unmounted volumes=[data]
```

**Comment by yasker** [comment]
OK, I think it's because of this: https://github.com/rancher/rke/issues/140

Also, can you show me the log of `longhorn-flexvolume-driver-deployer`?

**Comment by techninja1008** [comment]
I believe I've figured part of it out: RKE containerises all of the Kubernetes components including Kubelet. As the flex volume handler is run by Kubelet, it gets run in the container, without access to the host's /dev/longhorn

(sidenote: host's dev is accessible inside the container through /host/dev,rprivate/longhorn/...)

**Comment by yasker** [comment]
@techninja1008 right, that's why longhorn flexvolume driver cannot find the device. 

You can use the new bind-mount options of RKE to fix that. :)

**Comment by techninja1008** [comment]
Ah, makes sense, I'll just try that.

**Comment by yasker** [comment]
See here: https://github.com/rancher/rke/issues/140#issuecomment-375835796
