### ISSUE TITLE
UI: Need a way to show restoring in progress for disaster recovery volume

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#534]
Since the `activate` action is not available during restoration, users need to know that restoring is in progress.

@shuo-wu 

Can you provide more details on how can UI tell if the restoration in progress from API's perspective?

**Comment by shuo-wu** [comment]
When` volume.standby == true && volume.lastBackup != "" && volume.lastBackup != volume.controllers[0]. lastRestoredBackup`, the disaster recovery volume is in restoring process.

For corner case `volume.standby == true && volume.lastBackup == “”`, it’s possible that the the disaster recovery volume is in restoring process. But we cannot figure it out in UI perspective.

**Comment by meldafrawi** [comment]
**Longhorn Version:** 0.5.0-rc2

Longhorn UI:
- DR volume icon has gray color while DR volume is in restore process.
- DR volume icon has blue color when DR volume restoration process completed.
- DR volume icon tool tip show the state of DR volume restoration process.
