### ISSUE TITLE
Backend: Create backup API call timing out

### ISSUE THREAD

**Issue by meldafrawi** [rancher/longhorn#539]
**Longhorn Version:**  0.5.0-rc1

steps to reproduce:
  - Create a volume X
  - Attach the volume X to a node
  - Create a backup of X
  - Backup Volume list page, click `Create Disaster Recovery Volume` from volume drop down
  - Create the DR volume Xdr
  - Attach the Xdr volume to any node
  - Format volume X on the attached node
  - Mount the volume on the node, write a fairly large file ~ 2GB to it
  - Make a backup of Volume X
  - Select the volume & click Create Backup button.

**Comment by yasker** [comment]
Fixed in https://github.com/rancher/longhorn-manager/pull/295

**Comment by meldafrawi** [comment]
Longhorn Version: 0.5.0-rc2

Fixed
