### ISSUE TITLE
User should not be able to set Backupstore Poll Interval to negative number.

### ISSUE THREAD

**Issue by meldafrawi** [rancher/longhorn#543]
**Longhorn Version:** v0.5.0-rc1

in Longhorn UI > `Settings/General` >  set  `Backupstore Poll Interval` to negative value & click save

**Comment by yasker** [comment]
Should be fixed at https://github.com/rancher/longhorn-manager/commit/dd6c207aba0d2ed6348060b83e2547ccd6579656

**Comment by meldafrawi** [comment]
#523
