### ISSUE TITLE
Create a Helm Chart for Longhorn deployment

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#55]

**Comment by guangbochen** [comment]
added longhorn to our proposed [rancher-charts](https://github.com/rancher/rancher-charts/tree/2.0/proposed/longhorn)

**Comment by manwegit** [comment]
The just released Rancher 2.0 Catalog Chart for Longhorn is broken. 
Images it references are not available - 2018-05-03.

**Comment by guangbochen** [comment]
@manwegit the image tag is fixed, thanks.

**Comment by Dremor** [comment]
I tried to use the Helm chart, but Longhorn fail to create the volumes with the following error:

``time="2018-05-05T20:49:07Z" level=fatal msg="Failed to start up frontend: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm -m node -T iqn.2014-09.com.rancher:pvc-56c149d6-50a5-11e8-a437-fa163eedabad -p 10.42.0.32 --login], output iscsiadm: No records found\n, error exit status 21"``

Parameters used : 

- Default image : true
- Default Storage class : true
- Expose app using Layer 7 Load Balancer : false
- Longhorn UI Service : ClusterIP

**Comment by yasker** [comment]
Hi Dremor,

Can you check the log of the Longhorn Engine instance to see the detail
error message?

Also what's host OS version you're using?

**Comment by Dremor** [comment]
I forgot to setup iscsi. removed my comment.

**Comment by botzill** [comment]
Hi.

I wanted to ask if you have a helm chart with the latest version? Also, how easy will be to remove it using helm chart as well?

**Comment by yasker** [comment]
@botzill you can now install/uninstall latest Longhorn using Apps in Rancher, which is a wrapper around Helm Chart. We haven't released official Helm Chart yet.

**Comment by botzill** [comment]
Hi @yasker! Thx for reply. Rancher is a really nice platform, will look into that. For now, I have my own k8s cluster on DO and I want to test longhorn and having a helm chart for tests will be much easier. I saw [this](https://github.com/rancher/charts/tree/master/proposed/longhorn/v0.1.0) but not sure if it's up to date, can you guide me about this?

**Comment by yasker** [comment]
In Rancher repo, the latest one is at https://github.com/rancher/charts/tree/master/proposed/longhorn/latest . Yeah, we will always keep this up to date.

**Comment by botzill** [comment]
I see, great! Does this work with `helm install` ?
