### ISSUE TITLE
Sometimes VM gets an IP , but is not able to make outbound connections,

### ISSUE THREAD

**Issue by sangeethah** [rancher/longhorn#55]
Tested with Rancher server - latest Build from master 
Ros version - v0.4.4 
Longhorn catalog template from - https://github.com/cjellick/longhorn-catalog (image - cjellick/longhorn:dev5)

Had a set up with 3 hosts.

Deployed a VM with image yasker/vm-ubuntu:14.04 which has ROOT volumes using longhorn driver.
VM get an ipaddress (10.42.x.x ) but has no connectivity. It is unable to ping 8.8.8.8/google.com .
But is able to ping other containers in managed network and is also reachable from other containers using its assigned Ip address.

<img width="900" alt="screen shot 2016-05-10 at 5 38 33 pm" src="https://cloud.githubusercontent.com/assets/4266958/15170522/5c3ea14c-16fb-11e6-95a8-eedef94c0b75.png">

**Comment by yasker** [comment]
Close this one for now because we haven't seen this issue recently.
