### ISSUE TITLE
UI: Node: Edit disk page: Units are misaligned

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#550]
<img width="1229" alt="Screen Shot 2019-05-16 at 3 22 49 PM" src="https://user-images.githubusercontent.com/3344618/57890973-89d6fa80-77ee-11e9-8b3d-c0afb33a06da.png">

**Comment by meldafrawi** [comment]
`Enabled` radio button is still misaligned.

![Screenshot from 2019-05-18 02-31-51](https://user-images.githubusercontent.com/18232258/57962328-b6396680-7915-11e9-827e-9159ec81f025.png)

**Comment by yasker** [comment]
Fixed in v0.5.0-rc3.
