### ISSUE TITLE
UI: wrong Kubernetes status name after deleting PVC and workload for Longhorn volume

### ISSUE THREAD

**Issue by shuo-wu** [rancher/longhorn#551]
After deleting PVC and workload for Longhorn volume, the status name should be `Last Bounded PVC Name`, `Last Namespace`, `Last Pod Status`, and `Last Workload Type` rather than `PVC Name`, `Namespace`, `Pod Status`,  and `Workload Type`.

**Comment by yasker** [comment]
Also, I noticed the `namespace` is not shown as yellow in the list when `lastPVCRefAt` was set.

**Comment by meldafrawi** [comment]
**Longhorn UI Version:** fc8ba32

Fixed
