### ISSUE TITLE
Manager: add cron validation in the API

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#553]
To prevent cronjob failure without user knowing.

**Comment by meldafrawi** [comment]
**Longhorn Manager Version:** dcd57d

I was able to set invaild cron structure.

![Screenshot from 2019-05-18 04-23-14](https://user-images.githubusercontent.com/18232258/57963458-b0974d00-7924-11e9-88c9-303138c82094.png)

**Comment by yasker** [comment]
@meldafrawi I found out it's not allowed to save since that's when it passed to the backend. But editor part wasn't validated by the backend.

**Comment by yasker** [comment]
Per @meldafrawi , this is verified.
