### ISSUE TITLE
Rancher 2.0 longhorn is not working.

### ISSUE THREAD

**Issue by BalaBalaYi** [rancher/longhorn#61]
rancher version: v2.0.0

kubernetes: 
![image](https://user-images.githubusercontent.com/23303886/39792376-ddf7012e-5372-11e8-8b75-d7016d0c8845.png)

longhorn version:
![image](https://user-images.githubusercontent.com/23303886/39792390-f06933c2-5372-11e8-8470-2e3a3c6b2e0c.png)

Result:
The volume cant create automatically according to the storage class after the deployment from catalog.

deployment:
![image](https://user-images.githubusercontent.com/23303886/39792526-a85061c2-5373-11e8-8138-abe45026db12.png)

storage class:
![image](https://user-images.githubusercontent.com/23303886/39792446-449f19e8-5373-11e8-8678-57333eafbf39.png)

cant bond volume cuz volume didnt create:
![image](https://user-images.githubusercontent.com/23303886/39792473-69845282-5373-11e8-8f18-7b320807ccb7.png)

longhorn-ui cant find any volumes:
![image](https://user-images.githubusercontent.com/23303886/39792485-78c4d028-5373-11e8-8f2f-4bc9d8ea5672.png)

**Comment by BalaBalaYi** [comment]
create volume in longhorn-ui is ok:
![image](https://user-images.githubusercontent.com/23303886/39792727-b578c8c0-5374-11e8-8108-d7bc4a37d595.png)

![image](https://user-images.githubusercontent.com/23303886/39792734-bf980da2-5374-11e8-9c6a-ce30d310cd47.png)

Seems there is something wrong between kubernetes's pv and longhorn's volume. 
Flexvolume plugins problem same to 1.6.x?

**Comment by yasker** [comment]
Yeah, sounds like the flexvolume directory is wrong. What's k8s version on the node? And which distro of K8S you're using?

**Comment by BalaBalaYi** [comment]
@yasker 
Is 1.10.x.

 Image :
![image](https://user-images.githubusercontent.com/23303886/39792987-f1697770-5375-11e8-95d2-5fedccbd37dd.png)

**Comment by yasker** [comment]
I meant, what k8s running for the cluster with trouble? GKE? RKE(rancher builtin)?

For GKE, it's `/home/kubernetes/flexvolume`

For RKE, flexvolume directory is `/var/lib/kubelet/volumeplugins`. Need to set it for the catalog.

See https://github.com/rancher/longhorn#volume-can-be-attacheddetached-from-ui-but-kubernetes-podstatefulset-etc-cannot-use-it

We will add more documents about RKE.

**Comment by BalaBalaYi** [comment]
Its RKE.
I changed the dir to "/var/lib/kubelet/volumeplugins" in longhorn settings like this:
![image](https://user-images.githubusercontent.com/23303886/39793443-18e2f554-5378-11e8-90cc-ff1ffe265a89.png)

Seems i also need to change the corresponding config for kubelet?
Could u provide some easier way to do this? In rancher 2.0. thx^^

Also accroding to the image above , need more doc for RKE using.

**Comment by BalaBalaYi** [comment]
just found the kubelet 's flag is already:
![image](https://user-images.githubusercontent.com/23303886/39793687-1a862c22-5379-11e8-9c98-cee6d21a6529.png)

But the issue still exsist.

**Comment by Dremor** [comment]
Did you try to create a many-nodes RW volume ?

**Comment by BalaBalaYi** [comment]
@Dremor 
Just tried. The same "pending".

**Comment by Dremor** [comment]
Have you tried a single-node RW volume too ? In my case many-node RW was stuck in "Pending" state, but not in single-node RW.

**Comment by BalaBalaYi** [comment]
@Dremor 
Three access types all tried. Same issue. Pity...

**Comment by Angelinsky7** [comment]
got this after manually attaching the volume to the host (with the ui)
```
Containers:

 my-app-with-volume:

   Container ID:

   Image:          nginx

   Image ID:

   Port:           <none>

   State:          Waiting

     Reason:       ContainerCreating

   Ready:          False

   Restart Count:  0

   Environment:    <none>

   Mounts:

     /data from my-app-with-volume-vol1 (rw)

     /var/run/secrets/kubernetes.io/serviceaccount from default-token-wnvpx (ro)

Conditions:

 Type           Status

 Initialized    True

 Ready          False

 PodScheduled   True

Volumes:

 my-app-with-volume-vol1:

   Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)

   ClaimName:  app-with-volume-claim

   ReadOnly:   false

 default-token-wnvpx:

   Type:        Secret (a volume populated by a Secret)

   SecretName:  default-token-wnvpx

   Optional:    false

QoS Class:       BestEffort

Node-Selectors:  <none>

Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s

                node.kubernetes.io/unreachable:NoExecute for 300s

Events:

 Type     Reason                 Age               From               Message

 ----     ------                 ----              ----               -------

 Normal   Scheduled              13m               default-scheduler  Successfully assigned my-app-with-volume-68c5544c9c-996s4 to swarm

 Normal   SuccessfulMountVolume  13m               kubelet, swarm     MountVolume.SetUp succeeded for volume "default-token-wnvpx"

 Warning  FailedMount            6s (x6 over 11m)  kubelet, swarm     Unable to mount volumes for pod "my-app-with-volume-68c5544c9c-996s4_test-load-balancing(c9f03b62-5396-11e8-90d5-e0d55e2e2e44)": timeout expired waiting for volumes to attach or mount for pod "test-load-balancing"/"my-app-with-volume-68c5544c9c-996s4". list of unmounted volumes=[my-app-with-volume-vol1]. list of unattached volumes=[my-app-with-volume-vol1 default-token-wnvpx]
```

**Comment by Angelinsky7** [comment]
![image](https://user-images.githubusercontent.com/13157968/39822669-74bdb6c4-53ab-11e8-9e74-08fd717253d4.png)

**Comment by Angelinsky7** [comment]
i'am an idiot that cannot read the doc....
so everything seems to work fine... when you configure correctly and read the doc...

you maybe should make the field for the volume dir plugin empty by default... like that we would read the doc... sorry for the noise

**Comment by yasker** [comment]
@Dremor Longhorn only supports access mode ReadWriteOnce, like EBS or Google Persistent Disk. So ReadWriteMany won't work for Longhorn.

**Comment by yasker** [comment]
@BalaBalaYi 

Just to make sure that there is only one Longhorn system in your setup right?

Also, how do you create the volume using the longhorn storage class?

Can you check if anything happens in the any of longhorn-managers' log when you trying to create the volume?

**Comment by Angelinsky7** [comment]
yes... installed with the catalog app with rancher2
yes using the ui interface from rancher2
the log of everything appening during the creation of a pod with a new volume claim and new volume
```
ERROR: logging before flag.Parse: I0509 17:00:32.363338       1 controller.go:1084] scheduleOperation[lock-provision-test-load-balancing/my-app4-volume-claim[7beca36f-53aa-11e8-90d5-e0d55e2e2e44]]
ERROR: logging before flag.Parse: I0509 17:00:32.369779       1 controller.go:1084] scheduleOperation[lock-provision-test-load-balancing/my-app4-volume-claim[7beca36f-53aa-11e8-90d5-e0d55e2e2e44]]
ERROR: logging before flag.Parse: I0509 17:00:32.392608       1 leaderelection.go:156] attempting to acquire leader lease...
ERROR: logging before flag.Parse: I0509 17:00:32.401363       1 leaderelection.go:178] successfully acquired lease to provision for pvc test-load-balancing/my-app4-volume-claim
ERROR: logging before flag.Parse: I0509 17:00:32.401503       1 controller.go:1084] scheduleOperation[provision-test-load-balancing/my-app4-volume-claim[7beca36f-53aa-11e8-90d5-e0d55e2e2e44]]
DEBU[59835] Created volume pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44
INFO[59835] provisioner: created volume %vpvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44
ERROR: logging before flag.Parse: I0509 17:00:32.415209       1 controller.go:817] volume "pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44" for claim "test-load-balancing/my-app4-volume-claim" created
ERROR: logging before flag.Parse: I0509 17:00:32.418610       1 controller.go:834] volume "pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44" for claim "test-load-balancing/my-app4-volume-claim" saved
ERROR: logging before flag.Parse: I0509 17:00:32.418662       1 controller.go:870] volume "pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44" provisioned for claim "test-load-balancing/my-app4-volume-claim"
WARN[59835] HTTP handling error fail to parse size error parsing size 'null': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
ERRO[59835] Error in request: fail to parse size error parsing size 'null': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
WARN[59836] HTTP handling error fail to parse size error parsing size 'null': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
ERRO[59836] Error in request: fail to parse size error parsing size 'null': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
INFO[59836] Event(v1.ObjectReference{Kind:"Volume", Namespace:"longhorn", Name:"pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44", UID:"7bf611cf-53aa-11e8-90d5-e0d55e2e2e44", APIVersion:"longhorn.rancher.io", ResourceVersion:"115879", FieldPath:""}): type: 'Normal' reason: 'Detached' volume pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44 has been detached
ERROR: logging before flag.Parse: I0509 17:00:34.412142       1 leaderelection.go:198] stopped trying to renew lease to provision for pvc test-load-balancing/my-app4-volume-claim, task succeeded
DEBU[59838] Attaching volume pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44 to swarm
INFO[59838] Event(v1.ObjectReference{Kind:"Replica", Namespace:"longhorn", Name:"pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44-r-f1b5670e", UID:"7bf9da4d-53aa-11e8-90d5-e0d55e2e2e44", APIVersion:"longhorn.rancher.io", ResourceVersion:"115906", FieldPath:""}): type: 'Normal' reason: 'Start' Starts pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44-r-f1b5670e
INFO[59838] Event(v1.ObjectReference{Kind:"Replica", Namespace:"longhorn", Name:"pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44-r-ac9324b3", UID:"7bfaa388-53aa-11e8-90d5-e0d55e2e2e44", APIVersion:"longhorn.rancher.io", ResourceVersion:"115907", FieldPath:""}): type: 'Normal' reason: 'Start' Starts pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44-r-ac9324b3
INFO[59838] Event(v1.ObjectReference{Kind:"Replica", Namespace:"longhorn", Name:"pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44-r-238bb5ae", UID:"7bfbb78a-53aa-11e8-90d5-e0d55e2e2e44", APIVersion:"longhorn.rancher.io", ResourceVersion:"115908", FieldPath:""}): type: 'Normal' reason: 'Start' Starts pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44-r-238bb5ae
DEBU[59839] Requeue longhorn/pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44-r-f1b5670e due to conflict
INFO[59848] Event(v1.ObjectReference{Kind:"Engine", Namespace:"longhorn", Name:"pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44-e", UID:"7bf84da7-53aa-11e8-90d5-e0d55e2e2e44", APIVersion:"longhorn.rancher.io", ResourceVersion:"115968", FieldPath:""}): type: 'Normal' reason: 'Start' Starts pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44-e
DEBU[59856] Start monitoring pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44-e
INFO[59856] Event(v1.ObjectReference{Kind:"Volume", Namespace:"longhorn", Name:"pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44", UID:"7bf611cf-53aa-11e8-90d5-e0d55e2e2e44", APIVersion:"longhorn.rancher.io", ResourceVersion:"115911", FieldPath:""}): type: 'Normal' reason: 'Attached' volume pvc-7beca36f-53aa-11e8-90d5-e0d55e2e2e44 has been attached to swarm
```

**Comment by Angelinsky7** [comment]
![image](https://user-images.githubusercontent.com/13157968/39828527-ab1bd830-53bb-11e8-9805-212811492781.png)

**Comment by Angelinsky7** [comment]
![image](https://user-images.githubusercontent.com/13157968/39828547-bec8c744-53bb-11e8-89dd-5f2d18c46c83.png)

**Comment by Angelinsky7** [comment]
sorry didn't read that you weren't taking to me... but you now have more info nevertheless

**Comment by yasker** [comment]
@Angelinsky7 thanks anyway, now we have some success log on how the Longhorn manager should work. :)

Also noticed the bogus error message about `size` in your log. It will be addressed in the next release.

**Comment by yasker** [comment]
@BalaBalaYi 

If you only create PV and PVC but not using them, I think K8s may not call the volume driver to populate the volume. So you won't see anything until you started to use the PVC.

If you create a PVC using storage class, the volume will be in detached mode until you start using it.

You can try it with some workload to see if everything works as expected.

**Comment by BalaBalaYi** [comment]
@yasker 
Thx a lot. The storage got fine when i deployed a nginx using the pvc by longhorn storage class.
We will keep testing.

Thank you so much for ur patient. Looking forward to ur effort^^
