### ISSUE TITLE
Authentication support

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#64]
To enable the management UI on the net.

https://github.com/rancher/longhorn-ui/issues/14

**Comment by yasker** [comment]
Update: as in v0.3.2, when installing as a catalog app, Longhorn UI will be exposed behind Rancher. You will need to have the access to the project Longhorn is running to access the UI.

Longhorn still needs its own user management support though.

**Comment by junkiebev** [comment]
Is access granted by RBAC? What are the roles required?

**Comment by yasker** [comment]
I think it's limited to who has access to the `longhorn-system` namespace in Rancher. @guangbochen can help to confirm.

**Comment by guangbochen** [comment]
yes, and to be more detailed, we will default to project(1 project contains multiple ns) level access protection, not 100% sure about namespace level protection, but you can always move it to an independent project if that matters.

**Comment by yasker** [comment]
Close this issue since we now provided authentication though Rancher. Separate user management can be filed as another issue.

**Comment by cntsw** [comment]
@guangbochen @yasker
If the user bypasses the Ingress or Rancher and accesses the longhorn-frontend Pod directly, does it mean that there is no authorized support?
(Assuming there is no network isolation, users can access the Pod's IP segment by some means)

**Comment by yasker** [comment]
@cntsw yeah, in that case, there will be no authorization support in the current version.
