### ISSUE TITLE
Reboot all nodes when volume attached result in volume stuck in `attaching` state

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#66]
Reproduce steps (simplified from https://github.com/rancher/longhorn/issues/60#issuecomment-387540363 )

1. Create a new volume, attach to a node
2. Reboot all the nodes in the cluster
3. After K8S cluster back online, the volume stuck in `attaching` state.

**Comment by Angelinsky7** [comment]
@yasker got the "same" issue... shutdown my host and reboot it...
all the volume are in the infinite attaching state...
what could i do to workaround waiting for the fix ? (some volumes don't have backups) ?

**Comment by yasker** [comment]
@Angelinsky7 

Yes, it can be worked around:
1. `kubectl -n longhorn-system edit lhv <volume_name>`
2. Set the `spec.nodeID` to "".

It will help to detach the volume. Then the volume can be attached again.

This is an issue because the engine for the volume has been dead unexpectedly (due to the reboot). The current fix we have is to detach the volume automatically when this happened.

**Comment by Angelinsky7** [comment]
@yasker thanks this is working !!!

**Comment by yasker** [comment]
We've fixed part of the problem. Now after the reboot, the volume will be detached automatically.

We need to check more before we can decide if we need to attach the volume back automatically or not. Seems CSI expected the volume to be attached if the node reboots.

**Comment by yasker** [comment]
Now we automatically attach the volume after the node reboot.
