### ISSUE TITLE
Add a button in UI to create snapshot then backup in one step

### ISSUE THREAD

**Issue by Angelinsky7** [rancher/longhorn#67]
How can we manually create a backup without first making a snapshot ?

**Comment by yasker** [comment]
You cannot. Snapshot represent a fixed version for the volume and backup cannot be made without it.

Curious why don't want to create a snapshot?

**Comment by Angelinsky7** [comment]
@yasker this was more a question about how "you" think it should be done...
i'm clearly discovering rancher/kubernetes/longhorn and i don't have best practices yet :-)
If we need a snapshot to create a backup, i would maybe want, that when i create a backup, a snapshot would be automatically created and destroyed (depending on an option) for me in the background.
My experience of the ui for now was that i searched in the ui for a moment, looking for the *create backup* button... and then after a while not finding it, decided to try the snapshot feature to discover that i could create a backup from there... (it's clearly because the documentation is not yet there, but i might think that it could be a little more obvious, non ???)

**Comment by yasker** [comment]
Yeah, that makes sense. We will add a feature in UI to create snapshot then backup automatically.

**Comment by yasker** [comment]
Fixed.
