### ISSUE TITLE
Fix driver with ext4 option on CentOS 7

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#71]
Currently, the driver supports ext4 as default but it somehow doesn't work with CentOS, even though CentOS has necessary tools to operate on it.

See the thread in https://github.com/rancher/longhorn/issues/69#issuecomment-392279796

**Comment by jeroenjacobs1205** [comment]
It's possible to set  fsType: "xfs" in the pvc, and this works on CentOS7. I just verified this.

**Comment by yasker** [comment]
@jeroenjacobs1205 Thanks for investigating.

I've updated the issue to address CentOS ext4 specifically.

**Comment by yasker** [comment]
@zhoubofsy 

There is a bug in https://github.com/rancher/longhorn-manager/blob/master/driver/longhorn#L233

That line ignored the output of `mkfs`. We need to fix that.

If logging is enabled (`$LONGHORN_DRIVER_LOG` exists), output the result of `mkfs` to the log. Otherwise, output the log to console.

**Comment by yasker** [comment]
@zhoubofsy Can you take a look at https://github.com/rancher/longhorn/issues/69#issuecomment-395937118 

And test if `mke2fs` v1.43.4 failed on Longhorn volume?

**Comment by yasker** [comment]
it's not a centos issue. It's due to the network according to our understanding now. Close the issue for now.
