### ISSUE TITLE
Incorrect disk space reported for ROS hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/longhorn#76]
rancher-server version - v1.1.0-dev2-rc2
longhorn version - rancher/longhorn:v0.1.0-rc5

In my setup , i have 3 hosts of "type1" from packets all having storage - "2 x 120GB Enterprise SSD".

In ranche-server UI , I see 2 of my hosts report "108 GiB" and 1 of them report - " 227 GiB" .
This results in replica containers for "DATA" disks in longhorn  

<img width="970" alt="screen shot 2016-05-15 at 11 48 17 am" src="https://cloud.githubusercontent.com/assets/4266958/15276107/f14d7bc4-1a92-11e6-9768-7cb044d2f171.png">

```
[rancher@san-final-3 ~]$ df -h  .
Filesystem                Size      Used Available Use% Mounted on
/dev/md127              217.7G     27.9G    178.8G  13% /home
[rancher@san-final-3 ~]$ exit
logout
Connection to 147.75.198.247 closed.
Sangeethas-MBP:bin sangeethahariharan1$ ssh rancher@147.75.192.7
[rancher@san-final-2 ~]$ df -h  .
Filesystem                Size      Used Available Use% Mounted on
/dev/md127              107.7G      6.6G     95.6G   6% /opt
[rancher@san-final-2 ~]$ 
```

**Comment by yasker** [comment]
It's packet allocated different machines with different storage size here, as shown in `df`.

Close the bug.
