### ISSUE TITLE
Multiple Pods, multiple persistent volumes

### ISSUE THREAD

**Issue by saschaarthur** [rancher/longhorn#76]
Hey,

Im having the issue if im starting a 3 instance pod and attaching persistent volumes, that only 1 volume is provisioned.

I cant scale up the number of pods, the provisioning of persistent volumes does not work in this case.

**Comment by yasker** [comment]
Please use statefulset instead of deployment.

See https://github.com/rancher/longhorn/blob/master/examples/statefulset.yaml for example.

**Comment by saschaarthur** [comment]
Importing this file via rancher UI gives me:

![grafik](https://user-images.githubusercontent.com/4057921/40846161-17fd7aa8-65b9-11e8-9177-80516e251945.png)

(endless loading)

**Comment by yasker** [comment]
Try it with kubectl.

If it works, you can report a bug at Rancher UI and link this to the issue.

**Comment by yasker** [comment]
Close the issue for now. Please reopen if the solution doesn't work.
