### ISSUE TITLE
Base image support

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#78]
Longhorn Engine already supports `--backing-file` to use a qcow2 image file as the base for the volume. We need to add the support for Longhorn Manager.

It's needed for Rancher VM integration.

**Comment by LLParse** [comment]
https://github.com/rancher/longhorn-manager/pull/79
https://github.com/rancher/longhorn-engine/pull/304
https://github.com/rancher/longhorn-ui/pull/15

**Comment by yasker** [comment]
Done.
