### ISSUE TITLE
Backup user experience improvement

### ISSUE THREAD

**Issue by dnauck** [rancher/longhorn#83]
Currently i need to navigate to each volume and:

1.) need to check if backup is already configured (i do not see it in the volumes list)
2.) configure backup for each volume "by hand"

If i use Rancher and have a "Project" i've a SLA or definition that everything in this project needs "daily backups for 30 days" or sth like that. So it would be nice to have an option to define (and monitor) the backup strategy for a complete project/namespace/deployment.

**Comment by yasker** [comment]
Maybe it can achieve by providing a more comprehensive overview of the volume list.

**Comment by yasker** [comment]
Track #82 Item 5 in this issue as well.

https://github.com/rancher/longhorn/issues/82

5. show info about scheduled backups (everything green and healthy?)

**Comment by yasker** [comment]
In the volume list, we will show:
1. What's the latest backup and when it was taken (depends on backend https://github.com/rancher/longhorn/issues/459 )
2. Is there a recurring backup has been configured for the volume. It can be just an icon, then e.g. click the icon to show the detail of recurring snapshot and backups.

**Comment by yasker** [comment]
The support of default backup policy will be tracked as #467 

The feature that listing the current backup schedule and last backup has been merged.
