### ISSUE TITLE
One click support bundle download

### ISSUE THREAD

**Issue by dnauck** [rancher/longhorn#84]
To get help easier, implement a button that downloads a zip file containing everything you need to provide support, e.g.:

* manager logs
* configurations
* ....

**Comment by yasker** [comment]
Wow, this will be helpful, though it's maybe hard to adapt to the different environments.

As a first step, we should provide a troubleshooting guide to point out which logs should be collected. Starting from there we can begin to make the process more automatic.

**Comment by yasker** [comment]
A list of information we should be able to get from manager:
1. Longhorn configurations (CRDs)
2. Running pods list and logs in longhorn-system namespace, includes manager and engine, as well as drivers.

**Comment by yasker** [comment]
@ly5156 Need UI to add a link `Generate Support Bundle` at the bottom bar, between `Documentation` and `File an Issue`, and link to the backend URL `/v1/supportbundle`.
