### ISSUE TITLE
Error provisioning volumes on a Bare-Metal deployment

### ISSUE THREAD

**Issue by mtenrero** [rancher/longhorn#89]
Hello. I've deployed longhorn in a custom cluster with Rancher but when I try to create a new volume via Longhor UI the logs gives me this error

```
the server does not allow this method on the requested resource (post volumes.longhorn.rancher.io)
```
Also, when I try to deploy a stateful app, it couldn't be succesfully deployed because any volume is deployed.

The volume-plugin-dir is correctly confgured: /var/lib/kubelet/volumeplugins

**Comment by yasker** [comment]
@mtenrero Seems something is wrong with the permission. How do you deploy Longhorn, by using Rancher Apps or use `github.com/rancher/longhorn`?

The permission for Longhorn Manager was defined in `longhorn-role`. Can you check:
```
kubectl -n longhorn-system get clusterrole longhorn-role -o yaml
```
to see if it contains following:
```
- apiGroups:
  - longhorn.rancher.io
  resources:
  - volumes
  - engines
  - replicas
  - settings
  verbs:
  - '*'
```

**Comment by mtenrero** [comment]
I've deployed longhorn via Rancher Apps.

It seems to be wrong configured, this is the output:

```console
-apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - events
  - persistentvolumes
  - persistentvolumeclaims
  - nodes
  - proxy/nodes
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - daemonsets
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - '*'
- apiGroups:
  - longhorn.rancher.io
  resources:
  - nodes
  verbs:
  - '*'
- apiGroups:
  - longhorn.rancher.io
  resources:
  - volumes
  verbs:
  - '*'
- apiGroups:
  - longhorn.rancher.io
  resources:
  - engines
  verbs:
  - '*'
- apiGroups:
  - longhorn.rancher.io
  resources:
  - replicas
  verbs:
  - '*'
- apiGroups:
  - longhorn.rancher.io
  resources:
  - settings
  verbs:
  - '*'
```

**Comment by mtenrero** [comment]
**longhorn-bind kubectl output**
```yaml
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: longhorn-role
subjects:
- kind: ServiceAccount
  name: longhorn-service-account
  namespace: longhorn-0robua
```
**longhorn-manager kubectl output**
```yaml
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: longhorn-manager
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: longhorn-manager
    spec:
      containers:
      - command:
        - longhorn-manager
        - -d
        - daemon
        - --engine-image
        - rancher/longhorn-engine:de88734
        - --manager-image
        - rancher/longhorn-manager:1ebf5cb
        - --service-account
        - longhorn-service-account
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: LONGHORN_BACKEND_SVC
          value: longhorn-backend
        image: rancher/longhorn-manager:1ebf5cb
        imagePullPolicy: Always
        name: longhorn-manager
        ports:
        - containerPort: 9500
          name: manager
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/dev/
          name: dev
        - mountPath: /host/proc/
          name: proc
        - mountPath: /var/run/
          name: varrun
        - mountPath: /var/lib/rancher/longhorn/
          name: longhorn
        - mountPath: /usr/local/bin/
          name: execbin
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - cp /usr/local/bin/* /data/
        image: rancher/longhorn-engine:de88734
        imagePullPolicy: IfNotPresent
        name: init-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/
          name: execbin
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: longhorn-service-account
      serviceAccountName: longhorn-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /dev/
          type: ""
        name: dev
      - hostPath:
          path: /proc/
          type: ""
        name: proc
      - hostPath:
          path: /var/run/
          type: ""
        name: varrun
      - hostPath:
          path: /var/lib/rancher/longhorn/
          type: ""
        name: longhorn
      - emptyDir: {}
        name: execbin
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 4
  desiredNumberScheduled: 4
  numberAvailable: 4
  numberMisscheduled: 0
  numberReady: 4
  observedGeneration: 1
  updatedNumberScheduled: 4
```

**longhorn manager pod full log:**

```console

ERROR: logging before flag.Parse: I0618 16:30:33.449827       1 controller_utils.go:1041] Waiting for caches to sync for longhorn datastore controller

ERROR: logging before flag.Parse: I0618 16:30:33.651089       1 controller_utils.go:1048] Caches are synced for longhorn datastore controller

INFO[0000] Start Longhorn volume controller

INFO[0000] Start Longhorn replica controller

ERROR: logging before flag.Parse: I0618 16:30:33.651367       1 controller_utils.go:1041] Waiting for caches to sync for longhorn engines controller

INFO[0000] Start Longhorn engine controller

ERROR: logging before flag.Parse: I0618 16:30:33.651372       1 controller_utils.go:1041] Waiting for caches to sync for longhorn replicas controller

ERROR: logging before flag.Parse: I0618 16:30:33.651414       1 controller_utils.go:1041] Waiting for caches to sync for longhorn engines controller

ERROR: logging before flag.Parse: I0618 16:30:33.751507       1 controller_utils.go:1048] Caches are synced for longhorn engines controller

ERROR: logging before flag.Parse: I0618 16:30:33.751508       1 controller_utils.go:1048] Caches are synced for longhorn engines controller

ERROR: logging before flag.Parse: I0618 16:30:33.751724       1 controller_utils.go:1048] Caches are synced for longhorn replicas controller

ERROR: logging before flag.Parse: I0618 16:30:33.855765       1 controller.go:407] Starting provisioner controller ec768e6e-7314-11e8-b0fa-3e920f7eda29!

INFO[0000] Listening on 10.42.1.49:9500

WARN[0035] HTTP handling error unable to create volume: unable to create volume 7: &{OwnerID: Size:21474836480 FromBackup: NumberOfReplicas:3 StaleReplicaTimeout:20 NodeID: RecurringJobs:[]}: the server does not allow this method on the requested resource (post volumes.longhorn.rancher.io)

ERRO[0035] Error in request: unable to create volume: unable to create volume 7: &{OwnerID: Size:21474836480 FromBackup: NumberOfReplicas:3 StaleReplicaTimeout:20 NodeID: RecurringJobs:[]}: the server does not allow this method on the requested resource (post volumes.longhorn.rancher.io)

WARN[0044] HTTP handling error unable to create volume: unable to create volume 7: &{OwnerID: Size:21474836480 FromBackup: NumberOfReplicas:3 StaleReplicaTimeout:20 NodeID: RecurringJobs:[]}: the server does not allow this method on the requested resource (post volumes.longhorn.rancher.io)

ERRO[0044] Error in request: unable to create volume: unable to create volume 7: &{OwnerID: Size:21474836480 FromBackup: NumberOfReplicas:3 StaleReplicaTimeout:20 NodeID: RecurringJobs:[]}: the server does not allow this method on the requested resource (post volumes.longhorn.rancher.io)
```

**Comment by yasker** [comment]
Are you using a number(`7`) for volume name? I don't think that's allowed. The name cannot be started with a number.

We should add a UI and a backend check for that.

**Comment by yasker** [comment]
@mtenrero Yeah, you're right.

Which namespace longhorn manager is in? It doesn't show in `longhorn-manager kubectl output`

**Comment by yasker** [comment]
Also, just want to confirm that you have only one Longhorn System running on your cluster right? Because the service account `longhorn-0robua` shows that Helm Charts created another namespace for the Longhorn system. By default it should be `longhorn` for the Longhorn System.

**Comment by mtenrero** [comment]
All longhorn components are in longhorn-0robua namespace, because longhorn namespace was taken by a previous deployment.

Anyway that namespace is empty. 

I'll try to clean all namespaces and deploy longhorn again in longhorn namespace to check if the problem comes from the namespace.

**Comment by yasker** [comment]
@mtenrero The previous namespace probably is not empty. Check `kubectl -n longhorn get lhv`. (and `lhe` as well as `lhr`)

You may need to use `kubectl -n longhorn edit lhv`(`lhe`, `lhr`) to remove the finalizers if you have leftover volumes previously.

**Comment by mtenrero** [comment]
You were right, the _longhorn_ namespace were dirty. I've removed succesfully the namespace and redeployed again in the _longhorn_ namespace instead if _longhorn-0rouba_ ns.

But the longhorn-manager now have another error:

```console
ERROR: logging before flag.Parse: E0618 19:48:01.463328       1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:61: Failed to list *v1alpha1.Replica: the server could not find the requested resource (get replicas.longhorn.rancher.io)
```

**Comment by yasker** [comment]
What's the result of `kubectl -n longhorn get crd`? It should contains:

```
NAME                                          AGE
engines.longhorn.rancher.io                   6d
replicas.longhorn.rancher.io                  6d
settings.longhorn.rancher.io                  6d
volumes.longhorn.rancher.io                   6d
```

**Comment by mtenrero** [comment]
```console
NAME                                          AGE
bgpconfigurations.crd.projectcalico.org       2d
clusterinformations.crd.projectcalico.org     2d
engines.longhorn.rancher.io                   13m
felixconfigurations.crd.projectcalico.org     2d
globalnetworkpolicies.crd.projectcalico.org   2d
globalnetworksets.crd.projectcalico.org       2d
hostendpoints.crd.projectcalico.org           2d
ippools.crd.projectcalico.org                 2d
networkpolicies.crd.projectcalico.org         2d
settings.longhorn.rancher.io                  13m
volumes.longhorn.rancher.io                   13m
```

**Comment by mtenrero** [comment]
It seems to be dirty data again..

**Comment by yasker** [comment]
@mtenrero `replicas.longhorn.rancher.io` somehow is missing... Others are for calico, don't touch them.

**Comment by mtenrero** [comment]
Cleaning everything again and redeploying deployed longhorn succesfully. Now, I can create volumes via Longhorn UI and provisioner seems to work correctly:

‘’’console
DEBU[0386] Created volume pvc-22dc5fa5-7335-11e8-8e0b-bc305bc27760

INFO[0386] provisioner: created volume %vpvc-22dc5fa5-7335-11e8-8e0b-bc305bc27760

ERROR: logging before flag.Parse: I0618 22:21:58.038912       1 controller.go:817] volume "pvc-22dc5fa5-7335-11e8-8e0b-bc305bc27760" for claim "efk/data-efk-elasticsearch-2" created

ERROR: logging before flag.Parse: I0618 22:21:58.083287       1 controller.go:834] volume "pvc-22dc5fa5-7335-11e8-8e0b-bc305bc27760" for claim "efk/data-efk-elasticsearch-2" saved

ERROR: logging before flag.Parse: I0618 22:21:58.083399       1 controller.go:870] volume "pvc-22dc5fa5-7335-11e8-8e0b-bc305bc27760" provisioned for claim "efk/data-efk-elasticsearch-2"

ERROR: logging before flag.Parse: I0618 22:21:59.911009       1 leaderelection.go:198] stopped trying to renew lease to provision for pvc efk/data-efk-elasticsearch-2, task succeeded
‘’’
But the volumes are not usable because they are degraded every few seconds, and in my stateful deployment , elasticsearch, the volume doesn’t works.

This is the statefulset config:
‘’’yaml
"statefulSetConfig": {

    "podManagementPolicy": "Parallel",
    "revisionHistoryLimit": 10,
    "serviceName": "efk-elasticsearch",
    "strategy": "OnDelete",
    "volumeClaimTemplates": [
        {
            "accessModes": [
                "ReadWriteOnce"
            ],
            "created": null,
            "creatorId": null,
            "id": "data",
            "name": "data",
            "namespaceId": null,
            "projectId": null,
            "resources": {
                "requests": {
                    "storage": "35Gi"
                },
                "type": "/v3/project/schemas/resourceRequirements"
            },
            "state": "pending",
            "status": {
                "phase": "Pending",
                "type": "/v3/project/schemas/persistentVolumeClaimStatus"
            },
            "storageClassId": "longhorn",
            "transitioning": "no",
            "transitioningMessage": "",
            "type": "/v3/project/schemas/persistentVolumeClaim",
            "volumeId": null
        }
    ]

}
‘’’

**Comment by yasker** [comment]
@mtenrero Can you show me the `kubectl describe <pod>`? Do you see the volume has been attached in the Longhorn UI? Maybe flexvolume plugin issue.

**Comment by mtenrero** [comment]
In Longhorn UI apperars as healthy in all 3 nodes.

‘’’yaml
nit Containers:
  sysctl:
    Container ID:  docker://f0c7ec3a755ef88abf0d766551a20469b15e3eec082d0f2173bbdd33ac690d63
    Image:         busybox
    Image ID:      docker-pullable://busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
    Port:          <none>
    Host Port:     <none>
    Command:
      sysctl
      -w
      vm.max_map_count=262144
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 19 Jun 2018 01:14:55 +0200
      Finished:     Tue, 19 Jun 2018 01:14:55 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from efk-elasticsearch-token-p9wmc (ro)
Containers:
  elasticsearch:
    Container ID:   docker://fdcc3bfeea4f01af2c78add880560c78731fd82c2ced48c9fac5e2959f1e3bcd
    Image:          docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    Image ID:       docker-pullable://docker.elastic.co/elasticsearch/elasticsearch-oss@sha256:2d9c774c536bd1f64abc4993ebc96a2344404d780cbeb81a8b3b4c3807550e57
    Ports:          9300/TCP, 9200/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 19 Jun 2018 01:52:07 +0200
      Finished:     Tue, 19 Jun 2018 01:52:12 +0200
    Ready:          False
    Restart Count:  12
    Limits:
      cpu:  1
    Requests:
      cpu:      25m
      memory:   512Mi
    Readiness:  http-get http://:9200/_cluster/health%3Flocal=true delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      cluster.name:                        efk-cluster
      discovery.zen.ping.unicast.hosts:    efk-elasticsearch
      discovery.zen.minimum_master_nodes:  2
      KUBERNETES_NAMESPACE:                efk (v1:metadata.namespace)
      discovery.zen.ping.unicast.hosts:    efk-elasticsearch
      PROCESSORS:                          1 (limits.cpu)
      ES_JAVA_OPTS:                        -Djava.net.preferIPv4Stack=true -Xms1g -Xmx1g
    Mounts:
      /usr/share/elasticsearch/data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from efk-elasticsearch-token-p9wmc (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-efk-elasticsearch-1
    ReadOnly:   false
  efk-elasticsearch-token-p9wmc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  efk-elasticsearch-token-p9wmc
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                 From               Message
  ----     ------                 ----                ----               -------
  Warning  FailedScheduling       43m (x5 over 44m)   default-scheduler  pod has unbound PersistentVolumeClaims (repeated 4 times)
  Normal   Scheduled              43m                 default-scheduler  Successfully assigned efk-elasticsearch-1 to kaiju
  Normal   SuccessfulMountVolume  43m                 kubelet, kaiju     MountVolume.SetUp succeeded for volume "efk-elasticsearch-token-p9wmc"
  Normal   SuccessfulMountVolume  42m                 kubelet, kaiju     MountVolume.SetUp succeeded for volume "pvc-1f8edcc2-734d-11e8-8e0b-bc305bc27760"
  Normal   Pulling                42m                 kubelet, kaiju     pulling image "busybox"
  Normal   Pulled                 42m                 kubelet, kaiju     Successfully pulled image "busybox"
  Normal   Created                42m                 kubelet, kaiju     Created container
  Normal   Started                42m                 kubelet, kaiju     Started container
  Normal   Created                41m (x4 over 42m)   kubelet, kaiju     Created container
  Normal   Started                41m (x4 over 42m)   kubelet, kaiju     Started container
  Normal   Pulled                 38m (x6 over 42m)   kubelet, kaiju     Container image "docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4" already present on machine
  Warning  BackOff                3m (x168 over 41m)  kubelet, kaiju     Back-off restarting failed container
‘’’

**Comment by yasker** [comment]
The error is `pod has unbound PersistentVolumeClaims (repeated 4 times)`. Does pvc for `data-efk-elasticsearch-1` created successfully? From the log, I saw a pvc for `data-efk-elasticsearch-2`.

**Comment by mtenrero** [comment]
Yes, longhorn managers shows so:
‘’’console
ERROR: logging before flag.Parse: I0619 01:13:48.565579       1 controller.go:817] volume "pvc-1f8edcc2-734d-11e8-8e0b-bc305bc27760" for claim "efk/data-efk-elasticsearch-1" created

ERROR: logging before flag.Parse: I0619 01:13:48.634265       1 controller.go:834] volume "pvc-1f8edcc2-734d-11e8-8e0b-bc305bc27760" for claim "efk/data-efk-elasticsearch-1" saved

ERROR: logging before flag.Parse: I0619 01:13:48.634299       1 controller.go:870] volume "pvc-1f8edcc2-734d-11e8-8e0b-bc305bc27760" provisioned for claim "efk/data-efk-elasticsearch-1"
‘’’

**Comment by mtenrero** [comment]
**get pvc**
```console
No resources found
```

**get pv**
```console
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                          STORAGECLASS   REASON    AGE
pvc-1f65b129-734d-11e8-8e0b-bc305bc27760   35Gi       RWO            Delete           Bound     efk/data-efk-elasticsearch-0   longhorn                 8h
pvc-1f8edcc2-734d-11e8-8e0b-bc305bc27760   35Gi       RWO            Delete           Bound     efk/data-efk-elasticsearch-1   longhorn                 8h
pvc-1fcfcf66-734d-11e8-8e0b-bc305bc27760   35Gi       RWO            Delete           Bound     efk/data-efk-elasticsearch-2   longhorn                 8h
```

**Comment by yasker** [comment]
@mtenrero PVCs are bounded as shown here. Another warning is `Back-off restarting failed container`. Can you check the log of your pod to see why it has failed?

**Comment by mtenrero** [comment]
```console
[2018-06-19T20:41:25,916][INFO ][o.e.n.Node               ] [] initializing ...

[2018-06-19T20:41:25,930][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]

org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment

	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.2.4.jar:6.2.4]

	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.4.jar:6.2.4]

	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.4.jar:6.2.4]

	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.4.jar:6.2.4]

	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.4.jar:6.2.4]

	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.4.jar:6.2.4]

	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.4.jar:6.2.4]

Caused by: java.lang.IllegalStateException: Failed to create node environment

	at org.elasticsearch.node.Node.<init>(Node.java:267) ~[elasticsearch-6.2.4.jar:6.2.4]

	at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.4.jar:6.2.4]

	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.4.jar:6.2.4]

	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.4.jar:6.2.4]

	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.4.jar:6.2.4]

	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.4.jar:6.2.4]

	... 6 more

Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
```
The container is trying to write in the path where te pvc should be bounded. It gets a Permission denied error.

**Comment by yasker** [comment]
@guangbochen Can you take a look? Seems elastic search assume some permission other than root when accessing the persistent storage.

**Comment by guangbochen** [comment]
@mtenrero this seems to be a pod security issue, please referecer https://github.com/elastic/elasticsearch-docker/issues/21 and you can set securityContext of your elasticsearch pod accordingly(e.g, runAsUser: 0), thanks.

**Comment by mtenrero** [comment]
I'll try to change the securityContext. But The deployment of efk comes from Rancher Library. I think we should to have a look into the deployment parameters and add the securityContext

**Comment by shay-berman** [comment]
Hi
Does anyone knows why the provisioner show this error:
`ERROR: logging before flag.Parse: I1023 08:56:12.965359       1 controller.go:407] Starting provisioner controller 7e2b06b6-d6a1-11e8-a8ea-12a49f12eb0d!`

What this error indicate for?
