### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#93]
The user no longer needs to refresh UI to get the latest information.

**Comment by LLParse** [comment]
https://github.com/rancher/longhorn-manager/pull/105
https://github.com/rancher/longhorn-ui/pull/27

**Comment by yasker** [comment]
Backend merged at https://github.com/rancher/longhorn-manager/pull/105

**Comment by yasker** [comment]
Frontend merged at https://github.com/rancher/longhorn-ui/pull/27

Feature complete for now. Please file additional issues for it later.
